Update git submodules
* Update external/libjpeg-turbo from branch 'master'
  to 090811cdb9b8ec7b7c7379264fb8f88fdb3f3aef
  - Upgrade libjpeg to 2.0.2
    
    Test: build
    Change-Id: If51cbf56f0b48fde26fac4f36d4f0219068659ac
    
  - ChangeLog.md: "floating-point"="floating point"
    
  - rpm.spec.in: Fix "File listed twice" warning/error
    
    %{_libdir}/pkgconfig is a directory and should thus be prefixed by
    %{dir} (oops.)  This issue caused the debuginfo build under RHEL 8
    (which is apparently now enabled by default-- regardless of whether the
    RPM actually contains debug info, but that's another matter) to fail
    with:
    
    RPM build errors:
      File listed twice: /opt/libjpeg-turbo/lib64/pkgconfig/libjpeg.pc
      File listed twice: /opt/libjpeg-turbo/lib64/pkgconfig/libturbojpeg.pc
    
  - rpm.spec.in: Fix doc packaging issues w/ RHEL 7+
    
    On RHEL 7 and later (not sure exactly whether this is a product of the
    newer RPM release or something distro-specific), macros are lazily
    expanded, so we need to set _docdir using %global (which expands at
    definition time) and prior to _prefix and _datarootdir (which affect
    _defaultdocdir.)  Otherwise, _docdir is set to a subdirectory of
    /opt/libjpeg-turbo/share/doc or /opt/libjpeg-turbo/doc.  The former
    (which happens on RHEL 7) leads to incorrect documentation packaging
    (the docs should be packaged under /usr/share/doc per Red Hat
    standards), and the latter (which happens on RHEL 8) leads to an RPM
    build error.
    
  - rpm.spec.in: Update deprecated [Build]Prereq tags
    
    AFAICT, Requires and BuildRequires subsumed the functionality of Prereq
    and BuildPrereq in RPM 4.0, and none of the platforms we support with
    libjpeg-turbo 2.0.x has RPM < 4.4.
    
  - GNUInstallDirs.cmake: Silence CMP0054 warning ...
    
    in CMake 3.11 and later
    
  - tjbench.c: Fix GCC 8 compiler warning
    
  - Build: Optionally install PDB files for MSVC DLLs
    
    Based on
    https://github.com/Youw/libjpeg-turbo/commit/333a36ae984a52e547ddeb23848873d3cc798047
    
    Closes #329
    Closes #324
    
  - MMI: Fix unaligned comp. perf. for 32-bit PFs also
    
    (Oversight from 1c2d3cfaaf7324d9091ba3cc4e900f60a16fe1aa)
    
  - MMI: Fix comp. perf. issue w/ unaligned image rows
    
    Using ldc1 with a non-64-bit-aligned memory location causes as much as a
    10x slow-down in overall compression performance.
    
  - Build: Fix install of static build w/ VStudio IDE
    
    Unfortunately, this hack is necessary because:
    - install(TARGETS, ...) doesn't support the RENAME option.
    - We can't modify OUTPUT_NAME for the "-static" targets without breaking
      the regression tests.
    - ${CMAKE_CFG_INTDIR} doesn't seem to work properly in an install()
      command.
    
    Refer to #307
    
  - LICENSE.md: Clarifications RE: BSD & zlib licenses
    
    Including the license templates was confusing to some, since it made
    it appear as if the copyright year and author were unspecified for the
    libjpeg-turbo source.  Thus, rather than include the zlib License
    template, link to that template on opensource.org.  For the Modified BSD
    License, include a roll-up of copyright years and authors, since the
    terms of that license require the text of it to be included in product
    documentation for binary distributions without accompanying source code.
    
  - BUILDING.md: Update/simplify Android build instr.
    
    Use the android.toolchain.cmake toolchain file in the NDK (v13b or
    later), since this toolchain file generally takes care of setting the
    approprate compiler flags and dealing with the differences between
    GCC and Clang.  Our custom Android build procedure did not work with
    Clang-based NDK toolchains, which meant that it could not be made to
    work with NDK v18b or later.
    
    Fixes #309
    
  - Build: Fix regression test failure w/ ctest -j
    
    The djpeg rgb-islow-icc-cmp test must run after the djpeg rgb-islow
    test, since the latter generates testout_rgb_islow.icc.
    
  - djpeg: Fix PPM output regression w/ color quant.
    
    Regression caused by aa7459050d7a50e1d8a99488902d41fbc118a50f
    
    Fix based on:
    https://github.com/sinic/libjpeg-turbo/commit/03fbacb8ebf1fffc3f2d2db26ddf4db8b1f6aa7b
    
    Closes #310
    
  - TurboJPEG: Decompress 4:4:4 JPEGs with unusual SFs
    
    Normally, 4:4:4 JPEGs have horizontal x vertical luminance & chrominance
    sampling factors of 1x1.  However, it is technically legal to create
    4:4:4 JPEGs with sampling factors of 2x1, 1x2, 3x1, or 1x3, since the
    sums of the products of those sampling factors are still <= 10.  The
    libjpeg API correctly decodes such images, so the TurboJPEG API should
    as well.
    
    Fixes #323
    
  - Travis: Use Homebrew addon to improve performance
    
    
  - TJBench Java: Properly handle transform warnings
    
    + warnings from TJDecompressor.decompressHeader()
    
  - TJBench: Fix FPE when decompressing 0-width JPEG
    
    Fixes #319
    
  - wrbmp.c: Don't allow quantization w/ non-RGB CS
    
    If cinfo->quantize_colors == 1, then jpeg_calc_output_dimensions() will
    set cinfo->output_components to 1, and if cinfo->out_color_space is not
    RGB (or extended RGB), hilarity will ensue.
    
    Fixes #305
    
  - wrbmp.c: Use IsExtRGB() macro where appropriate
    
    (to improve readability)
    
  - tjLoadImage(): Fix int overflow/segfault w/big BMP
    
    Fixes #304
    
  - jversion.h: Bump copyright year to 2019
    
  - Build: Fix regr. that nuked RPATH in Mac/iOS build
    
    Caused by 950580eb0c020598a4c6c8aa46c86e31062e1ddc.  Since the code that
    sets CMAKE_INSTALL_RPATH now depends on ENABLE_SHARED, that code needed
    to be moved to after the point at which ENABLE_SHARED is defined.
    
  - Bump version to 2.0.2 to prepare for new commits
    
  - Travis: Fetch GPG key from libjpeg-turbo.org
    
    I give up on the public keyserver.  It inexplicably just fails
    sometimes.  I was trying to use it out of an abundance of caution
    (<cough> paranoia <cough>), but it seems like most open source projects
    just serve up their public keys from their project web sites.  The
    private and public pre-release keys are still stored on separate sites,
    the private key is still strongly encrypted by Travis, and we use a
    separate key for pre-releases anyhow, so even if it's compromised, we
    can quickly and easily deploy a new one.
    
  - Build: Fix issue with HAVE_MAPFILE test on Solaris
    
    We have to link the test code into a shared library, or else the mapfile
    prevents necessary libc symbols from being exposed.
    
  - Travis: Try high-availability SKS keyserver pool
    
    The saga continues ...
    
  - tjbench.c: Fix compiler warnings with GCC 8
    
    strncpy() may fail to truncate dst if len == strlen(dst).
    
  - Build: Fix install error with fully static build
    
    Closes #273
    
  - Travis: Don't check key server SSL certificate
    
    ... when downloading the RPM signing key.  Apparently the key server
    URL sometimes redirects to an https URL, which may explain why fetching
    the RPM signing keys failed frequently when we used to run wget inside
    of the CentOS 5 Docker container.
    
  - Travis: Work around frequent build failures
    
    The build will consistently fail for days at a time with:
    
    error: http://pool.sks-keyservers.net/pks/lookup?op=get&search=0x0575F26BD5B3FDB1: import read failed(-1).
    
    I have a hunch that this is related to the CentOS 5 Docker container, so
    this commit causes Travis to download the RPM signing key outside of
    the container and share it with the container.
    
  - Android: Fix "using JNI after critical get" error
    
    We shouldn't be making JNI calls between GetPrimitiveArrayCritical() and
    ReleasePrimitiveArrayCritical().  Apparently Android is stricter about
    this than desktop Java.
    
    Issue was introduced in 0713c1bb542672257c08782a5a930a577eb20167.
    
    Fixes #300
    
  - Include .pc files in LJT SDKs for Visual C++
    
    These are apparently useful in certain esoteric build environments.
    
    Closes #296
    
  - cjpeg: Fix OOB read caused by malformed 8-bit TGA
    
    ... in which one or more of the color indices is out of range for the
    number of palette entries.
    
    Fix partly borrowed from jpeg-9c.
    
    Fixes #295
    
  - Clarify that Win7 SP0 crash was a regression
    
  - SIMD: Fix c000001d exception on Win 7 w/o SP1
    
    Apparently Windows 7 without SP1 has O/S support for XSAVE but not for
    YMM registers, and this exposed a bug in our usage of xgetbv.  The test
    instruction will set ZF only if none of the bits match between the two
    operarands, so in effect, we were enabling AVX2 instructions if the O/S
    supported XSAVE and the CPU supported AVX2 but the O/S only supported
    XMM registers.  This bug was not exposed on, for instance, Windows XP or
    RHEL 5 because those O/S's do not support XSAVE.
    
    Fixes #288
    
  - Build: Update javah target to work with JDK 10+
    
    javah is no longer a thing, but 'javac -h' can accomplish the same task.
    
  - BUILDING.md: Correct/update Java information
    
    - CMake 3.10.x or later must be used with JDK 11, or an error
      ("regex not supported") will occur when CMake tries to parse the Java
      version number.
    - The JDK is no longer available at java.com.
    
  - Enable DSPr2 SIMD extensions if CPU type is mipsel
    
    The DSPr2 extensions have been verified to work with little endian MIPS.
    Whether or not CMAKE_SYSTEM_PROCESSOR is set to "mips" or "mipsel" in a
    little endian MIPS environment seems to be inconsistent, but our build
    system needs to handle both cases.
    
  - Fix MIPS DSPr2 build when using soft float ABI
    
    (for instance, when passing -msoft-float to the compiler)
    
    The instructions used by jsimd_quantize_float_dspr2() and
    jsimd_convsamp_float_dspr2() don't work with the soft float ABI, so
    disable those functions when soft float is enabled.
    
    Based on:
    https://github.com/libjpeg-turbo/libjpeg-turbo/pull/272/commits/129a739bfabe1568d078eb2719691a76db128185
    
    Closes #272
    
  - jconfig.h: restore Autotools compatibility
    
    (regression introduced with the CMake-based Un*x build system)
    
    Refer to change log for more details.
    
    Based on:
    https://github.com/libjpeg-turbo/libjpeg-turbo/pull/275/commits/d992d12bc7631c29ab4adc42a7c5b4273fe2d56e
    
    Closes #275
    
  - Bump version to 2.0.1 to prepare for new commits
    
  - Correct various typos in code comments
    
    Found via `codespell -q 3`
    
    Closes #263