Update git submodules
* Update device/ti/beagle_x15 from branch 'master'
  to 46b9a5293b5f133224ff3801631ec7a6f805abe9
  - Merge "device.mk: Use dtb with symbols when possible"
  - device.mk: Use dtb with symbols when possible
    
    Use dtb files built with symbols generated (dtc -@) from
    arch/arm/boot/dts/ti directory (when it exists) to make it possible to
    apply dtbo files on those dtb files. This is needed for example when
    AM57x EVM board is used, which has LCD definition in corresponding dtbo
    file. Otherwise with the dtb under arch/arm/boot/dts, we will get kernel
    loading problem like this:
    
        failed on fdt_overlay_apply(): FDT_ERR_NOTFOUND
        base fdt does did not have a /__symbols__ node
        make sure you've compiled with -@
           Booting using the fdt blob at 0x83000000
           Loading Kernel Image ... OK
           Loading Ramdisk to 8ff45000, end 8ffff55c ... OK
        ERROR: image is not a fdt - must RESET the board to recover.
        FDT creation failed! hanging...### ERROR ### Please RESET the board ###
    
    In case of linux-mainline we don't have such directory
    (arch/arm/boot/dts/ti), so let's use regular dtb files from
    arch/arm/boot/dts, because BeagleBoard X15 doesn't require any dtbo
    files to be applied on top of dtb.
    
    dtb and dtbo files from DTB_DIR and DTBO_DIR then being packed into
    boot_fit.img file, which being read by bootloader, and bootloader can
    merge needed dtbo files into dtb file, if it's required for the board in
    use.
    
    Test: boot to homescreen
    
    Change-Id: I60085eced9f6c7e3b4705385539a877138fdb72b
    Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>
    Signed-off-by: Sam Protsenko <semen.protsenko@linaro.org>