Update git submodules
* Update external/conscrypt from branch 'master'
  to d24dd76b40a53b8131df5e4f4ceba38a0ab9bb3e
  - Merge upstream master
    
    Major changes:
    
    * TLS 1.3 support
    * Support RSA-PSS signatures with opaque keys
    * Support supported_signature_algorithms in TLS handshake
    * Improve error reporting when native library loading fails
    * Refactor TrustManagerFactoryImpl a bit
    * Reduce warnings from missing FDs
    * Merge ConscryptSocketBase into AbstractConscryptSocket
    * Fix a file descriptor leak
    
    Bug: 110403171
    Test: cts -m CtsLibcoreTestCases
    Test: cts -m CtsLibcoreOkHttpTestCases
    Test: cts -m CtsLibcoreWycheproofConscryptTestCases
    Change-Id: I621a5a1e604930ba945b4f8619fd94e29bab3790
    
  - Make TestUtils.readPublicKeyPemFile Windows-compatible (#533)
    
    When line ending conversion occurs, the PEM files can end up with CR
    characters in them, so we need to strip those as well to make the
    tests pass on Windows.
  - Support TLS 1.3 (#524)
    
    Enables support for negotiating TLS 1.3.  TLS 1.3 is not enabled
    unless SSLContext.TLSv1.3 is requested or setEnabledProtocols() is
    called with a set of values that includes TLSv1.3.
    
    Detailed changes:
    
    Adds protocol constants for TLS 1.3, and provides SSLContext.TLSv1.3,
    which has TLS 1.3 enabled by default.
    
    Adjusts cipher suite code for TLS 1.3 suites.  When enabled, all TLS
    1.3 cipher suites are always returned from supportedCipherSuites() and
    enabledCipherSuites().  Attempts to customize TLS 1.3 cipher suites in
    setEnabledCipherSuites() are ignored.
    
    Splits {SSLEngine,SSLSocket}Test into version-dependent and
    version-independent tests.  The latter remain in
    {SSLEngine,SSLSocket}Test and the former move into new files
    {SSLEngine,SSLSocket}VersionCompatibilityTest, which are parameterized
    to test all combinations of client and server on TLS 1.2 and TLS 1.3.
    
    Remove a pile of RI-specific TLS-related expectation declarations from
    StandardNames.  We don't actually verify the behavior of the RI at any
    point, so it was just making the code more confusing.
    
    Fixes #479.
  - Add some EC details to CAPABILITIES.md (#531)
    
    
  - Merge ConscryptSocketBase and AbstractConscryptSocket (#529)
    
    We used to need this separation because we had delegating sockets that
    inherited from AbstractConscryptSocket but not ConscryptSocketBase,
    but those are gone now, so we no longer need to have two classes here.
    
    While the remaining file is named AbstractConscryptSocket (to parallel
    AbstractConscryptEngine), what really happened is the abstract methods
    from AbstractConscryptSocket got merged into ConscryptSocketBase, and
    then the resulting class was renamed.
  - Tag release containers with release name (#528)
    
    This makes it easier to build two releases in parallel, for cases
    where we need to backport security fixes or otherwise build multiple
    releases in short order.
  - Start 1.3 development cycle (#526)
    
    Also update README.md for release of 1.2.0
  - Fix Javadoc dependencies (#525)
    
    
  - Support TLS 1.3 sessions. (#515)
    
    TLS 1.3 sessions are designed to only be used once, preventing
    correlation across connections.  This implements support for those
    sessions by removing such sessions from the cache whenever they're
    retrieved from the session cache and not sending them to the
    persistent (filesystem-based) cache, which we currently cannot delete
    individual items from.
    
    Also switch our per-host-port caches to support a list of cached
    sessions rather than a single one, so that if we get multiple sessions
    from the peer we can cache them all and use them when establishing
    multiple connections in parallel or such things.
  - Obey supported_signature_algorithms when present (#521)
    
    In TLS 1.2, servers can supply a list of supported signature
    algorithms, and we should base our key choice on what is supported by
    the server.  In TLS 1.3, this is the only mechanism for supplying the
    server's requirements, so this is necessary for TLS 1.3 support.
  - Reduce warning spam (#522)
    
    A significant number of log statements from this Platform method were
    due to bad file descriptors, so check for those and throw
    SocketException, which mirrors what sockets do when they have a bad
    file descriptor in other situations.
  - Provide TrustManagerFactory (#516)
    
    This is necessary for users who want to enable TLS 1.3, since the
    TrustManagerFactory implementation shipped with OpenJDK throws an
    exception if it encounters an SSLSocket or SSLEngine that's negotiated
    TLS 1.3.  Use our TrustManager in tests.
    
    Also adds a HostnameVerifier in the tests that does the simplest
    thing, because our TrustManager verifies hostnames by default, whereas
    the OpenJDK one doesn't, and the bundled HostnameVerifier on OpenJDK
    just fails to verify anything.
  - Update README.md for 1.1.4 (#518)
    
    
  - Update basic docs (#519)
    
    Add Android dependency snippets to README.md and reformat a bit.
    
    Move the source code layout info from README.md to CONTRIBUTING.md.
  - Don't init cipher suites if native code didn't load (#517)
    
    The try/catch and setting of loadError prevents the first static
    initializer in NativeCrypto from rendering the class unloadable, but
    the second static initializer still does, which means that users tend
    to get NoClassDefFoundErrors when they try to use Conscrypt instead of
    a more useful UnsatisfiedLinkError that points to the root cause.
  - Support opaque keys with RSA-PSS signatures. (#513)
    
    TLS 1.3 only uses RSA-PSS signatures (rather than RSA-PKCS#1), so we
    need to support these.  Implement it by switching to
    Cipher.RSA/ECB/NoPadding instead of using Signature.RSA.  Fix the
    opaque key tests so they actually work properly.
  - Upgrade wrapper to Gradle 4.8.1 (#506)
    
    * Upgrade wrapper to Gradle 4.8.1
    
    This fixes the temporary hack for Windows 10 SDK detection. Also updates
    some build files to work with changes in 4.8.1.
    
    This necessitates the upgrade of Android SDK build tools which causes
    cascading changes being needed in other dependencies and build files in
    Android.
    
    * Apply the Android Tools in the root project
    
    Otherwise each subproject will have its own copy of the class in its own ClassLoader. This breaks
    Android Lint tool which assumes it can cast directly to Class type.
    
    * Remove custom Test task settings
    
    These do not appear to be needed since they are not set in the regular
    test stanza. They should be set automatically by virtue of this being
    a Test type task in a java-library project.
    
  - Use Conscrypt.isConscrypt() in CryptoUpcalls. (#512)
    
    Also fix a couple typos.
  - fix #491 ConscryptEngine.closeInbound should free resources (#511)
    
    If closeOutbound is invoked prior to closeInbound, resources should
    be freed.
  - Add missing pkcs7.h include. (#510)
    
    The PKCS7_* functions are defined in pkcs7.h nowadays.
  - Fix Android benchmark references (#508)
    
    The Android benchmarks were assuming a lot of things will stay in the
    same place. Instead of hardcoding paths, try to use project properties
    to discover where the files are.
    
    Additionally make sure all the tasks have dependencies in the right
    Gradle lifecycle so they can be run individually without causing an
    error.
  - Extract loading of default CA store to Platform. (#505)
    
    The default CA store on Android is built into the platform, so we can
    simply fetch it.
    
    For OpenJDK, we look for the highest-priority non-Conscrypt
    TrustManagerFactory that produces at least one certificate.  If the
    user has just installed Conscrypt as the first provider, which is
    typical, this means we should get the OpenJDK-provided implementation,
    which uses a variety of system properties to determine where to find
    the CA certs.  Otherwise, whatever system they've previously been
    using to choose the set of trusted CA certs will continue to work.
  - Move TrustManagerImpl to common. (#503)
    
    This is the first step in making the TrustManager implementation
    available on OpenJDK, which is necessary for TLS 1.3 because the
    TrustManager implementations in OpenJDK throw an exception when they
    encounter an SSLSocket or SSLEngine that reports a protocol not in
    their enumerated lists.  It moves the code and tests over so they
    compile on OpenJDK, but doesn't yet change anything about the
    provider, so the code isn't used.
    
    There are a few changes necessary:
    
    Extract an interface for TrustedCertificateStore, which is still
    platform-only due to its reliance on specific directories to find
    certs and other details of the Android platform.
    
    Extract an interface for CertBlacklist, for the same reason.
    
    Adjust TrustManagerImpl to get implementations of the add-on
    functionality (CertBlacklist, CTLogStore, and CTPolicy) from the
    Platform class instead of constructing them itself and tolerate nulls
    for those classes.  The Platform classes for non-platform builds
    return null for those classes, but we might want to change that in the
    future.
    
    Make a few minor changes while moving things over (JDK 6 source
    compatibility, adjust tests for JUnit4, etc.).
  - Add doc listing Conscrypt capabilities. (#504)
    
    This will be useful to indicate what we do and don't support, as well
    as a place to indicate our implementation-specific choices (like MGF1
    digest or TLS 1.3 choices).
    
    Also standardize on lowercase "with" in Signature algorithm IDs.  The
    RSA ones used "With" and the ECDSA and PSS ones used "with", so it's
    2:1 in favor of lowercase.  JCA algorithm identifiers are matched
    case-insensitively, so this is just for display purposes.

* Update frameworks/base from branch 'master'
  to 27eec4b376b098892d8292e97fe03c37de988b4c
  - Merge "Update greylist for Conscrypt update"
  - Update greylist for Conscrypt update
    
    Conscrypt has been refactored to eliminate the ConscryptSocketBase
    class, so its greylisted methods no longer exist.
    
    Test: make droid
    Change-Id: Iffcfe529d960a397d0ced012f5a97de93dde69fa
    

* Update libcore from branch 'master'
  to c6c57023fb7ebbf50cb87a8dea1618b8feb254ce
  - Merge "Update tests for Conscrypt update"
  - Update tests for Conscrypt update
    
    This mainly updates the tests to account for the existence of TLS 1.3.
    In particular, add the new TLS 1.3-related constants to StandardNames
    and update some old harmony tests to handle the fact that we now
    report TLS 1.3 cipher suites as being supported.
    
    Bug: 110403171
    Test: cts -m CtsLibcoreTestCases
    Test: cts -m CtsLibcoreOkHttpTestCases
    Test: cts -m CtsLibcoreWycheproofConscryptTestCases
    Change-Id: I1ff6aa5961438527b0eb882488a5dbfaaeaacc6c