Update git submodules
* Update device/generic/goldfish-opengl from branch 'master'
  to 5ae1f3b377d8fc61f02f5d7939d21b5d09dbc639
  - Merge "Revert "Add GoldfishAddressSpaceBlock::memoryMap""
  - Revert "Add GoldfishAddressSpaceBlock::memoryMap"
    
    This reverts commit 659aafc0cfbeb574b5ffa0c3e107a1cdb339a2d1.
    
    Reason for revert: 3:27(05:36.14) rel | warning: /Applications/Xcode9.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: warning for library: archives/libEMULATOR_FEATURE_DEPENDENCIES.a the table of contents is empty (no object file members in the library define global symbols)
    12:43:27(05:37.68) rel | [3477/8089] Building CXX object android/android-emugl/guest/CMakeFiles/cutils.dir/androidImpl/Unicode.cpp.o
    12:43:27(05:37.38) rel | [3478/8089] Building CXX object android/android-emugl/goldfish-opengl/shared/OpenglCodecCommon/CMakeFiles/OpenglCodecCommon_host.dir/ChecksumCalculator.cpp.o
    12:43:27(05:37.84) rel | [3479/8089] Building CXX object android/android-emu/CMakeFiles/emulator-libui-headless.dir/android/recording/screen-recorder.cpp.o
    12:43:27(05:37.39) rel | [3480/8089] Building CXX object android/android-emugl/goldfish-opengl/shared/OpenglCodecCommon/CMakeFiles/OpenglCodecCommon_host.dir/GLESTextureUtils.cpp.o
    12:43:27(05:37.45) rel | [3481/8089] Building CXX object android/android-emugl/guest/CMakeFiles/cutils.dir/androidImpl/RefBase.cpp.o
    12:43:28(05:37.22) rel | [3482/8089] Building CXX object android/android-emu/CMakeFiles/emulator-libui-headless.dir/android/recording/video/VideoProducer.cpp.o
    12:43:28(05:37.77) rel | [3483/8089] Building CXX object android/android-emugl/goldfish-opengl/shared/OpenglCodecCommon/CMakeFiles/OpenglCodecCommon_host.dir/glUtils.cpp.o
    12:43:28(05:37.18) rel | [3484/8089] Building CXX object android/android-emugl/goldfish-opengl/shared/OpenglCodecCommon/CMakeFiles/OpenglCodecCommon_host.dir/auto_goldfish_dma_context.cpp.o
    12:43:28(05:37.24) rel | [3485/8089] Building CXX object android/android-emugl/goldfish-opengl/shared/OpenglCodecCommon/CMakeFiles/OpenglCodecCommon_host.dir/SocketStream.cpp.o
    12:43:28(05:38.60) rel | [3486/8089] Building CXX object android/android-emugl/guest/CMakeFiles/cutils.dir/androidImpl/String16.cpp.o
    12:43:28(05:38.4 ) rel | [3487/8089] Building CXX object android/android-emugl/guest/CMakeFiles/cutils.dir/androidImpl/String8.cpp.o
    12:43:28(05:38.32) rel | [3488/8089] Building CXX object android/android-emugl/goldfish-opengl/shared/OpenglCodecCommon/CMakeFiles/OpenglCodecCommon_host.dir/TcpStream.cpp.o
    12:43:28(05:38.28) rel | [3489/8089] Building CXX object android/android-emu/CMakeFiles/emulator-libui-headless.dir/android/recording/FfmpegRecorder.cpp.o
    12:43:28(05:38.46) rel | [3490/8089] Building CXX object android/android-emugl/goldfish-opengl/shared/OpenglCodecCommon/CMakeFiles/OpenglCodecCommon_host.dir/goldfish_dma_host.cpp.o
    12:43:28(05:38.23) rel | [3491/8089] Building CXX object android/android-emugl/guest/CMakeFiles/cutils.dir/androidImpl/Properties.cpp.o
    12:43:28(05:38.92) rel | [3492/8089] Building CXX object android/android-emugl/goldfish-opengl/system/GLESv1_enc/CMakeFiles/GLESv1_enc.dir/gl_client_context.cpp.o
    12:43:28(05:38.14) rel | [3493/8089] Building CXX object android/android-emu/CMakeFiles/emulator-libui-headless.dir/android/emulation/control/ScreenCapturer.cpp.o
    12:43:29(05:38.10) rel | [3494/8089] Building CXX object android/android-emugl/guest/CMakeFiles/vulkan_android.dir/libvulkan/swapchain.cpp.o
    12:43:29(05:38.38) rel | [3495/8089] Building CXX object android/android-emugl/CMakeFiles/GLESv2_dec.dir/host/libs/GLESv2_dec/GLESv2Decoder.cpp.o
    12:43:29(05:38.68) rel | [3496/8089] Building CXX object android/android-emugl/guest/CMakeFiles/gui_unittests.dir/androidImpl/libgui_unittest.cpp.o
    12:43:29(05:39.25) rel | [3497/8089] Building CXX object android/android-emugl/guest/CMakeFiles/cutils.dir/androidImpl/Ashmem.cpp.o
    12:43:29(05:39.5 ) rel | [3498/8089] Building CXX object android/android-emugl/goldfish-opengl/shared/OpenglCodecCommon/CMakeFiles/OpenglCodecCommon_host.dir/IndexRangeCache.cpp.o
    12:43:29(05:39.81) rel | [3499/8089] Building CXX object android/android-emugl/goldfish-opengl/shared/OpenglCodecCommon/CMakeFiles/OpenglCodecCommon_host.dir/goldfish_address_space.cpp.o
    12:43:29(05:39.78) rel | FAILED: android/android-emugl/goldfish-opengl/shared/OpenglCodecCommon/CMakeFiles/OpenglCodecCommon_host.dir/goldfish_address_space.cpp.o
    12:43:29(05:39.46) rel | /Volumes/Android/buildbot/src/android/emu-master-dev/out/toolchain/g++ -DANDROID -DANDROID_GRPC -DEMULATOR_OPENGL_POST_O=1 -DGL_GLEXT_PROTOTYPES -DGOLDFISH_HIDL_GRALLOC -DGOLDFISH_VULKAN -DHOST_BUILD -DLIBXML_STATIC -DLOG_TAG=\"eglCodecCommon\" -DNDEBUG=1 -DOpenglCodecCommon_host_EXPORTS -DPAGE_SIZE=4096 -DPLATFORM_SDK_VERSION=29 -DWITH_GLES2 -D_DARWIN_C_SOURCE=1 -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE=1 -D_LARGEFILE_SOURCE -D_LIBCPP_VERSION=__GLIBCPP__ -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS=1 -D__STDC_LIMIT_MACROS=1 -I/Volumes/Android/buildbot/src/android/emu-master-dev/device/generic/goldfish-opengl/shared/OpenglCodecCommon -I/Volumes/Android/buildbot/src/android/emu-master-dev/device/generic/goldfish-opengl/./host/include/libOpenglRender -I/Volumes/Android/buildbot/src/android/emu-master-dev/device/generic/goldfish-opengl/./system/include -I/Volumes/Android/buildbot/src/android/emu-master-dev/device/generic/goldfish-opengl/./../../../external/qemu/android/android-emugl/guest -I/Volumes/Android/buildbot/src/android/emu-master-dev/external/qemu/android/android-emugl/host/include -I/Volumes/Android/buildbot/src/android/emu-master-dev/external/qemu/android/android-emugl/shared -I/Volumes/Android/buildbot/src/android/emu-master-dev/external/qemu/android-qemu2-glue/config/darwin-x86_64 -I/Volumes/Android/buildbot/src/android/emu-master-dev/external/qemu/android/android-emu -Iandroid/android-emu -I/Volumes/Android/buildbot/src/android/emu-master-dev/external/qemu/android/android-emugl/guest/. -I/Volumes/Android/buildbot/src/android/emu-master-dev/external/qemu/android/android-emu/. -O3 -g3 -Wno-everything -fmacro-backtrace-limit=0 -Wno-unknown-warning-option -Wno-unknown-argument -g -fno-rtti -fno-exceptions -Wno-invalid-offsetof -Wno-return-type -Wno-unused-value -Wno-inconsistent-missing-override -Wno-deprecated-declarations -O3 -DNDEBUG -fPIC -fvisibility=default -Wno-unused-parameter -Wno-unused-private-field -Wno-return-type-c-linkage -MD -MT android/android-emugl/goldfish-opengl/shared/OpenglCodecCommon/CMakeFiles/OpenglCodecCommon_host.dir/goldfish_address_space.cpp.o -MF android/android-emugl/goldfish-opengl/shared/OpenglCodecCommon/CMakeFiles/OpenglCodecCommon_host.dir/goldfish_address_space.cpp.o.d -o android/android-emugl/goldfish-opengl/shared/OpenglCodecCommon/CMakeFiles/OpenglCodecCommon_host.dir/goldfish_address_space.cpp.o -c /Volumes/Android/buildbot/src/android/emu-master-dev/device/generic/goldfish-opengl/shared/OpenglCodecCommon/goldfish_address_space.cpp
    12:43:29(05:39.42) rel | In file included from /Volumes/Android/buildbot/src/android/emu-master-dev/device/generic/goldfish-opengl/shared/OpenglCodecCommon/goldfish_address_space.cpp:17:
    12:43:29(05:39.47) rel | In file included from /Volumes/Android/buildbot/src/android/emu-master-dev/device/generic/goldfish-opengl/shared/OpenglCodecCommon/goldfish_address_space_host.impl:25:
    12:43:29(05:39.96) rel | /Volumes/Android/buildbot/src/android/emu-master-dev/device/generic/goldfish-opengl/shared/OpenglCodecCommon/goldfish_address_space.h:86:77: error: unknown type name 'off64_t'; did you mean 'off_t'?
    12:43:29(05:39.19) rel | static int memoryMap(void *addr, size_t len, address_space_handle_t fd, off64_t off, void** dst);
    12:43:29(05:39.23) rel | ^~~~~~~
    12:43:29(05:39.67) rel | off_t
    12:43:29(05:39.14) rel | /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/sys/_types/_off_t.h:31:25: note: 'off_t' declared here
    12:43:29(05:39.72) rel | typedef __darwin_off_t off_t;
    12:43:29(05:39.68) rel | ^
    12:43:29(05:39.35) rel | In file included from /Volumes/Android/buildbot/src/android/emu-master-dev/device/generic/goldfish-opengl/shared/OpenglCodecCommon/goldfish_address_space.cpp:17:
    12:43:29(05:39.63) rel | /Volumes/Android/buildbot/src/android/emu-master-dev/device/generic/goldfish-opengl/shared/OpenglCodecCommon/goldfish_address_space_host.impl:186:42: error: unknown type name 'off64_t'; did you mean 'off_t'?
    12:43:29(05:39.90) rel | off64_t,
    12:43:29(05:39.21) rel | ^~~~~~~
    12:43:29(05:39.79) rel | off_t
    12:43:29(05:39.77) rel | /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/sys/_types/_off_t.h:31:25: note: 'off_t' declared here
    12:43:29(05:39.48) rel | typedef __darwin_off_t off_t;
    12:43:29(05:39.15) rel | ^
    12:43:29(05:39.23) rel | 2 errors generated.
    12:43:29(05:39.18) rel | [3500/8089] Building CXX object android/android-emugl/goldfish-opengl/system/GLESv2_enc/CMakeFiles/GLESv2_enc.dir/gl2_client_context.cpp.o
    12:43:29(05:39.44) rel | [3501/8089] Building CXX object android/android-emugl/host/libs/libOpenglRender/CMakeFiles/OpenglRender_vulkan.dir/vulkan/VkDecoder.cpp.o
    12:43:29(05:39.53) rel | [3502/8089] Linking CXX shared library lib64/libcutils.dylib
    12:43:30(05:39.89) rel | [3503/8089] Building CXX object android/android-emugl/goldfish-opengl/system/GLESv1_enc/CMakeFiles/GLESv1_enc.dir/gl_entry.cpp.o
    12:43:30(05:39.34) rel | [3504/8089] Building CXX object android/android-emugl/goldfish-opengl/shared/OpenglCodecCommon/CMakeFiles/OpenglCodecCommon_host.dir/qemu_pipe_host.cpp.o
    12:43:30(05:40.49) rel | [3505/8089] Building CXX object android/android-emugl/goldfish-opengl/system/GLESv1_enc/CMakeFiles/GLESv1_enc.dir/GLEncoderUtils.cpp.o
    12:43:31(05:40.49) rel | [3506/8089] Building CXX object android/android-emugl/goldfish-opengl/system/GLESv2_enc/CMakeFiles/GLESv2_enc.dir/gl2_entry.cpp.o
    12:43:31(05:40.66) rel | [3507/8089] Building CXX object android/android-emugl/goldfish-opengl/system/GLESv2_enc/CMakeFiles/GLESv2_enc.dir/GL2EncoderUtils.cpp.o
    12:43:31(05:41.39) rel | [3508/8089] Building CXX object android/android-emugl/goldfish-opengl/system/GLESv1_enc/CMakeFiles/GLESv1_enc.dir/GLEncoder.cpp.o
    12:43:31(05:41.73) rel | [3509/8089] Building CXX object android/android-emugl/goldfish-opengl/system/GLESv2_enc/CMakeFiles/GLESv2_enc.dir/__/enc_common/IOStream_common.cpp.o
    12:43:31(05:41.19) rel | [3510/8089] Building CXX object android/android-emu/CMakeFiles/emulator-libui-headless.dir/android/recording/video/player/VideoPlayer.cpp.o
    12:43:31(05:41.95) rel | [3511/8089] Building CXX object android/android-emugl/host/libs/libOpenglRender/CMakeFiles/OpenglRender_vulkan.dir/vulkan/VkReconstruction.cpp.o
    12:43:32(05:41.78) rel | [3512/8089] Building CXX object android/android-emugl/goldfish-opengl/system/GLESv2_enc/CMakeFiles/GLESv2_enc.dir/GLESv2Validation.cpp.o
    12:43:32(05:42.90) rel | [3513/8089] Building CXX object android/android-emugl/goldfish-opengl/system/GLESv1_enc/CMakeFiles/GLESv1_enc.dir/gl_enc.cpp.o
    12:43:32(05:42.66) rel | [3514/8089] Building CXX object android/android-emugl/goldfish-opengl/shared/OpenglCodecCommon/CMakeFiles/OpenglCodecCommon_host.dir/GLSharedGroup.cpp.o
    12:43:33(05:43.11) rel | [3515/8089] Building CXX object android/android-emugl/goldfish-opengl/shared/OpenglCodecCommon/CMakeFiles/OpenglCodecCommon_host.dir/GLClientState.cpp.o
    12:43:33(05:43.6 ) rel | [3516/8089] Automatic MOC, UIC and RCC for target emulator-libui
    12:43:34(05:43.55) rel | [3517/8089] Building CXX object android/android-emugl/goldfish-opengl/system/GLESv2_enc/CMakeFiles/GLESv2_enc.dir/gl2_enc.cpp.o
    12:43:35(05:44.34) rel | [3518/8089] Building CXX object android/android-emugl/goldfish-opengl/system/GLESv2_enc/CMakeFiles/GLESv2_enc.dir/GL2Encoder.cpp.o
    12:43:39(05:49.83) rel | [3519/8089] Building CXX object android/android-emugl/host/libs/libOpenglRender/vulkan/cereal/CMakeFiles/OpenglRender_vulkan_cereal.dir/common/goldfish_vk_baseprotoconversion.cpp.o
    12:43:40(05:50.71) rel | [3520/8089] Building CXX object android/android-emugl/host/libs/Translator/GLES_CM/CMakeFiles/GLES_CM_translator.dir/GLEScmImp.cpp.o
    12:43:43(05:52.75) rel | [3521/8089] Building CXX object android/android-emugl/CMakeFiles/GLESv2_dec.dir/gles2_dec.cpp.o
    12:43:43(05:53.60) rel | [3522/8089] Building CXX object android/android-emugl/host/libs/libOpenglRender/CMakeFiles/OpenglRender_vulkan.dir/vulkan/VkDecoderGlobalState.cpp.o
    12:43:55(06:05.16) rel | [3523/8089] Building CXX object android/android-emugl/host/libs/Translator/GLES_V2/CMakeFiles/GLES_V2_translator.dir/GLESv2Imp.cpp.o
    12:46:11(08:20.71) rel | [3524/8089] Building CXX object android/android-emugl/host/libs/libOpenglRender/vulkan/cereal/proto/CMakeFiles/OpenglRender_vulkan_cereal_proto.dir/goldfish_vk_baseprotodefs.pb.cc.o
    12:46:11(08:20.3 ) rel | ninja: build stopped: subcommand failed.
    12:46:11(08:20.10) rel | Traceback (most recent call last):
    12:46:11(08:20.3 ) rel | File "/Volumes/Android/buildbot/src/android/emu-master-dev/external/qemu/android/build/python/cmake.py", line 20, in <module>
    12:46:11(08:20.19) rel | cmake.launch()
    12:46:11(08:20.19) rel | File "/Volumes/Android/buildbot/src/android/emu-master-dev/external/qemu/android/build/python/aemu/cmake.py", line 181, in launch
    12:46:11(08:20.88) rel | app.run(main)
    12:46:11(08:20.98) rel | File "/Users/android-build/Library/Python/2.7/lib/python/site-packages/absl_py-0.6.1-py2.7.egg/absl/app.py", line 300, in run
    12:46:11(08:20.7 ) rel | _run_main(main, args)
    12:46:11(08:20.35) rel | File "/Users/android-build/Library/Python/2.7/lib/python/site-packages/absl_py-0.6.1-py2.7.egg/absl/app.py", line 251, in _run_main
    12:46:11(08:20.90) rel | sys.exit(main(argv))
    12:46:11(08:20.78) rel | File "/Volumes/Android/buildbot/src/android/emu-master-dev/external/qemu/android/build/python/aemu/cmake.py", line 150, in main
    12:46:11(08:20.52) rel | run(get_build_cmd())
    12:46:11(08:20.44) rel | File "/Volumes/Android/buildbot/src/android/emu-master-dev/external/qemu/android/build/python/aemu/process.py", line 101, in run
    12:46:11(08:20.90) rel | (' '.join(cmd), proc.returncode))
    12:46:11(08:20.79) rel | Exception: Failed to run /Volumes/Android/buildbot/src/android/emu-master-dev/prebuilts/cmake/darwin-x86/bin/cmake --build /Volumes/Android/buildbot/src/android/emu-master-dev/out --target install/strip - 1
    Traceback (most recent call last):
    File "tools/buildSrc/servers/build_tools.py", line 198, in <module>
    main(sys.argv)
    File "tools/buildSrc/servers/build_tools.py", line 191, in main
    run(launcher + cmd + prod, cfg.get_env(), 'rel')
    File "tools/buildSrc/servers/build_tools.py", line 83, in run
    (" ".join(cmd), proc.returncode))
    Exception: Failed to run /usr/bin/python /Volumes/Android/buildbot/src/android/emu-master-dev/external/qemu/android/build/python/cmake.py --noqtwebengine --noshowprefixforinfo --out /Volumes/Android/buildbot/src/android/emu-master-dev/out --sd
    
    Change-Id: Ifda8e42157dc7fdae3b75b1840501411be26ffca