Update git submodules
* Update external/toybox from branch 'master'
  to 7a03bafda6c2b288cdd9c7fce63cf66618757a0e
  - Merge remote-tracking branch 'toybox/master' into HEAD
    
    Change-Id: I82b1111110115386f99b26b8114fab491bf8396e
    
  - Promote i2ctools.
    
    (Fixed one declaration not at start of a block.)
    
  - Implement i2c utilities.
    
    This is enough to cover the use cases of the Android users I know of.
    
    Bug: http://b/115644518
    
  - Stack can grow in either direction, so needs signed subtraction and abs().
    Both positive and both negative should work, even crossing midpoint (which
    should never happen on linux) works in two's complement.
    
  - file: remove %s with no corresponding argument.
    
    I've had added the argument, but I don't know what it wants? Ubuntu's file
    calls a bmp file "data".
    
  - Nommu systems want to _exit() after vfork when exec fails, but should do cleanup ala fflush(0) after a normal exec() failure.
    
  - It should never matter on Linux (where the top half of virtual address space
    is reserved for the kernel), but technically a pointer is unsigned long.
    
  - Fluff up the roadmap a bit.
    
  - Add .bmp supoprt to file(1).
    
  - Add .wav support to file(1).
    
  - Fix glibc build after 013876f067a11ebfcf47789921b376e7bf3bf5b8.
    
    /usr/include/unistd.h:626:15: error: conflicting types for 'confstr'
    
  - Add a couple Android NDK links for reference.
    
  - Variable data needs to go at the end.
    
  - Tweaks to make building with Android NDK's llvm happier.
    
  - Clean up test.c
    
    * A number of logic and style fixes
    * No longer changes toys.optargs and toys.optc
    * Now supports ( ) ! -a -o
    * Supports POSIX special cases for low argument count
    
  - Convert option style.
    
  - added fold test for discussion
    
  - Add a test case raised on the list.
    
  - Add binary file detection to grep.
    
  - Convert more commands to the new option/GLOBALS code style.
    
  - Remove ls sub-option: always support --color.
    
    (Well, when you say --color or "alias ls='ls --color=auto'" in your shell.)
    
  - Convert more argument variables in GLOBALS() to new style.
    
  - Coding style change: 1) Use argument letter for variable names filled out by
    that argument (so "t:" fills out TT.t), 2) go ahead and collate arguments of
    same type on same line. (Order's guaranteed by C99 either way.)
    
  - Use \033 instead of \e gcc extension.
    
  - Oneit shouldn't reboot the system if it's not pid 1.
    
  - Comment tweak.
    
  - Allow enough space padding for "192.168.123.456/24" to consistently indent.
    
  - Make microcom use set_terminal() and move speed setting into set_terminal().
    
  - Add bc (and its tests) to pending
    
  - Added support for a fourth field in mdev.conf
    
  - Forgot to check in the deflate header change, and pending shouldn't default y.