Update git submodules
* Update external/autotest from branch 'master'
  to 6c7a26bfdf7c45cca31ecf94e3ae0ad39dfa5864
  - Revert "Add applicable_models to TestConfig."
    am: 9b13af1f6a
    
    Change-Id: If39eee383613fc93ab174fedec4b5e998dbc45de
    
  - Revert "Add applicable_models to TestConfig."
    
    This reverts commit 5b5ddff0e8c3bab5634e4d4753df6ae8577934de.
    
    Reason for revert: breaks chromite unit tests, as in https://ci.chromium.org/p/chromeos/builders/cq/chromite-cq/b8900050863131122272 
    
    
    ======================================================================
    ERROR: [chromite.lib.paygen.paygen_build_lib_unittest] HWTest.testTestPlan
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/mnt/host/source/chromite/lib/timeout_util.py", line 191, in TimeoutWrapper
        return func(*args, **kwargs)
      File "/mnt/host/source/chromite/lib/paygen/paygen_build_lib_unittest.py", line 1327, in testTestPlan
        build='dummy-build')
      File "/mnt/host/source/chromite/lib/paygen/paygen_build_lib.py", line 1248, in _TestPlan
        shown_test_name = '%s_%s' % (test_name, payload_test.unique_name_suffix())
      File "/mnt/host/source/src/third_party/autotest/files/site_utils/autoupdate/lib/test_params.py", line 132, in unique_name_suffix
        self.source_release, self.payload_type.lower())
    AttributeError: 'NoneType' object has no attribute 'lower'
    
    
    Original change's description:
    > Add applicable_models to TestConfig.
    > 
    > The applicable_models are the list of models that an FSI config should
    > run against. These come from the paygen.json provided by GE and will be
    > passed in here by chromite's paygen_build_lib. Currently we run all FSI
    > configs on all unibuild models. With the applicable_models list here it
    > will be easy to filter configs by model.
    > 
    > Also removes a hack for figuring out suffix of test name in a previous
    > CL while I waited for a chromite CL to land.
    > 
    > BUG=chromium:909972
    > TEST=tryjob
    > 
    > Change-Id: I19b0845467aad0a09832f073fb0df53b9e37ee78
    > Reviewed-on: https://chromium-review.googlesource.com/1834105
    > Tested-by: David Haddock <dhaddock@chromium.org>
    > Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
    > Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
    > Reviewed-by: Amin Hassani <ahassani@chromium.org>
    
    Bug: chromium:909972
    Change-Id: Iac227c7414843f6c756ce9b4386e47dfbacff59c
    Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/1850712
    Reviewed-by: Sean Abraham <seanabraham@chromium.org>
    Reviewed-by: David Haddock <dhaddock@chromium.org>
    Commit-Queue: Sean Abraham <seanabraham@chromium.org>
    Tested-by: Sean Abraham <seanabraham@chromium.org>