Update git submodules
* Update external/llvm from branch 'lldb-master-dev'
  to 59877d3409fa580aaeda8e9e0bc88f7a3b24d432
  - Merge "Revert r338354 "[ARM] Revert r337821" am: 1fa19f6800" into lldb-master-dev
  - Revert r338354 "[ARM] Revert r337821"
    am: 1fa19f6800
    
    Change-Id: I07161f433a0fd90f2ecbdb4a52200186c2aa90c3
    
  - Revert r338354 "[ARM] Revert r337821"
    
    Disable ARMCodeGenPrepare by default again. It is causing verifier
    failues in V8 that look like:
    
      Duplicate integer as switch case
      switch i32 %trunc, label %if.end13 [
        i32 0, label %cleanup36
        i32 0, label %if.then8
      ], !dbg !4981
      i32 0
      fatal error: error in backend: Broken function found, compilation aborted!
    
    I will continue reducing the test case and send it along.
    
    git-svn-id: https://llvm.org/svn/llvm-project/llvm/trunk@338452 91177308-0d34-0410-b5e6-96231b3b80d8