Update git submodules
* Update bionic from branch 'pie-gsi'
  to b5e5388aca8bdd473769364f82f36e5bce12c5b5
  - Merge "Merge pi-qpr1-release PQ1A.181105.017.A1 to pi-platform-release am: 814964e054" into pie-gsi
  - Merge pi-qpr1-release PQ1A.181105.017.A1 to pi-platform-release
    am: 814964e054
    
    Change-Id: I7d79db426636c73ed43d83b66d1fbb9bf46e5e1e
    
  - Merge pi-qpr1-release PQ1A.181105.017.A1 to pi-platform-release
    
    Change-Id: Ic9f65be968a41b3419a655102838a432f8d3b62d
    
  - Snap for 4920102 from fbe26c723af60b101a6df9c066c1b661b6ab966c to pi-qpr1-release
    
    Change-Id: Ifd7027234368d31d675303934b1f0f8b6e23d714
    
  - Merge "remove bionic-compile-time-tests-g++" into pi-dev
  - Snap for 4916303 from 6fffb2332ca3be3abee84810b389a29b731887ee to pi-qpr1-release
    
    Change-Id: If8971618ca5839bb3044dd35acbd31189ebb613e
    
  - remove bionic-compile-time-tests-g++
    
    make checkbuild gives the following error:
    bionic/tests/fortify_filecheck_diagnostics_test.cpp:1:0: error: unknown value 'cortex-a55' for -mcpu
    
    The error is because we have a clang to support the new architecture,
    but not a corresponding GCC. It is not trivial to filter out an invalid
    CPU, and since there is no platform code built with GCC any more, its
    better to remove bionic-compile-time-tests-g++
    
    Bug: 74404306
    Change-Id: I6aa181c652abeef782fec6380dfadd066140b8b9
    
  - Disable malloc debug intercepts when exiting.
    
    There is a hang when enabling leak_track since the dumping of the
    leak data can wind up doing an allocation.
    
    Add new system unit test to make sure this doesn't happen again.
    
    Bug: 111146059
    
    Test: Test program that leaks does not hang forever.
    Test: Unit tests pass.
    Change-Id: Icf99be58ba5db98ee124a471b957a086045f5870
    Merged-In: Icf99be58ba5db98ee124a471b957a086045f5870
    (cherry picked from commit 97b474710225bc4853ab314c3d9ca812dc375525)
    
  - Merge "Reland "Remove a check for AIDs in the OEM range."" into pi-dev
  - Reland "Remove a check for AIDs in the OEM range."
    
    There may be vendor extensions to the system image which would need to
    use these IDs.
    
    This reverts commit 41986a013a10c6f79822002800a9afe90efba4f2.
    
    Bug: 110856218
    Test: these tests