Update git submodules
* Update system/bt from branch 'master'
  to 9f8b1301adf1cdf5aaca946b491374580c12a0df
  - Reorder static libs to appease ld.gold linker
    
    Bug: http://b/112277682
    Bug: http://b/79419131
    
    Lld, which is the default linker for the platform, is able to resolve
    symbols across libraries irrespective of the order they appear in the
    command line.  This was not the case for ld.gold and other linkers.
    Unfortunately, there are some targets that still rely on ld.gold
    (pgo-taimen-config1 in internal release branch being one of
    them).
    
    With http://aosp/721652, libbt-stack should be added before libbt-common
    so MessageLoopThread::~MessageLoopThread is resolved correctly.  If not,
    the following error is reported by gold:
    
    system/bt/stack/btu/btu_init.cc:41: error: undefined reference to
    'bluetooth::common::MessageLoopThread::MessageLoopThread(std::__1::basic_string<char,
    std::__1::char_traits<char>, std::__1::allocator<char> > const&)'
    
    Test: m USE_CLANG_LLD=false
    Change-Id: I9c8208218ffb4bb027ad75b51bcd484e9bb37368