Update git submodules
* Update external/fmtlib from branch 'master'
  to 71aa0b1047729072861452eda91eaa957d95c9ce
  - Upgrade fmtlib to 6.1.0
    
    Test: None
    Change-Id: I5db685146ca9241665ada5e15523666e48e67f3f
    
  - Update version
    
  - Bump version
    
  - Update changelog
    
  - Update changlog
    
  - Update docs
    
  - Put vprint declarations in one place
    
  - Fixing installation directory of '*.dll' files on Windows
    
  - Clean up includes
    
  - Update changlog
    
  - Update changelog
    
  - Update changelog
    
  - Avoid wchar_t instantiations
    
  - Squelch MSVC warning exporting subclasses of runtime_error
    
    When compiling {fmt} as a DLL, MSVC complains that we are exporting
    classes that inherit from "std::runtime_error", which we are not
    exporting.
    
    In this case, it's not really a problem because that symbol is already
    exported via the C++ stdlib. So we just add a pragma to silence the
    warning.
    
  - Update changelog
    
  - digits -> num_bits
    
  - Fix dangling else problem in FMT_ASSERT
    
  - Fix handling of fallback_uintptr
    
  - Remove dependency on <cassert>
    
  - Fix fallback pointer formatting on big endian, take 2
    
  - Fix handling of missing fraction in snprintf_float
    
  - Fix fallback pointer formatting on big endian
    
  - Update docs
    
  - Update changelog
    
  - Remove invalid noexcept annotation
    
    buffered_file& operator=(buffered_file&& other) calls close which can
    throw.
    
  - Fix -Wconversion warnings
    
  - Update changelog
    
  - Add missing newline
    
  - Update docs
    
  - Refactor floating-point formatting
    
  - float_spec -> float_specs
    
  - Remove gen_digits_params
    
  - Enable -Wswitch-enum in CI
    
  - Update README.rst
  - Fix precision handling in snprintf_float
    
  - Fix handling of streamable and convertible to string types
    
  - Fix hexfloat buffer reallocation
    
  - Fix handling of types with deleted rvalue conversion to string (#1421)
    
  - Update comment
    
  - Remove fp::operator-
    
  - Simplify Grisu implementation
    
  - Instantiate snprintf_float
    
  - Minor cleanup
    
  - Don't print trailing zero with fixed, precision=0, and showpoint (#1417)
    
  - Handle null terminator at the end of the buffer
    
  - fix bad oss fuzz link in the oss-fuzz badge
    
  - Integrate Grisu and sprintf digit generators
    
  - Refactor floating-point formatting
    
  - Merge branch 'float'
    
  - Merge branch 'master' of github.com:fmtlib/fmt
    
  - Refactor floating point formatting
    
  - Cleanup FP formatting
    
  - Don't print % for nan and inf
    
  - Merge write_fp into write
    
  - Update comment
    
  - Update README.rst
  - Update README.rst
  - Move basic_writer::write_fp to where it belongs
    
  - Make parse_arg_id more readable
    
  - Merge safe-duration-cast.h into chrono.h
    
  - Remove redundant qualification
    
  - warning C4456: declaration of 'num_digits' hides previous local declaration
    
  - Use grisu for exponent notation
    
  - Don't parse % unless FMT_DEPRECATED_PERCENT is set
    
  - Deprecate the fmt macro
    
  - Remove Grisu2
    
  - test: add default constructor for a const value
    
    This fixed a compilation error of the OS X 10.11.6 C++ compiler:
    
        ./fmt/test/format-test.cc:1861:16: error: default initialization of an object of const type 'const Answer' without a user-provided default constructor
          const Answer const_answer;
                       ^
                                   {}
    
  - Make % an opt-in to improve compatibility with std::format
    
  - Refactor float spec parsing
    
  - Replace bool with float_format and add exponential
    
  - Move float_spec_handler to internal namespace and update asserts
    
  - Fix indentation
    
  - Clarify that numeric alignment is deprecated
    
  - Apply coding conventions to examples
    
  - Apply coding conventions to examples
    
  - Tweak the docs
    
  - Document and clean basic_format_parse_context
    
  - Bump version
    
  - Don't use POSIX API on UWP
    
  - Use overridden locale in ostream
    
  - Tweak the docs
    
  - [docs] Added conda
    
  - Improve POSIX API detection
    
  - Move has_formatter into the public fmt namespace. (#1407)
    
    * Move has_formatter into the public fmt namespace.
    
    This will allow users to do SFINAE-friendly checks for
    the formattability of a type.
    
    Fixes #1369
  - Remove broken CI config
    
  - Correct basic_string_view from string ctor
    
  - [clang-tidy] Replace deprecated C headers
    
    Found with modernize-deprecated-headers
    
    Signed-off-by: Rosen Penev <rosenp@gmail.com>
    
  - [clang-tidy] Add missing override
    
    Found with hicpp-use-override
    
    Signed-off-by: Rosen Penev <rosenp@gmail.com>
    
  - [clang-tidy] Replace {} with = default
    
    Found with hicpp-use-equals-default
    
    Signed-off-by: Rosen Penev <rosenp@gmail.com>
    
  - [clang-tidy] Use auto
    
    Found with hicpp-use-auto
    
    Signed-off-by: Rosen Penev <rosenp@gmail.com>
    
  - [clang-tidy] Add noexcept where move is used
    
    Found with performance-noexcept-move-constructor
    
    Signed-off-by: Rosen Penev <rosenp@gmail.com>
    
  - [clang-tidy] Add parentheses to macro arguments
    
    Found with bugprone-macro-parentheses
    
    Signed-off-by: Rosen Penev <rosenp@gmail.com>
    
  - [clang-tidy] Use braced init list
    
    Found with modernize-return-braced-init-list
    
    Signed-off-by: Rosen Penev <rosenp@gmail.com>
    
  - [clang-tidy] Changes suffixes to uppercase
    
    Found with hicpp-uppercase-literal-suffix
    
    Signed-off-by: Rosen Penev <rosenp@gmail.com>
    
  - [clang-tidy] Turn deleted function to public
    
    Found with modernize-use-equals-delete
    
    Signed-off-by: Rosen Penev <rosenp@gmail.com>
    
  - Mark apidoc as rst
    
  - Merge branch 'master' of github.com:fmtlib/fmt
    
  - Update docs
    
  - Document members
    
  - Try fix CI
    
  - Use grouping() from locale for specifier 'n'
    
  - basic_parse_context -> basic_format_parse_context per standard and document
    
  - Fix UTF-8 truncation
    
  - Remove redundant ctor
    
  - Workaround X11 madness (#1388)
    
  - Add double support to compile
    
  - Always inline grisu_gen_digits and disable grisu2 by default
    
  - Apply get_cached_power optimization by jk-jeon
    
  - Simplify format_handler
    
  - Make unsigned-integer-overflow sanitizer happy (#1377)
    
  - Don't emit trailing zeros in exponential notation (#1376)
    
  - Simplify grisu_writer
    
  - Simplify NVCC checks
    
  - clang-format
    
  - Remove obsolete comment and clang-format
    
  - Fix more Visual Studio 2019 pedantic warnings (#1371)
    
    * format-inl.h(444,1): warning C4804: '>>': unsafe use of type 'bool' in operation
    format.h(2808,1): warning C4127: conditional expression is constant
    
    * More fixes for VS2019 pedantic warnings
    
    * Fix "conditional expression is constant" VS2019 warning in more specific way
    
    * Use const_check to silence constexpr warning
  - Patch compiler error when building using nvcc
    
    If you compile using `nvcc` and pass the option `--expt-relaxed-constexpr` it will crash with an internal compiler error. This modification prevents using `constexpr` in `fmtlib` when compiling using `nvcc` and prevents the crash.
    
  - Optimize counting
    
  - Simplify grisu_writer
    
  - Improve handling of signs
    
  - Initialize all the things
    
  - Handle assymetric boundaries
    
  - Fix computing lower boundaries for smallest normalized double
    
  - packed_arg_bitsize -> packed_arg_bits and remove packed_arg_mask
    
  - Implement round half to even
    
  - Support single precision floats in grisu formatting
    
    Fixes #1336
    
  - Fix Visual Studio 2019 pedantic warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
    
  - Apply clang-format
    
  - Reduce bigint capacity
    
  - Handle negative exponent and nonnegative power
    
  - Handle negative exponent and rename value/pow10 to numerator/denominator
    
  - Partially implement (FPP)^2
    
  - Fix a linkage error introduced by #1360 (#1362)
    
  - Implement add_compare
    
  - Rename write_double to write_fp
    
    It handles all floating point types, not just doubles.
    
  - Distinguish float from double
    
  - Use words for packed constants
    
  - Encode types using 5 bits
    
    This is needed to support more than the current 16 types.
    
  - Implement more comparison operators
    
  -  Add defaulted copy and move operations to format_error and system_error  (#1347)
    
    * Avoid weak vtables by providing a private virtual member function
    
    * Add warning Wweak-vtables to clang when FMT_PEDANTIC is on
    
    * Add defaulted copy and move operations to format_error and system_error
    
    Compiler generated copy operations are deprecated and move operations
    are not generated altogether.
    
    * Add warning Wdeprecated to clang when FMT_PEDANTIC is on
    
  - Deduplicate color vformat and vprint
    
    After #1351 they became essentially the same.
    
  - use memory_buffer to make color print behave atomic #1348 (#1351)
    
    
  - Fix compile error in printf with gcc9 (#1354)
    
  - Implement divmod
    
  - Fix undefined in format-test (#1349)
    
    When `MoveCtor` performs `check_move_buffer`, the buffer allocator becomes null,
    but then `MoveCtor` attempts to use it to allocate a dynamic buffer. This
    succeeds nevertheless because a typical `std::allocator<char>::allocate` does
    not use `this`, so it does not crash when `this` is null.
    
    Fixes #1344
  - Fix undefined in core-test and printf-test (#1345)
    
    * Fix undefined in core-test
    
    Fixes "reference binding to null pointer" in BufferTest.Ctor
    
    buffer.operator[] attempts to return a reference to `buffer.ptr_[0]` when `ptr_`
    in `mock_buffer<int> buffer` is null.
    
    * Fix undefined in printf-test
    
    Fixes "signed integer overflow" in PrintfTest.Length
    
    This occurs in `TestLength<long long>("ll")`, since its minimum value minus one
    does not fit in long long.
    
    * Fix undefined in printf %0$
    
    Printf counts arguments from 1.
    
    Fixes "shift exponent -4 is negative" in PrintfTest.InvalidArgIndex.
    
    `do_get` is called with index -1 when `basic_printf_context.arg` is called with
    id 4294967295 when basic_printf_context::get_arg subtracts 1 from arg_index 0 in
    the format string "%0$d".
    
  - Implement more bigint operations
    
  - Initial implementation of square
    
  - Fix handling of types convertible to std::string_view
    
  - Repoint one more Python 2 link to Python 3
    
    One more python reference, this one acknowledging the `str.format` function.
  - let README point to python 3 instead of 2
  - Fix ambiguity for types with dodgy conversions
    
  - Provide overload for `fmt::join` that handles `std::tuple`s
    
    Address enhancement request #1322.
    
    The overload is provided in `ranges` (original `fmt::join` exists
    currently in `format.h` for historical reasons.
    
    Tests for prvalue and lvalue tuple arguments as well as the empty
    tuple are provided in `ranges-test.cc`.
    
  - Update README.rst
  - Making CUDA test work with CMAKE_MSVC_RUNTIME_LIBRARY
    
    CMake 3.15 introduced a new way of handling MSVC CRT type definition for
    the build: CMAKE_MSVC_RUNTIME_LIBRARY variable.
    (https://cmake.org/cmake/help/latest/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html)
    
    This is supposed to be the way to go with MSVC CRT selection in new
    projects. Using this method however breaks the current CMake script for
    CUDA test. The reason is the CUDA test uses "FindCUDA" CMake module to
    detect and set up CUDA support in CMake, which is deprecated since CMake
    version 3.10, and which does not support CMAKE_MSVC_RUNTIME_LIBRARY
    selector correctly (i.e. it does not propagate the compiler option
    related to the CRT).
    
    I did not find a way to "patch" in the correct compiler options, so
    (while knowing this feature is only available from CMake 3.15 on) I
    decided to change also the way CUDA is handled and instead of using
    FindCUDA, used enable_language. Apart from having some nice additional
    side-effects, it also fixed the problem with CRT selection.
    
    However, the propagation of the compiler options (and in particular the
    options related to C++ standard selection) is still a bit flaky on
    Windows+MSVC platform, so it had to be done manually.
    
    The patch makes two things in parallel:
    
    1) Introduces MSVC_BUILD_STATIC, which, together with CMake version >=
    3.15, allows building static version of the 'fmt' lib (and all the
    tests).
    
    2) At the same time, for CMake >= 3.15 it switches handling of CUDA
    support from (old) FindCUDA to (new) enable_language, to fix the
    problems which the old method has with the new CRT selector for MSVC in
    a new CMake.
    
    Added a check for CUDA before enabling it.
    
    Using VERSION_LESS instead of VERSION_GREATER_EQUAL
    
    Since apparently VERSION_GREATER_EQUAL exists only from CMake 3.7, while
    Android is using CMake 3.6.
    
    Removed MSVC_RUNTIME_LIBRARY logic from the CMake file.
    
    The static build can be set on the command line with CMake >= 3.15
    by defining the policy and the CMAKE_MSVC_RUNTIME_LIBARY this way:
    
    cmake -G <gen> <options>
        -DCMAKE_POLICY_DEFAULT_CMP0091=NEW
        -DMSVC_BUILD_STATIC=ON
        -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded$<$<CONFIG:Debug>:Debug>"
    
    When MSVC_BUILD_DEBUG is set the test 'posix-mock-test' is skipped as it
    does not build with the static runtime.
    
  - workaround VS2019 Update 3 compiler bug. (#1328)
    
    
    
  - add test for multiple compilation types
    
  - fix name clash in header-only mode
    
  - fix `get`
    
  - Disable integral operator<< (#1316)
    
  - Remove redundant and nonportable test (#1313)
    
  - Don't use const char* overload of operator<< (#1309)
    
  - Fix a warning (#1319) and simplify code
    
  - Fix shared build on Solaris
    
  - add oss fuzz badge
    
  - fmt.pc.in: Fix for cross compilation
    
    These variables get set to /usr/lib and /usr/include , which is totally wrong in a cross compilation
    environment.
    
    Changed to standard pkgconfig values consistent with most other ones.
    
  - Update ChangeLog.rst
  - Fix fallback_format (#1306)
    
  - Fix format overload that takes text_style (#1305)
    
  - Add max_value
    
  - Implement multiplication and part of assignment from pow of 10
    
  - Implement left shift
    
  - Refactor normalize and clean up
    
  - value -> bigit
    
  - Add a bigint stub and reenable grisu
    
  - Tweak comment
    
  - Integrate new format string compilation
    
  - Update index.rst
  - Update README.rst
  - Update README.rst
  - Fixed vs 2015 warning about unused variable when grisu is off
    
  - Make numeric alignment optional
    
  - Format octal 0 as 0
    
  - Add ccache to the list of projects
  - Reduce the numer of ifdefs with an empty (u)int128_t fallback
    
  - Add support for built-in __int128 when available
    
  - Move definition of FMT_USE_INT128 to core.h
    
  - Rename internal::is_integral and internal::is_arithmetic
    
    To reserve space for the type traits sharing the same name as the ones
    from standard library.
    
  - Initial implementation of optimal compile-time formatter generation
    
  - Clarify use of the core API in header-only mode (#1296)
    
  - Simplify format string compilation
    
  - Remove unused code and refactor
    
  - Make compile work with user-defined types
    
  - Remove string_view_metadata
    
    string_view_metadata was introduced to make compiled format relocatable.
    However, format string compilation is an optimization and therefore
    adding overhead and extra complexity for relocation is undesirable.
    In most cases the string will be either static or outlive compilation
    and formatting and if it doesn't, it's possible to make compiled
    representation relocatale by other means.
    
  - Refactor format string compilation
    
  - Simplify format string compilation
    
  - Add -Werror to tests
    
  - Fix compile-time checks for user-defined types (#1292)
    
  - Document floating-point n specifier (#1291)
    
  - Fix warnings (#1288)
    
  - FixedEnum -> StrongEnum and make it a regression test
    
  - Fix minor clang-tidy warnings
    
    using instead of typedef.
    
    climits instead of limits.h
    
    Added missing cast to size_t.
    
  - Map not int enum to correct underlying_type (#1286)
    
    * Map not int enum to correct underlying_type
    
    * Use non-zero constant in TestFixedEnum
    
  - Add a CUDA test
    
    test cuda: import fmt in CUDA source code
    
    Current test is only for Windows(cl.exe).
    Need to test more with the other host compilers...
    
    * Activate the test when `find_package(CUDA)` worked
    * The test runs with C++14
    
    Detailed comments in 'test/cuda-test'
    
    test cuda: add more comment / macro check
    
    * checks both `__NVCC__` and `__CUDACC__`
    
    More comments for CMake and CUDA source file.
    
    test cuda: <fmt/core.h> checks NVCC and CUDA
    
    The header file checks 2 things.
    
    * __NVCC__: if the compiler is from NVIDIA
    * __CUDACC__: if the source code is CUDA(.cu) file
    
    Since we can't sure all users prefer latest, Version for
    `find_pacakge(CUDA)` is downgraded to 9.0.
    This is the minimum version for C++14 in CUDA
    
  - Rename precision parameter
    
    To avoid clang warning:
    
    fmtlib/include/fmt/chrono.h:753:32: error: declaration shadows a field of 'formatter<duration<type-parameter-0-0, type-parameter-0-1>, type-parameter-0-2, void>' [-Werror,-Wshadow]
  - Make buffer_range public and update custom formatting docs (#1281)
    
  - Workaround broken [[deprecated]] in Intel compiler (#1273)
    
  - Eliminate shadow variable warning
    
    gcc-9 gives the following shadow warning:
    ```
    In file included from /Users/libraries/ioss/src/fmt/ostream.h:12,
                     from /Users/libraries/ioss/src/Ioss_DatabaseIO.C:59:
    /Users/libraries/ioss/src/fmt/format.h: In function 'void fmt::v6::internal::parse_format_string(fmt::v6::basic_string_view<Char>, Handler&&)':
    /Users/libraries/ioss/src/fmt/format.h:2442:10: warning: declaration of 'struct fmt::v6::internal::parse_format_string(fmt::v6::basic_string_view<Char>, Handler&&)::writer' shadows a global declaration [-Wshadow]
     2442 |   struct writer {
          |          ^~~~~~
    /Users/libraries/ioss/src/fmt/format.h:1703:7: note: shadowed declaration is here
     1703 | using writer = basic_writer<buffer_range<char>>;
          |       ^~~~~~
    ```
    
    Since the `writer` struct is only used internally in the `parse_format_string` function, its name can be changed somewhat aribtrarily to avoid conflicts with names in an outer scope.
    
    Note that this warning is also present in the 6.0.0 release.
  - Fix typos.