Update git submodules
* Update bionic from branch 'master'
  to 436af3d55b26d1204812b4e45fea7bd9feb983e7
  - Merge changes from topic "clang-r365631-switch-over"
    
    * changes:
      Fix segment gap test
      stdatomic_test: always use bits/stdatomic.h
      Adapt tests due to the new Clang fortify-source warning
    
  - Fix segment gap test
    
    The test starts failing in the upcoming lld update. The root cause is
    that no relro section is specified by the linker script, and the orphan
    placement algorithm decides to place them after .text which is a
    misaligned place.
    
    Test: bionic-unit-tests
    Bug: 139089152
    Bug: 131328001
    Change-Id: I2140d8a9fd7c712f1d31a541a3b4a10788385e98
    
  - stdatomic_test: always use bits/stdatomic.h
    
    Host includes are updated now, so we always must include
    bits/stdatomic.h
    
    Bug: 137876753
    Bug: 138701943
    Test: not yet
    Change-Id: Ib2ce34ae5dace8f9a114fa8c04f864cd7f41a5d9
    
  - Adapt tests due to the new Clang fortify-source warning
    
    https://reviews.llvm.org/D58797 added several new compile time
    _FORTIFY_SOURCE diagnostics. This broke clang_fortify_tests:
    
    FAILED: out/target/product/walleye/obj/STATIC_LIBRARIES/bionic-compile-time-tests2-clang++_intermediates/clang_fortify_tests.o
    error: 'warning' diagnostics seen but not expected:
      Line 159: 'memcpy' will always overflow; destination buffer has size 8, but size argument is 9
      Line 161: 'memmove' will always overflow; destination buffer has size 8, but size argument is 9
      Line 165: 'memset' will always overflow; destination buffer has size 8, but size argument is 9
      Line 183: 'strncpy' size argument is too large; destination buffer has size 8, but size argument is 9
      Line 185: 'stpncpy' size argument is too large; destination buffer has size 8, but size argument is 9
      Line 189: 'strncat' size argument is too large; destination buffer has size 8, but size argument is 9
      Line 227: 'strncpy' size argument is too large; destination buffer has size 4, but size argument is 5
      Line 232: 'stpncpy' size argument is too large; destination buffer has size 4, but size argument is 5
      Line 242: 'strncat' size argument is too large; destination buffer has size 4, but size argument is 5
      Line 490: 'snprintf' size argument is too large; destination buffer has size 8, but size argument is 9
      Line 495: 'vsnprintf' size argument is too large; destination buffer has size 8, but size argument is 9
    error: 'note' diagnostics seen but not expected:
      File bionic/libc/include/bits/fortify/fcntl.h Line 50: 'open' has been explicitly marked unavailable here
      File bionic/libc/include/bits/fortify/fcntl.h Line 102: 'open64' has been explicitly marked unavailable here
      File bionic/libc/include/bits/fortify/fcntl.h Line 75: 'openat' has been explicitly marked unavailable here
      File bionic/libc/include/bits/fortify/fcntl.h Line 121: 'openat64' has been explicitly marked unavailable here
      File bionic/libc/include/bits/fortify/stdio.h Line 68: 'sprintf' has been explicitly marked unavailable here
    16 errors generated.
    
    Bug: 131328001
    Bug: 138701853
    Test: Build with r365631 toolchain
    Change-Id: I103ecb7b3abcf4b5cfc4f36ccab69e03d0976275
    

* Update build/soong from branch 'master'
  to bdefa541d9f7efd7635581f9e855859d27a165a7
  - Merge "Switch to clang-r365631"
  - Switch to clang-r365631
    
    Test: build, boot, bionic-unit-test
    Test: For Googlers, go/clang-r365631-testing
    Bug: 131328001
    Change-Id: Ib357d9044a72e41f6bde1e5ec2db34e90706124d