Update git submodules
* Update external/lldb from branch 'lldb-master-dev'
  to af24a972855d770af28179c1499a6d3f806d1269
  - [lldb] Fix initialization order warnings.
    am: 88109e8482
    
    Change-Id: I7ee4f8ba28046a07b69c3fa291596d8f75d63630
    
  - [lldb] Fix initialization order warnings.
    
    Moved the declaration of m_kind below the declaration of cvclass,
    cvunion and cvenum. This order is necessary because in one of the
    constructors the initialization of m_kind depends on the value of
    cvclass.
    
    third_party/llvm/llvm/tools/lldb/source/Plugins/SymbolFile/NativePDB/PdbUtil.cpp:50:7: error: field 'cvclass' will be initialized after field 'm_kind' [-Werror,-Wreorder]
        : cvclass(std::move(c)),
          ^
    third_party/llvm/llvm/tools/lldb/source/Plugins/SymbolFile/NativePDB/PdbUtil.cpp:51:14: error: field 'cvclass' is uninitialized when used here [-Werror,-Wuninitialized]
          m_kind(cvclass.Kind == TypeRecordKind::Struct ? Struct : Class) {}
    
    git-svn-id: https://llvm.org/svn/llvm-project/lldb/trunk@346435 91177308-0d34-0410-b5e6-96231b3b80d8