Update git submodules
* Update external/llvm from branch 'lldb-master-dev'
  to e20f02ff4823252cb9c12494b1a7137ee89121e6
  - Merge "[nios2] Add missing Nios2CodeGen -> Nios2AsmPrinter linkage am: 82ed232183" into lldb-master-dev
  - [nios2] Add missing Nios2CodeGen -> Nios2AsmPrinter linkage
    am: 82ed232183
    
    Change-Id: I25d1bd2ea2940b8e2439ad49c831a8fd7def9d48
    
  - [nios2] Add missing Nios2CodeGen -> Nios2AsmPrinter linkage
    
    Add missing linkage from Nios2CodeGen library to Nios2AsmPrinter
    library.  The missing dependency causes shared-lib build to fail with
    the following reason:
    
      lib/Target/Nios2/CMakeFiles/LLVMNios2CodeGen.dir/Nios2AsmPrinter.cpp.o: In function `(anonymous namespace)::Nios2AsmPrinter::PrintAsmMemoryOperand(llvm::MachineInstr const*, unsigned int, unsigned int, char const*, llvm::raw_ostream&)':
      Nios2AsmPrinter.cpp:(.text._ZN12_GLOBAL__N_115Nios2AsmPrinter21PrintAsmMemoryOperandEPKN4llvm12MachineInstrEjjPKcRNS1_11raw_ostreamE+0x2b): undefined reference to `llvm::Nios2InstPrinter::getRegisterName(unsigned int)'
      lib/Target/Nios2/CMakeFiles/LLVMNios2CodeGen.dir/Nios2AsmPrinter.cpp.o: In function `(anonymous namespace)::Nios2AsmPrinter::PrintAsmOperand(llvm::MachineInstr const*, unsigned int, unsigned int, char const*, llvm::raw_ostream&)':
      Nios2AsmPrinter.cpp:(.text._ZN12_GLOBAL__N_115Nios2AsmPrinter15PrintAsmOperandEPKN4llvm12MachineInstrEjjPKcRNS1_11raw_ostreamE+0x97): undefined reference to `llvm::Nios2InstPrinter::getRegisterName(unsigned int)'
      collect2: error: ld returned 1 exit status
    
    Differential Revision: https://reviews.llvm.org/D47810
    
    git-svn-id: https://llvm.org/svn/llvm-project/llvm/trunk@347387 91177308-0d34-0410-b5e6-96231b3b80d8