Update git submodules
* Update external/protobuf from branch 'master'
  to 8f8e27deef8af8be3defe00feb5aeb02c7589b6d
  - Merge "Add recovery_available: true to libprotobuf-cpp-lite"
  - Add recovery_available: true to libprotobuf-cpp-lite
    
    Init needs this in order to be built in Android.bp
    
    Test: build
    Change-Id: Idc3bfe634e7f6cd7b1290833d6b93f3e446f574d
    
  - Merge "Protobuf: Suppress MissingOverride"
  - Protobuf: Suppress MissingOverride
    
    Bug: 73499927
    Test: m javac-check RUN_ERROR_PRONE=true
    Change-Id: I3947bf481b25a9ec5ecec5f3ad70200e1c130470
    
  - Merge "Add all the internal protos to the java protobuf lib"
  - Add all the internal protos to the java protobuf lib
    
    Mirror the python protobuf lib and add all the internal
    protos to the java lib in order to be able to use
    import google/protobuf/Any and such in proto definitions.
    
    Test: make host-libprotobuf-java-full
    Bug: 79990695
    Change-Id: I3383f42b1de5cd31986cd79b6c4a82fb69fba122
    
  - Merge "Add SIX to Python-Protobuf dependencies"
  - Add SIX to Python-Protobuf dependencies
    
    Test: m -j perf_proto_stack
    Bug: b/79751992
    Change-Id: If6b85d5378334f61648e3c85372c2143d1f683ca
    
  - Merge "protobuf: Update path to android.jar."
  - protobuf: Update path to android.jar.
    
    It's being moved to a new location, so update the path.
    
    Test: No
    Bug: 77525052
    Change-Id: I990f3bedb43e7c7dbd18bf67fa5daf058be20055
    
  - Merge "Create common protobuf libs for Python"
  - Create common protobuf libs for Python
    
    Bug: b/70568913
    Test: manually create examples.
    Change-Id: I63e94d6066ea4a09206b497f6181799b6e478fdc
    
  - Merge "Don't force libcore_private.stubs to be built with java 1.7"
  - Don't force libcore_private.stubs to be built with java 1.7
    
    We no longer need to build libcore_private.stubs with java 1.7, because
    the library is only built for target and not for host, where it
    conflicts with the module jdk.unsupported.
    
    Bug: 74211600
    Test: m -j libprotobuf-java-lite is successful. both host and target
    variant of the lib is generated.
    Test: EXPERIMENTAL_USE_OPENJDK9=true m -j libprotobuf-java-lite is also
    successful.
    
    Change-Id: I61a49d537ee6abad29e5661944ffc612a94465b8
    
  - Merge "libcore_private.stubs is uninstallable"
  - libcore_private.stubs is uninstallable
    
    Make sure that libcore_private.stubs isn't installed to the device as a
    standalone jar library. The lib is meant to provide build-time only
    symbol information to protobuf and thus is not runnable.
    
    Bug: 73204840
    Test: m -j libcore_private.stubs does not create
    libcore_private.stubs.jar in /system/framework
    
    Change-Id: I7c661211161937dba5ee71fdc4bb8b9f101c5a59
    
  - Merge "libcore_private.stubs cannot be built with JDK9"
  - libcore_private.stubs cannot be built with JDK9
    
    The package sun.misc in the stubs library is causing module name
    conflict when building with JDK9.
    
    error: package exists in another module: jdk.unsupported
    
    Fixing the error by setting java_version to 1.7 so that modules are not
    used when building the stubs lib.
    
    Bug: 74211600
    Test: EXPERIMENTAL_USE_OPENJDK9=true m -j libcore_private.stubs
    
    Change-Id: Ifa709bef2dc8e2b11048ef96fc7517d8c25e8a7f
    
  - Merge "Build libprotobuf-java-lite only using core Java SDK APIs"
  - Build libprotobuf-java-lite only using core Java SDK APIs
    
    libprotobuf-java-lite is now built against core Java APIs which excludes
    Android-only APIs (classes under android.* packages) and private APIs.
    "core_current" is a pseudo SDK which is a core Java subset of Android
    SDK.
    
    However, this lib has been using sun.misc.Unsafe which is a hidden API
    and dependency to the class doesn't seem to be able to be cut easily in
    the near future. In order to make it possible to build the lib with the
    SDK only, a stubs library called libcore_private.stubs is defined to
    provide build-time only information on the hidden APIs exclusively to
    protobuf.
    
    At runtime, the Unsafe class is provide by the OS and protobuf is linked
    to the class loaded there.
    
    Bug: 73204840
    Test: m -j libprotobuf-java-lite is successful and does not show any
    link-type check warning
    
    Change-Id: I2fce2662cc65d4e57fc75bbf30ebf9f7d47c6775
    
  - Merge "Add zlib support to protobuf"
  - Add zlib support to protobuf
    
    We're already including the source files for zlib support, and linking
    against libz, but we haven't been turning it on.
    
    Test: cd external/protobuf; mma
    Change-Id: Ia4d0ef9f7053b163afda7efaa7c22c3ffa32d4f7