Update git submodules
* Update art from branch 'master'
  to 1e88f980a85056165312331746862dc48186bc54
  - Use apex_available property
    
    Use apex_available property to prevent modules that are only for the ART
    apex from being used outside of the APEX.
    
    This change also fixes the reference to
    $(TARGET_OUT_SHARED_LIBRARIES)/$(lib).so to $(lib).com.android.art.debug
    phony module since the former is never installed to the system partition
    due to their 'apex_available' settings.
    
    Bug: 128708192
    Bug: 133140750
    Test: m
    Change-Id: I990e0a67e066d9b1dc221748422a2f44449258da
    

* Update build/make from branch 'master'
  to e09efa6473f8f2f6ae764360fd7f3c11bd673f55
  - Merge changes from topic "art_apex_available"
    
    * changes:
      Find the jar libraries in APEX from the correct path
      Use apex_available property
    
  - Find the jar libraries in APEX from the correct path
    
    JAR libraries in the ART and conscrypt APEXes are no longer built for
    the platform. Therefore, the path out/target/common/<name>_intermediates
    does not exist. Instead use the path
    out/target/common/<libname>.<apexname>_intermediates paths for those
    APEX-only jars.
    
    Bug: 128708192
    Bug: 133140750
    Test: m
    
    Change-Id: I5fb725403ac22198e5ce6d77ca97c5f3392fabfd
    
  - Use apex_available property
    
    Use apex_available property to prevent modules that are only for the ART
    apex from being used outside of the APEX.
    
    Bug: 128708192
    Bug: 133140750
    Bug: 129006418
    Test: m
    Test: m libnativeloader doesn't install anything. (because it doesn't
    have "//apex_available:platform".
    Test: Add "libnativeloader" to shared_libs of "libvndksupport" which is
    installed to /system/lib. Then the build fails with following error:
    
      error: system/core/libvndksupport/Android.bp:3:1: module
      "libvndksupport" variant "android_arm_armv8-a_core_shared": depends on
      //art/libnativeloader:libnativeloader which is not visible to this
      module
    
    Change-Id: I964d0125cfedb454a60c098bf1a1797201d5dd40
    

* Update build/soong from branch 'master'
  to ead014b8f9f344caa2ae1e0a337d5dba48645125
  - Merge "Revert "Avoid duplicated classes for boot dex jars""
  - Revert "Avoid duplicated classes for boot dex jars"
    
    This reverts commit 2812df4edb6c22c6d5de2156942b1898db9c2317.
    
    This is no longer required as we have
    I6463ebc59cf7fd861b812999d7a79c387bbb3335.
    
    hostdex files are available even when the module doesn't have
    "//apex_available:platform"
    
    Bug: 128708192
    Test: m
    Change-Id: I0d1295683222bc9cdbb82630e61ab3421c717daf
    

* Update device/google/fuchsia from branch 'master'
  to 19b02461a94f8f381c5bf294568d49275d4cb1bb
  - Rename modules that are APEX-only
    
    The renamed modules are only available for APEXes, but not for the
    platform. Use the <module_name>.<apex_name> syntax to correctly install
    the APEX variant of the modules.
    
    Bug: 128708192
    Bug: 133140750
    Test: m
    Change-Id: I322b1efccb681ef22f95e2a1de90b7607aad9d30
    

* Update external/apache-xml from branch 'master'
  to 16015ab09e0ec27a16edec4ee7b021e03cf0fdb9
  - Merge "Use apex_available property"
  - Use apex_available property
    
    Use apex_available property to prevent modules that are only for the ART
    apex from being used outside of the APEX.
    
    Bug: 128708192
    Bug: 133140750
    Test: m
    Change-Id: Ic91bcbb9aa85c7e74afd31876a2f7664be68e62b
    

* Update external/bouncycastle from branch 'master'
  to 1dd3e7b5c199b77cc7b2b3785f9e936c9abbfcac
  - Merge "Use apex_available property"
  - Use apex_available property
    
    Use apex_available property to prevent modules that are only for the ART
    apex from being used outside of the APEX.
    
    Bug: 128708192
    Bug: 133140750
    Test: m
    Change-Id: Ia6c324eed0bc4f63a1576df9540066607be2bfc0
    

* Update external/chromium-libpac from branch 'master'
  to 3af26c4d340348db59de979615db205a02fbd658
  - Merge "Use apex_available property"
  - Use apex_available property
    
    Use apex_available property to prevent modules that are only for the ART
    apex from being used outside of the APEX.
    
    Bug: 128708192
    Bug: 133140750
    Test: m
    Change-Id: Ie999602c6840481c89b13848ccee6d3ef9e82834
    

* Update external/icu from branch 'master'
  to e243b2a8ba9174a0550f9d716eb629872d505d48
  - Use apex_available property
    
    Use apex_available property to prevent modules that are only for the ART
    apex from being used outside of the APEX.
    
    Bug: 128708192
    Bug: 133140750
    Test: m
    Change-Id: Iac65331774174070513c7e97aed42e8aefb69cfc
    

* Update external/oj-libjdwp from branch 'master'
  to 26a3ecbc0b334461c70f52a4ba1606259d7745e1
  - Use apex_available property
    
    Use apex_available property to prevent modules that are only for the ART
    apex from being used outside of the APEX.
    
    Bug: 128708192
    Bug: 133140750
    Test: m
    Change-Id: I2a3d73397c1dc03f8e2bf214117abc7d00537ef8
    

* Update libcore from branch 'master'
  to 5ff12cbc24f10517f789feae58992772f2a19e26
  - Merge "Use apex_available property"
  - Use apex_available property
    
    Use apex_available property to prevent modules that are only for the ART
    apex from being used outside of the APEX.
    
    Bug: 128708192
    Bug: 133140750
    Test: m
    Change-Id: I190ce2d10bd1626b420227a726072c5ac4d85d94
    

* Update libnativehelper from branch 'master'
  to daa7cd7bcbef2b363fbba2dac2dd32d8e469df05
  - Merge "Use apex_available property"
  - Use apex_available property
    
    Use apex_available property to prevent modules that are only for the ART
    apex from being used outside of the APEX.
    
    Bug: 128708192
    Bug: 133140750
    Test: m
    Change-Id: Ifa2bd0f8fe8d5526e6d9de27477177e36485f469