Update git submodules
* Update tools/tradefederation/core from branch 'master'
  to f353f125dbdf2948d41777593831cb7b58be3a3e
  - Merge "ATest: Show debug message when encountering TradeFedExitError."
  - ATest: Show debug message when encountering TradeFedExitError.
    
    Capture and output normal tradefed output for situations where Tradefed did not exit properly.
    Previously this was only an Atest python stacktrace that does not provide useful information to the user.
    
    Bug: 120461133
    
    Test: source build/envsetup.sh ; lunch
          adb disconnect
          atest hello_world_test
          Show message below
           D/CommandScheduler: No available device matching all the config's requirements for cmd id 1.
           The command [template/local_min, --template:map, test=atest, --include-filter, hello_world_test, --subprocess-report-port, 38493, --log-level, WARN] will be rescheduled.
            com.android.tradefed.device.NoDeviceException: No device was allocated for the command.
    	 at com.android.tradefed.command.CommandRunner.run(CommandRunner.java:94)
      	 at com.android.tradefed.command.CommandRunner.main(CommandRunner.java:120)
    
    Change-Id: Idca9ffa43ce9ec3dc9b5b98adccd61b6f2e0aca6