Update git submodules
* Update external/clang from branch 'lldb-master-dev'
  to a57e4c871da7dd56b466fed418df312e238aa2f9
  - Merge "[Frontend/Modules] Show diagnostics on prebuilt module configuration mismatch too am: 3d002375f1" into lldb-master-dev
  - [Frontend/Modules] Show diagnostics on prebuilt module configuration mismatch too
    am: 3d002375f1
    
    Change-Id: I4e5152525770452ca8e2390ed2c7d2c16aaf6cfc
    
  - [Frontend/Modules] Show diagnostics on prebuilt module configuration mismatch too
    
    The current version only emits  the below error for a module (attempted to be loaded) from the `prebuilt-module-path`:
    
    ```
    error: module file blabla.pcm cannot be loaded due to a configuration mismatch with the current compilation [-Wmodule-file-config-mismatch]
    ```
    
    With this change, if the prebuilt module is used, we allow the proper diagnostic behind the configuration mismatch to be shown.
    
    ```
    error: POSIX thread support was disabled in PCH file but is currently enabled
    error: module file blabla.pcm cannot be loaded due to a configuration mismatch with the current compilation [-Wmodule-file-config-mismatch]
    ```
    
    (A few lines later an error is emitted anyways, so there is no reason not to complain for configuration mismatches if a config mismatch is found and kills the build.)
    
    Reviewed By: dblaikie
    
    Tags: #clang
    
    Differential Revision: https://reviews.llvm.org/D53334
    
    git-svn-id: https://llvm.org/svn/llvm-project/cfe/trunk@346439 91177308-0d34-0410-b5e6-96231b3b80d8