Update git submodules
* Update system/tools/hidl from branch 'master'
  to 604fe01ac3d8d8a330f9674607219e0e7d9b8402
  - hidl: cpp: Use the root namespace for type tags
    
    Fixes a collision if a vendor uses a namespace that contain android:
    
    out/soong/.intermediates/vendor/corp/interfaces/interface/1.0/com.corp.android.something@1.0_genc++_headers/
    gen/com/corp/android/something/1.0/ISomething.h:24:13: error: no member named 'hardware' in namespace 'com:
    :corp::android'; did you mean '::android::hardware'?
        typedef android::hardware::details::i_tag _hidl_tag;
                ^~~~~~~~~~~~~~~~~
                ::android::hardware
    
    Also adds an an interface to hidl.tests.vendor.android which is
    generated in cpp_impl_test, providing a regression test for this
    behavior.
    
    Change-Id: Ia6a778127678771e47ac65cec019f8fc1c69e7d0