Update git submodules
* Update external/clang from branch 'lldb-master-dev'
  to f588192888ecc155dde4a4fa94e119b60402c52a
  - Merge "Temporarily revert r337226 "Restructure checking for, and warning on, lifetime extension." am: 28deda3b58" into lldb-master-dev
  - Temporarily revert r337226 "Restructure checking for, and warning on, lifetime extension."
    am: 28deda3b58
    
    Change-Id: I084d66b9c4aeba40c025fee97b3548d7cb2c8c3e
    
  - Temporarily revert r337226 "Restructure checking for, and warning on, lifetime extension."
    
    This change breaks on ARM because pointers to clang::InitializedEntity are only
    4 byte aligned and do not have 3 bits to store values. A possible solution
    would be to change the fields in clang::InitializedEntity to enforce a bigger
    alignment requirement.
    
    The error message is
    
    llvm/include/llvm/ADT/PointerIntPair.h:132:3: error: static_assert failed "PointerIntPair with integer size too large for pointer"
      static_assert(IntBits <= PtrTraits::NumLowBitsAvailable,
    include/llvm/ADT/PointerIntPair.h:73:13: note: in instantiation of template class 'llvm::PointerIntPairInfo<const clang::InitializedEntity *, 3, llvm::PointerLikeTypeTraits<const clang::InitializedEntity *> >' requested here
        Value = Info::updateInt(Info::updatePointer(0, PtrVal),
    llvm/include/llvm/ADT/PointerIntPair.h:51:5: note: in instantiation of member function 'llvm::PointerIntPair<const clang::InitializedEntity *, 3, (anonymous namespace)::LifetimeKind, llvm::PointerLikeTypeTraits<const clang::InitializedEntity *>, llvm::PointerIntPairInfo<const clang::InitializedEntity *, 3, llvm::PointerLikeTypeTraits<const clang::InitializedEntity *> > >::setPointerAndInt' requested here
        setPointerAndInt(PtrVal, IntVal);
        ^
    llvm/tools/clang/lib/Sema/SemaInit.cpp:6237:12: note: in instantiation of member function 'llvm::PointerIntPair<const clang::InitializedEntity *, 3, (anonymous namespace)::LifetimeKind, llvm::PointerLikeTypeTraits<const clang::InitializedEntity *>, llvm::PointerIntPairInfo<const clang::InitializedEntity *, 3, llvm::PointerLikeTypeTraits<const clang::InitializedEntity *> > >::PointerIntPair' requested here
        return {Entity, LK_Extended};
    
    Full log here:
    http://lab.llvm.org:8011/builders/clang-cmake-armv7-global-isel/builds/1330
    http://lab.llvm.org:8011/builders/clang-cmake-armv7-full/builds/1394
    
    
    
    
    git-svn-id: https://llvm.org/svn/llvm-project/cfe/trunk@337255 91177308-0d34-0410-b5e6-96231b3b80d8