Update git submodules
* Update external/clang from branch 'lldb-master-dev'
  to 0982778bcf53e90efb91bad36b470e5a462b7aca
  - Merge "Removed unused variable [NFC] am: 5e499dd14c" into lldb-master-dev
  - Removed unused variable [NFC]
    am: 5e499dd14c
    
    Change-Id: I2fa43a51882dd5362c3f8554d1630e1b5f00edcc
    
  - Removed unused variable [NFC]
    
    The compiler warned:
    ../tools/clang/lib/Sema/SemaType.cpp:6788:31: error: unused variable 'AT' [-Werror,-Wunused-variable]
        if (const AttributedType *AT = S.getCallingConvAttributedType(type)) {
                                  ^
    1 error generated.
    
    git-svn-id: https://llvm.org/svn/llvm-project/cfe/trunk@340251 91177308-0d34-0410-b5e6-96231b3b80d8