Update git submodules
* Update external/ltp from branch 'master'
  to 2add73c6856407c88a6b830516c31222bcae51ef
  - UPSTREAM: cpuset: Work around a clang compiler warning
    
    The clang compiler will warn about pasting a C string literal and an
    int, suggesting that array indexing should be used instead:
    
    testcases/kernel/controllers/cpuset/cpuset_lib/cpuinfo.c:143:3: error:
     adding 'int' to a string does not append to the string
     [-Werror,-Wstring-plus-int]
      while_each_childdir(SYS_CPU_DIR, "/", c_relpath,
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    testcases/kernel/controllers/cpuset/cpuset_lib/common.h:54:13: note:
     expanded from macro 'while_each_childdir'
      p_relpath + start); \
      ~~~~~~~~~~^~~~~~~
    testcases/kernel/controllers/cpuset/cpuset_lib/cpuinfo.c:143:3: note:
     use array indexing to silence this warning
    
    This seems like a strange warning, but the suggestion has no effect on
    code generation or readability, so change it to keep clang happy.
    
    Signed-off-by: Alistair Strachan <astrachan@google.com>
    Acked-by: Cyril Hrubis <chrubis@suse.cz>
    (cherry picked from commit 6c89d0ed30a7eb95399bbd8579c8227e1dcc7959)
    Bug: 37950676
    Test: mmm external/ltp
    Change-Id: I316b26e6e058b1ea4292da2614fd1a74fdd37c33
    Signed-off-by: Alistair Strachan <astrachan@google.com>
    
  - UPSTREAM: cpuset_lib: Replace index() with strchr()
    
    The index() function was removed in POSIX.2008. It is not implemented by
    Android's bionic C library for 64-bit platforms.
    
    Use the more portable strchr() function from C89.
    
    Signed-off-by: Alistair Strachan <astrachan@google.com>
    Signed-off-by: Petr Vorel <pvorel@suse.cz>
    (cherry picked from commit 86c04b02e32689b858ed9988383262cee382a634)
    Bug: 37950676
    Test: mmm external/ltp
    Change-Id: I08477a772133cc33bb7b28c7ccb85dff16ea34cd
    Signed-off-by: Alistair Strachan <astrachan@google.com>