Update git submodules
* Update build/make from branch 'simpleperf-release'
  to 51804002d906d6820d8705606c496eb94dcbba30
  - Merge "Snap for 5806856 from d994b4c062bbf701333c7bb098e7cdd6fbc67aba to simpleperf-release" into simpleperf-release
  - Snap for 5806856 from d994b4c062bbf701333c7bb098e7cdd6fbc67aba to simpleperf-release
    
    Change-Id: Ic3276e7049d5b89b933069508349efccfe8f8ebc
    
  - Merge "Stop packing system/update_engine/scripts."
  - Stop packing system/update_engine/scripts.
    
    We once attempted to use them (by importing from releasetools scripts)
    to parse payload. Due to the dependency on google.protobuf, we have
    switched to delta_generator instead (commit 750385e4).
    
    Bug: 65261072
    Test: `m -j otatools-package`; and check the related scripts are not
          included.
    Change-Id: Iaa8bcb0e2792e48512e1b8db29869db875ba8dc9
    

* Update device/amlogic/yukawa from branch 'simpleperf-release'
  to 1a828d0a212eeca9db5fb1d56c60f75d484cdeca
  - Snap for 5806856 from aae47ba99db44888b2a314e1f3ee9a3c0c6bee3a to simpleperf-release
    
    Change-Id: Ibf875c74a792fa6e4d7f080a97d45c46d83ebf70
    
  - yukawa: update audio_policy_configuration to Android Q compatible
    
    Removed references to non-exist configuration files
    Updated HAL version
    
    b/139419224
    
    test: manually, Android Q boots to home screen on
    Yukawa.
    
    Change-Id: I6f63fd9140c8db661316963a06af5ed5cb5226a4
    

* Update external/autotest from branch 'simpleperf-release'
  to 3582ffc945dfef278e03e0a6ccdefbe3091062ef
  - Snap for 5806856 from f872ba573ba7a6f3238e4bb1010e4f8906c6fbc9 to simpleperf-release
    
    Change-Id: Ibbafb9efe687ef1362bb62b138da7ff2bc4aadbc
    
  - platform_PrinterPpds: New function for digests calculation
    am: b48d04e13c
    
    Change-Id: I43f028f75078adc63ab7bd02d78aabf196eca59d
    
  - autotest: provision: check gs_cache server from DUT
    am: 4a2a664ad1
    
    Change-Id: Ic102ab09ad6c81cfba7ebf3e3576f32c34db2eca
    
  - Adding Post-recovery exception handling.
    am: e661d8c97d
    
    Change-Id: I81788805182ffd17ef1a57038a400cf09d93a7b9
    
  - [Autotest] Accessibility Autotests
    am: 13ef8d7e29
    
    Change-Id: I83aecdc93dc3bbc2aff0b08b364b07126123cb97
    
  - Revert "graphics_Idle: Move test to bvt-perbuild because it is flaky"
    am: 5f4f0c3c74
    
    Change-Id: Iec82f2fca8120bdbb1e176d935122647006901c5
    
  - [moblab] Add in an AU test suite.
    am: 648ab72852
    
    Change-Id: I19f4ae4db4af92f2df44fd3817f730715947d433
    
  - FAFT: Remove RyuSwitcher class
    am: 7db2b125ec
    
    Change-Id: I7d784771cbc56baf9130aed624f3f0b4db6ae649
    
  - [moblab] Extend the connect SSH timout by 1 second.
    am: 69cc5269f3
    
    Change-Id: I1469e06bcc8f9675aab7ab541e874c21bd031574
    
  - network_ShillInitScripts: don't stop recover_duts
    am: a6bafa86ec
    
    Change-Id: I0fe71e9d462668bb4a8452021d30433d7c3cb09c
    
  - bluetooth: Remove suite:bluetooth_quicksanity
    am: 9d3803d106
    
    Change-Id: I86b88f94b8f029aa04811c5c33e0402638fd88be
    
  - tast: Increase timeout of crosbolt tests to 3 hours.
    am: 8ea360bd22
    
    Change-Id: Ic79f1b4059794525daeb2f34184fe05b362d64dd
    
  - servo: add ControlUnavailableError, has_control()
    am: 2cba8e48b7
    
    Change-Id: Id5927186cfe9f2c6680afac236807e8cca74fd6b
    
  - servo: enforce keyboard on after hwinit when reflashing
    am: bd3b74f405
    
    Change-Id: Id0bd4b2f5d5f41d14ea3f82d5eafd48efb8c8a86
    
  - platform_PrinterPpds: New function for digests calculation
    
    The function for digests calculation was rewritten. The algorithm
    for prunning variables from documents headers is much better now
    and can handle different combination of PJL/PS encapsulations.
    Additionally, support for @EJL headers (epson eplaser) was added.
    New implementation is also faster than the previous one.
    This patch contains also new set of PPD files, new files with
    digests and an updated list of blacklisted PPDs.
    
    BUG=chromium:880935
    TEST=tested on nautilus, hana and veyron_minnie
    
    Change-Id: I13d11e276d77d243c0c52f509fda340147668c57
    Reviewed-on: https://chromium-review.googlesource.com/1734132
    Tested-by: Piotr Pawliczek <pawliczek@chromium.org>
    Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
    Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
    Reviewed-by: Sean Kau <skau@chromium.org>
    Reviewed-by: Katherine Threlkeld <kathrelkeld@chromium.org>
    
  - autotest: provision: check gs_cache server from DUT
    
    The shards/drones may not be able to talk to devserver directly, so it's
    not reliable to check if gs_cache server is there by connecting from the
    server. Instead, we can try to connect from DUT.
    
    BUG=None
    TEST=Ran below snips against two devservers (one with gs_cache enabled,
            one without) and ensure both provision were successful.
    
            import common
    
            from autotest_lib.server import hosts
            from autotest_lib.server.cros import autoupdater
    
            h = hosts.create_host('chromeos6-row12-rack13-host21')
    
            url = ('http://<devserver>.cros.corp.google.com:8082/update/'
                'octopus-release/R77-12241.0.0')
            updater = autoupdater.ChromiumOSUpdater(url, host=h,
                                                    use_quick_provision=True)
            updater.run_update()
    
    Change-Id: I79c4545f0eacfa5e2469f3088641cab9e5759d9a
    Reviewed-on: https://chromium-review.googlesource.com/1749616
    Tested-by: Congbin Guo <guocb@chromium.org>
    Commit-Ready: Congbin Guo <guocb@chromium.org>
    Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
    Reviewed-by: Congbin Guo <guocb@chromium.org>
    
  - Adding Post-recovery exception handling.
    
    Test image installation is out of the scope of the test verification
    and these failures should not be a reason to error out.
    
    BUG=chromium:866596
    TEST=None
    
    Change-Id: I44114ac6a2a0acffcc469cb3302858323ef3f35b
    Reviewed-on: https://chromium-review.googlesource.com/1735792
    Tested-by: Sridhar Sonti <sontis@google.com>
    Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
    Commit-Ready: Sridhar Sonti <sontis@google.com>
    Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
    Reviewed-by: Kalin Stoyanov <kalin@chromium.org>
    
  - [Autotest] Accessibility Autotests
    
    This test verifies the effect of the HighContrastEnabled, LargeCursorEnabled,
    VirtualKeyboardEnabled, and ScreenMagnifierType user policy on Chrome OS.
    
    BUG=chromium:945457
    TEST=this
    
    Change-Id: I988a92a81bd1c7a242fefb62240a999e728d4059
    Reviewed-on: https://chromium-review.googlesource.com/1534863
    Tested-by: Derek Beckett <dbeckett@chromium.org>
    Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
    Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
    Reviewed-by: Ruben Zakarian <rzakarian@chromium.org>
    
  - Revert "graphics_Idle: Move test to bvt-perbuild because it is flaky"
    
    This reverts commit 45ee8275d48208e9a62ea90c1ee689c14e71372b.
    
    Reason for revert: There has not been a failure in 2 weeks. This means the test is not flaky.
    
    Original change's description:
    > graphics_Idle: Move test to bvt-perbuild because it is flaky
    >
    > BUG=chromium:988475
    > TEST=none
    >
    > Change-Id: Ibabde6442a8155ace020ca1c2513eb9f3e800ba2
    > Reviewed-on: https://chromium-review.googlesource.com/1724734
    > Tested-by: Jason Clinton <jclinton@chromium.org>
    > Commit-Ready: Jack Neus <jackneus@google.com>
    > Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
    > Reviewed-by: Jack Neus <jackneus@google.com>
    
    Bug: chromium:988475
    Change-Id: I2d4eb49d74b33dd04e5dcb2ec8f6fcc202cacc72
    Reviewed-on: https://chromium-review.googlesource.com/1745522
    Tested-by: Ilja H. Friedel <ihf@chromium.org>
    Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
    Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
    Reviewed-by: Po-Hsien Wang <pwang@chromium.org>
    Reviewed-by: Ilja H. Friedel <ihf@chromium.org>
    
  - [moblab] Add in an AU test suite.
    
    The testing team are going to enable partners to do some AU testing
    this just give them a suite to add the correct tests.
    
    BUG=None
    TEST=Local moblab testing.
    
    Change-Id: I934041f52869dca1b2f4b5d258e171049997f963
    Reviewed-on: https://chromium-review.googlesource.com/1735833
    Tested-by: Keith Haddow <haddowk@chromium.org>
    Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
    Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
    Reviewed-by: Aviv Keshet <akeshet@chromium.org>
    
  - FAFT: Remove RyuSwitcher class
    
    This is part of the on-going effort to deprecate Ryu/Android
    support.  Further CLs to follow.
    
    BUG=b:138222680
    TEST=workstation
    
    Change-Id: I2f1efcb3dfc6c8b919e898381006adc06d5205b2
    Reviewed-on: https://chromium-review.googlesource.com/1745521
    Tested-by: Oleg Loskutoff <olegmikhail@google.com>
    Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
    Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
    Reviewed-by: Wai-Hong Tam <waihong@google.com>
    
  - [moblab] Extend the connect SSH timout by 1 second.
    
    The UI tried to identify the devices that can be added to moblab
    by SSH onto them, the timeout seems to be too short now, extend.
    
    Also updated the unit test
    
    BUG=chromium:990418
    TEST=local moblab testing.
    
    Change-Id: Ie8fa2f15127902fd8531c2715d176b71f65fedbe
    Reviewed-on: https://chromium-review.googlesource.com/1733691
    Tested-by: Keith Haddow <haddowk@chromium.org>
    Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
    Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
    Reviewed-by: Keith Haddow <haddowk@chromium.org>
    Reviewed-by: Aviv Keshet <akeshet@chromium.org>
    Reviewed-by: Prathmesh Prabhu <pprabhu@chromium.org>
    
  - network_ShillInitScripts: don't stop recover_duts
    
    The /run/autotest_pause_ethernet_hook lock can prevent recover_duts from
    interrupting us (e.g., because when we `stop shill`, it notices a loss
    in connectivity).
    
    BUG=chromium:530793
    TEST=`touch /mnt/stateful_partition/.labmachine; start recover_duts`;
         run test, watch `status recover_duts` and
         `flock /run/autotest_pause_ethernet_hook ${cmd}`
    TEST=power_SuspendStress
    
    Change-Id: I4d7fbbfd1a60222ec9939d7c82c026c87e45e262
    Reviewed-on: https://chromium-review.googlesource.com/1743259
    Tested-by: Brian Norris <briannorris@chromium.org>
    Commit-Ready: Brian Norris <briannorris@chromium.org>
    Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
    Reviewed-by: Ravi Chandra Sadineni <ravisadineni@chromium.org>
    
  - bluetooth: Remove suite:bluetooth_quicksanity
    
    BUG=b:138400393
    TEST=None
    
    Change-Id: I3503f40ed812042e0f6b15cdf532661ab4ccab6b
    Reviewed-on: https://chromium-review.googlesource.com/1722298
    Tested-by: Shijin Abraham <shijinabraham@google.com>
    Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
    Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
    Reviewed-by: Yun-Hao Chung <howardchung@google.com>
    
  - tast: Increase timeout of crosbolt tests to 3 hours.
    
    BUG=b:139391369
    TEST=None
    
    Change-Id: I912d3355c5dcfd5df3c179b2adac5a990f52902b
    Reviewed-on: https://chromium-review.googlesource.com/1752224
    Tested-by: Shuhei Takahashi <nya@chromium.org>
    Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
    Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
    Reviewed-by: Chung-yih Wang <cywang@google.com>
    
  - servo: add ControlUnavailableError, has_control()
    
    This change adds its own error class for servo erros where the control is
    unavailable on the servod side. This simplifies some of the code as the autotest
    code occasionally requires bridges to ensure compatibility with older and newer
    servod versions.
    
    As the new error class inherits from TestFail, existing code should still work.
    
    Additionally, it adds a has_control() function to servo.py
    
    This now allows for two flows:
    - if the control is likely available, and just some lab compatibility
    issues i.e. slow updating of labstations are to be guarded against,
    try/except is probably the way to go
    - if the test should handle things differently whether a control is
    available or not, has_control() is likely the way to go.
    
    BUG=chromium:924434
    TEST=test_that --autotest_dir . $DUP_IP power_ServoChargeStress.3loop
    
    // This test uses servo (thus goes through initiation flow) and uses a few
    // controls. To verify set/get still work as expected.
    
    Change-Id: I75738fad629faa5c93318d30246c894dcf900227
    Signed-off-by: Ruben Rodriguez Buchillon <coconutruben@chromium.org>
    Reviewed-on: https://chromium-review.googlesource.com/1749608
    Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
    Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
    Reviewed-by: Wai-Hong Tam <waihong@google.com>
    Reviewed-by: Mary Ruthven <mruthven@chromium.org>
    
  - servo: enforce keyboard on after hwinit when reflashing
    
    This change forces the keyboard to be on after a hwinit when reflashing
    a DUT, the same way it does for initialize_dut, as hwinit might turn it
    off from underneath us.
    
    BUG=chromium:992094
    TEST=test_that platform_InstallTestImage -b krane
    
    Change-Id: Idfa26b850a445eb430578d819b214f5cf2f14a21
    Signed-off-by: Ruben Rodriguez Buchillon <coconutruben@chromium.org>
    Reviewed-on: https://chromium-review.googlesource.com/1745516
    Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
    Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
    Reviewed-by: Hsin-Yi Wang <hsinyi@chromium.org>
    Reviewed-by: Nicolas Boichat <drinkcat@chromium.org>
    

* Update external/icu from branch 'simpleperf-release'
  to 73e5e7598955f4e112dc42dff56ea24786c054ef
  - Snap for 5806856 from 1b2d36db375637fd477cf6a4eef891a5395058ff to simpleperf-release
    
    Change-Id: I2138b3e73b084b85013f8b4518574ec7967da314
    
  - Merge "Suppress new ignored-attributes warning"
  - Suppress new ignored-attributes warning
    
    In file included from external/icu/icu4c/source/common/putil.cpp:68:
    external/icu/icu4c/source/common/umutex.h:52:17: error: 'dllexport' attribute ignored on explicit instantiation definition [-Werror,-Wignored-attributes]
    template struct U_COMMON_API std::atomic<int32_t>;
                    ^
    external/icu/icu4c/source/common/unicode/utypes.h:316:24: note: expanded from macro 'U_COMMON_API'
    #define U_COMMON_API   U_EXPORT
                           ^
    external/icu/icu4c/source/common/unicode/platform.h:790:32: note: expanded from macro 'U_EXPORT'
    #   define U_EXPORT __declspec(dllexport)
                                   ^
    1 error generated.
    
    Test: Build
    Bug: 131328001
    Change-Id: Ia8d8e2325141eb0e684c4ec0c5627812f49f43e2
    

* Update frameworks/opt/net/ike from branch 'simpleperf-release'
  to ba84e773477f570d7e25ba69a13ac47988e9ceb5
  - Snap for 5806856 from 24c1b6bb169fc8993227726d3e82a67b6b16d069 to simpleperf-release
    
    Change-Id: Ie31f874d0e8670abfa777382d4a315934080babc
    
  - Merge "Handle deletion in Child initial state"
  - Handle deletion in Child initial state
    
    This commit:
    - Handle deletion in Child initial state
    - Ignore request when the target Child Session is deleted
    
    Bug: 139436289
    Test: atest FrameworksIkeTests
    Change-Id: I0cf967d2d3268049b736ef8eb20e905f40fdbc44
    

* Update system/core from branch 'simpleperf-release'
  to 141e868dd8cc1bbdf674643eb568a5e68629b973
  - Merge "Snap for 5806856 from 536dd4292ea687908f6e5ca61a00e6046d5bfe27 to simpleperf-release" into simpleperf-release
  - Snap for 5806856 from 536dd4292ea687908f6e5ca61a00e6046d5bfe27 to simpleperf-release
    
    Change-Id: I07c4eaad86deab7cc927d097c45409b3ceaf179c
    
  - Merge "Rename libfiemap libraries."
  - Rename libfiemap libraries.
    
    Update Android.bp for libfiemap library renames.
    
    Test: builds
    
    Change-Id: I318c5f64452726579cebb41792b95f6b9e47fbb8
    

* Update system/gsid from branch 'simpleperf-release'
  to a5fd7d9fe98b31d2532b53c8054f8157df82237d
  - Snap for 5806856 from 5cc48468c670e93b27d53f4889cd7ea9f45f1732 to simpleperf-release
    
    Change-Id: I047cd783c5e997fe41a5bff4bccd9eb7c1867bf2
    
  - libfiemap: Do not use weak linkage.
    
    Move the passthrough IImageManager::Open function to libfiemap_passthrough
    The weak function can then be removed, avoid accidental linkages. Clients
    will link to libfiemap_passthrough or libfiemap_binder explicitly.
    
    Also, clean up libfiemap/Android.bp.
    
    Test: builds
    Test: fiemap_writer_test
    Test: fiemap_image_test
    Change-Id: I10aa4f3cf2e61ca32fb29950fc5ba29ad3b50146