Update git submodules
* Update external/clang from branch 'lldb-master-dev'
  to 0aeca790577599e02ad424bfd8a5dd39191b5cd3
  - Merge "[VFS] Implement `RedirectingFileSystem::getRealPath`. am: 30a86941b0" into lldb-master-dev
  - [VFS] Implement `RedirectingFileSystem::getRealPath`.
    am: 30a86941b0
    
    Change-Id: I2fdc6b2bff19018814c9b6a476230b8df891d7c9
    
  - [VFS] Implement `RedirectingFileSystem::getRealPath`.
    
    It fixes the case when Objective-C framework is added as a subframework
    through a symlink. When parent framework infers a module map and fails
    to detect a symlink, it would add a subframework as a submodule. And
    when we parse module map for the subframework, we would encounter an
    error like
    
    > error: umbrella for module 'WithSubframework.Foo' already covers this directory
    
    By implementing `getRealPath` "an egregious but useful hack" in
    `ModuleMap::inferFrameworkModule` works as expected.
    
    LLVM commit is r347009.
    
    rdar://problem/45821279
    
    Reviewers: bruno, benlangmuir, erik.pilkington
    
    Reviewed By: bruno
    
    Subscribers: hiraditya, dexonsmith, JDevlieghere, cfe-commits, llvm-commits
    
    Differential Revision: https://reviews.llvm.org/D54245
    
    
    
    git-svn-id: https://llvm.org/svn/llvm-project/cfe/trunk@347012 91177308-0d34-0410-b5e6-96231b3b80d8