Update git submodules
* Update external/clang from branch 'lldb-master-dev'
  to f48e9274f6032499adfa30b7e28789b09ed79266
  - Merge "Add support for -mno-tls-direct-seg-refs to Clang am: 38c9197d87" into lldb-master-dev
  - Add support for -mno-tls-direct-seg-refs to Clang
    am: 38c9197d87
    
    Change-Id: Ib35cc29cf0e0b24b34448ef72ac0aeb46cdd3be4
    
  - Add support for -mno-tls-direct-seg-refs to Clang
    
    This patch exposes functionality added in rL344723 to the Clang driver/frontend
    as a flag and adds appropriate metadata.
    
    Driver tests pass:
    ```
    ninja check-clang-driver
    -snip-
      Expected Passes    : 472
      Expected Failures  : 3
      Unsupported Tests  : 65
    ```
    
    Odd failure in CodeGen tests but unrelated to this:
    ```
    ninja check-clang-codegen
    -snip-
    /SourceCache/llvm-trunk-8.0/tools/clang/test/CodeGen/builtins-wasm.c:87:10:
    error: cannot compile this builtin function yet
    -snip-
    Failing Tests (1):
        Clang :: CodeGen/builtins-wasm.c
    
      Expected Passes    : 1250
      Expected Failures  : 2
      Unsupported Tests  : 120
      Unexpected Failures: 1
    ```
    
    Original commit:
    [X86] Support for the mno-tls-direct-seg-refs flag
    Allows to disable direct TLS segment access (%fs or %gs). GCC supports a
    similar flag, it can be useful in some circumstances, e.g. when a thread
    context block needs to be updated directly from user space. More info and
    specific use cases: https://bugs.llvm.org/show_bug.cgi?id=16145
    
    Patch by nruslan (Ruslan Nikolaev).
    
    Differential Revision: https://reviews.llvm.org/D53102
    
    
    
    git-svn-id: https://llvm.org/svn/llvm-project/cfe/trunk@344739 91177308-0d34-0410-b5e6-96231b3b80d8