Update git submodules
* Update external/llvm from branch 'lldb-master-dev'
  to e858e8730a3ecab547c23affb75cf88352926bc4
  - Merge "Revert "[COFF] Use comdat shared constants for MinGW as well" am: 078cc9c528" into lldb-master-dev
  - Revert "[COFF] Use comdat shared constants for MinGW as well"
    am: 078cc9c528
    
    Change-Id: I58695fb4c77db68b025585b74b1411446be7cdf7
    
  - Revert "[COFF] Use comdat shared constants for MinGW as well"
    
    This reverts commit r337951.
    
    While that kind of shared constant generally works fine in a MinGW
    setting, it broke some cases of inline assembly that worked before:
    
    $ cat const-asm.c
    int MULH(int a, int b) {
        int rt, dummy;
        __asm__ (
            "imull %3"
            :"=d"(rt), "=a"(dummy)
            :"a"(a), "rm"(b)
        );
        return rt;
    }
    int func(int a) {
        return MULH(a, 1);
    }
    $ clang -target x86_64-win32-gnu -c const-asm.c -O2
    const-asm.c:4:9: error: invalid variant '00000001'
            "imull %3"
            ^
    <inline asm>:1:15: note: instantiated into assembly here
            imull __real@00000001(%rip)
                         ^
    
    A similar error is produced for i686 as well. The same test with a
    target of x86_64-win32-msvc or i686-win32-msvc works fine.
    
    git-svn-id: https://llvm.org/svn/llvm-project/llvm/trunk@338018 91177308-0d34-0410-b5e6-96231b3b80d8