Update git submodules
* Update external/selinux from branch 'master'
  to c3e8eef8825cd02ab93d6429fc04d3935327b1cc
  - Merge remote-tracking branch 'aosp/upstream-master' into mymerge
    
    Followed the following steps:
      # In repo client
      cd external/selinux
      repo sync .
      repo start mymerge .
      git merge aosp/upstream-master --no-ff # resolve any conflicts
      repo upload .
    
    Test: android compiles and boots and no observed problems.
    Change-Id: I9fedadcaad26aa01425b71b9897f2dd0aa53468d
    
  - python/semanage: explain why sepolicy is imported in a function
    
    Importing modules inside functions is quite uncommon in Python. This is
    nevertheless required with sepolicy because it loads the current SELinux
    policy when it is imported (and raises ValueError when this fails).
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - python/audit2allow: allow using audit2why as non-root user
    
    Importing sepolicy as non-root on a system with SELinux causes the
    following exception to be raised:
    
        ValueError: No SELinux Policy installed
    
    Ignore this when using audit2why, which allows using it with option
    --policy as a non-root user.
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - python/audit2allow/sepolgen-ifgen: show errors on stderr
    
    This allows test_audit2allow.py to display the errors correctly.
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - python/audit2allow/sepolgen-ifgen: add missing \n to error message
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - python/sepolgen: close /etc/selinux/sepolgen.conf after parsing it
    
    sepolgen testsuite reports the following warning on a system with
    /etc/selinux/sepolgen.conf:
    
        .../src/./sepolgen/defaults.py:35: ResourceWarning: unclosed file
        <_io.TextIOWrapper name='/etc/selinux/sepolgen.conf' mode='r'
        encoding='UTF-8'>
    
    Fix this by properly closing the file in PathChooser.__init__().
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - libsemanage: Always set errno to 0 before calling getpwent()
    
    The manpage explicitly states that:
    
      The  getpwent()  function  returns a pointer to a passwd structure, or
      NULL if there are no more entries or an error occurred.  If an error
      occurs, errno is set appropriately.  If one wants to check errno after
      the call, it should be set to zero before the call.
    
    Without this, genhomedircon can wrongly return the following:
      libsemanage.get_home_dirs: Error while fetching users.  Returning list so far.
    
    https://github.com/SELinuxProject/selinux/issues/121
    
    Signed-off-by: Laurent Bigonville <bigon@bigon.be>
    
  - python/sepolicy: Make policy files sorting more robust
    
    The sorting order seems to be fragile because '100' < '99', so the policy
    filename needs to be parsed in order to extract the version as an integer and
    sort according to it.
    
    Based on idea from Nicolas Iooss <nicolas.iooss@m4x.org>
    
    Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
    
  - python/semanage: Load a store policy and set the store SELinux policy root
    
    When "store" is set, sepolicy needs to load a new policy file and selinux module
    needs to set the new store root path.
    
    With this patch, semanage is able to work correctly with non-default -S <store>
    even when the default policy is not installed yet.
    
    Fixes:
    $ sudo semanage login -S minimum -m -s unconfined_u -r s0-s0:c0.c1023 __default__
    libsemanage.dbase_llist_query: could not query record value
    OSError: [Errno 0] Error
    
    Related: https://bugzilla.redhat.com/show_bug.cgi?id=1558861
    
    Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
    
  - python/sepolicy: Add sepolicy.load_store_policy(store)
    
    load_store_policy() allows to (re)load SELinux policy based on a store name. It
    is useful when SELinux is disabled and default policy is not installed; or when
    a user wants to query or manipulate another policy.
    
    Related: https://bugzilla.redhat.com/show_bug.cgi?id=1558861
    
    Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
    
  - python/semanage: import sepolicy only when it's needed
    
    Related:
    https://github.com/SELinuxProject/selinux/issues/81
    
    Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
    
  - python/semanage: move valid_types initialisations to class constructors
    
    Based on idea from Nicolas Iooss <nicolas.iooss@m4x.org>
    
    Fixes:
    $ sudo semanage
    Traceback (most recent call last):
      File "/usr/sbin/semanage", line 28, in <module>
        import seobject
      File "/usr/lib/python3.7/site-packages/seobject.py", line 1045, in <module>
        class portRecords(semanageRecords):
      File "/usr/lib/python3.7/site-packages/seobject.py", line 1047, in portRecords
        valid_types = list(list(sepolicy.info(sepolicy.ATTRIBUTE, "port_type"))[0]["types"])
      File "/usr/lib/python3.7/site-packages/sepolicy/__init__.py", line 203, in <genexpr>
        return ({
      File "/usr/lib64/python3.7/site-packages/setools/typeattrquery.py", line 65, in results
        for attr in self.policy.typeattributes():
    AttributeError: 'NoneType' object has no attribute 'typeattributes'
    
    https://github.com/SELinuxProject/selinux/issues/81
    
    Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
    
  - python/sepolgen: upgrade ply to release 3.11
    
    PLY (Python Lex-Yacc) 3.11 has been released in February 2018:
    - http://www.dabeaz.com/ply/index.html
    - https://github.com/dabeaz/ply/releases/tag/3.11
    
    Copy lex.py and yacc.py from this new release.
    
    This fixes the following warning from "make test":
    
        python run-tests.py
        ../src/./sepolgen/lex.py:634: DeprecationWarning: Using or importing
        the ABCs from 'collections' instead of from 'collections.abc' is
        deprecated, and in 3.8 it will stop working
         if isinstance(t, collections.Callable):
    
    (Python 3.3 moved collections.Callable to collections.abc.Callable)
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - semanage_migrate_store: switch to space indentation
    
    The script used both tabs and space to indent the code, using a tab
    length of 8 (in calls to parser.add_option(...)). Make the code more
    readable by using spaces for indentation everywhere.
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - semanage_migrate_store: remove unused loading of libsepol.so
    
    semanage_migrate_store loads libsepol.so using ctypes but never uses it.
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - semanage_migrate_store: fix many Python linter warnings
    
    flake8 reports many warnings on script semanage_migrate_store:
    
        E225 missing whitespace around operator
        E302 expected 2 blank lines, found 1
        E701 multiple statements on one line (colon)
        E703 statement ends with a semicolon
        E722 do not use bare 'except'
        ...
    
    Fix some of them in order to reduce the noise.
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - Makefile: add -Wstrict-overflow=5 to CFLAGS
    
    Build with strict overflow checking enabled. If the compiler optimizes
    code that could be removed due to undefined signed overflow, then the
    compiler will issue a warning.
    
    Signed-off-by: William Roberts <william.c.roberts@intel.com>
    
  - build: set _FORTIFY_SOURCE=2 in libselinux
    
    Use -D_FO0RTIFY_SOURCE=2 when building libselinux and it's util library.
    Note that this can be overridden by setting CFLAGS during the build.
    
    Signed-off-by: William Roberts <william.c.roberts@intel.com>
    
  - Makefile: fix _FORTIFY_SOURCE redefined build error
    
    Certain builds of gcc enable _FORTIFY_SOURCE which results in the error:
    <command-line>:0:0: warning: "_FORTIFY_SOURCE" redefined
    <command-line>:0:0: note: this is the location of the previous definition
    
    Correct this by undefining it first and redefining it. Also, the previous
    command line option was using -Wp which is passing the value *AS IS* to the
    pre-processor rather than to the compiler driver. The C pre-processor has
    an undocumented interface subject to change per man 1 gcc. Just use the
    -D option to specify this value.
    
    Signed-off-by: William Roberts <william.c.roberts@intel.com>
    
  - mcstrans: Fix check in raw_color()
    
    raw_color() uses color_str as an output argument which is assigned to a new
    allocated memory. Therefore it should fail when color_str is null; or
    when *color_str is not null in order to avoid a memory leak.
    
    Fixes:
    >>> selinux.selinux_raw_context_to_color('system_u:system_r:inetd_t:s0')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    OSError: [Errno 0] Error
    
    Signed-off-by: Petr Lautrbach <plautrba@redhat.com>