Update git submodules
* Update bionic from branch 'master'
  to 998175dc6f45e401746fb420c7c245ef8eb074c4
  - Merge "Merge pie-platform-release (PPRL.181105.017, history only) into master"
  - Merge pie-platform-release (PPRL.181105.017, history only) into master
    
    Bug: 118454372
    Change-Id: I6b85bc54ed30bf7711e9b4bff80e181d7ec2b11f
    
  - Merge pi-qpr1-release PQ1A.181105.017.A1 to pi-platform-release
    
    Change-Id: Ic9f65be968a41b3419a655102838a432f8d3b62d
    
  - Snap for 4920102 from fbe26c723af60b101a6df9c066c1b661b6ab966c to pi-qpr1-release
    
    Change-Id: Ifd7027234368d31d675303934b1f0f8b6e23d714
    
  - Merge "remove bionic-compile-time-tests-g++" into pi-dev
  - Snap for 4916303 from 6fffb2332ca3be3abee84810b389a29b731887ee to pi-qpr1-release
    
    Change-Id: If8971618ca5839bb3044dd35acbd31189ebb613e
    
  - remove bionic-compile-time-tests-g++
    
    make checkbuild gives the following error:
    bionic/tests/fortify_filecheck_diagnostics_test.cpp:1:0: error: unknown value 'cortex-a55' for -mcpu
    
    The error is because we have a clang to support the new architecture,
    but not a corresponding GCC. It is not trivial to filter out an invalid
    CPU, and since there is no platform code built with GCC any more, its
    better to remove bionic-compile-time-tests-g++
    
    Bug: 74404306
    Change-Id: I6aa181c652abeef782fec6380dfadd066140b8b9
    
  - Disable malloc debug intercepts when exiting.
    
    There is a hang when enabling leak_track since the dumping of the
    leak data can wind up doing an allocation.
    
    Add new system unit test to make sure this doesn't happen again.
    
    Bug: 111146059
    
    Test: Test program that leaks does not hang forever.
    Test: Unit tests pass.
    Change-Id: Icf99be58ba5db98ee124a471b957a086045f5870
    Merged-In: Icf99be58ba5db98ee124a471b957a086045f5870
    (cherry picked from commit 97b474710225bc4853ab314c3d9ca812dc375525)
    

* Update device/generic/goldfish-opengl from branch 'master'
  to e3c573dfed0deac05f6e89fe7c0ecff359fe2a09
  - Merge pie-platform-release (PPRL.181105.017, history only) into master
    
    Bug: 118454372
    Change-Id: I329d78c043cc9c178b18d898417562b44a72b9fa
    
  - Merge pi-qpr1-release PQ1A.181105.017.A1 to pi-platform-release
    
    Change-Id: Ib4e310cd8dd58202d9847fbeca00454d5b705bc5
    
  - Snap for 4957529 from 9a1614b6a68a3e05e06995ca32c9e67ffb854297 to pi-qpr1-release
    
    Change-Id: I63a7d243c57e300aa07073fcddfe7fd62dda86b9
    
  - Merge "Partially revert ag/4742391." into pi-dev
  - Merge "Fix compile warnings emmitted from system/OpenglSystemCommon." into pi-dev
  - Partially revert ag/4742391.
    
    Needed to fix
    
    https://android-build.googleplex.com/builds/quarterdeck?branch=git_ics-mr1-emu-dev&target=sdk_x86-sdk&lkgb=4951371&fkbb=4954575
    
    It appears that some compiler setups do not accept the C99 syntax
    
    Bug: b/80194417
    Test: Recompile
    Change-Id: Ica21f2dc24a526358e9ae904fba55e1aa84bc6c8
    
  - Snap for 4954419 from b79f8897472251589814b4690367a50e6ca20096 to pi-qpr1-release
    
    Change-Id: I2e58404f822184d9602b880f6dd1fc394afc86b9
    
  - Merge "Fix compile warnings in system/GLES." into pi-dev
  - Merge "Fix compiler warnings emmited from system/egl/egl.cpp." into pi-dev
  - Fix compile warnings found in shared/OpenglCodecCommon.
    
    Bug: b/80194417
    Test: Recompile and look for warnings.
    Change-Id: Icd4ad776ffbe8daf3e6c3af821149cadf4657d78
    
  - Fix compiler warnings emmited from system/egl/egl.cpp.
    
    Bug: b/80194417
    Test: Recompile and check for warnings.
    Change-Id: Ie9c301ddb14d7c49a1106aac1255eb47d626adf1
    
  - Fix compile warnings emmitted from system/OpenglSystemCommon.
    
    Bug: b/80194417
    Test: Recompile and check for warnings.
    Change-Id: I7b97d7acffabd7e87772a57c3256d9d3e4057f84
    
  - Fix compile warnings in system/GLES.
    
    Bug: b/80194417
    Test: Recompile and check for warnings.
    Change-Id: I9acd46ab6831ee12d59a602542d702c5beef63b4
    
  - Snap for 4920102 from ff9e26650889fe4740683eaabb6e207608f9fdb9 to pi-qpr1-release
    
    Change-Id: I36ea18d8d4795eb5bcfdffa971048fb6ccec6569
    
  - Using fixed value to count gralloc buffer offset
    
    Gralloc module may be used by CameraHal(32bit) and Apk(64bit).
    Counting offset with int_ptr results in different values.
    
    Bug: 73485161
    
    Test: run cts -m CtsCameraTestCases
    Change-Id: I7d8d3f20652107df1fd7812d30c01e4546ac4a22
    

* Update device/google/cuttlefish from branch 'master'
  to 2b9fa2240826eae26939fdd194c4521d3d8cd3db
  - Merge pie-platform-release (PPRL.181105.017, history only) into master
    
    Bug: 118454372
    Change-Id: Ibfea0f10be817230fd879c9341753e306b7ff553
    
  - Merge pi-qpr1-release PQ1A.181105.017.A1 to pi-platform-release
    
    Change-Id: I9d217702012e6067adf95b221470bc788230e38b
    
  - Snap for 4959688 from a2e1b65baa2ce24d606287e869fb8e8ca70e1f65 to pi-qpr1-release
    
    Change-Id: If5305158d33d2a8ecd6e1fe7a278e1b54e6f76fa
    
  - Removed libbt-vendor-build-test from device.mk
    
    This target is not needed in treble-compliant devices.
    
    Bug: 112661635
    Test: run cf locally
    Change-Id: If0b5424180948304e65591a29402543d47b753f1
    Merged-In: If0b5424180948304e65591a29402543d47b753f1
    
  - Snap for 4957529 from 0f751d60bdf219486de810a4d9bbb2c936596573 to pi-qpr1-release
    
    Change-Id: Ib2c8c90704d99f9303c599c407b3241018986a7d
    
  - Add Broadcast Radio HAL to Cuttlefish Auto device
    
    Bug: 112604360
    Test: build and launch cf_x86_auto-userdebug; atest BroadcastRadioTests
    Change-Id: I22bc153abcc4ae46660edfc661ca458e90c70e8f
    (cherry picked from commit 38398875f52fe4a31af4cf64b42b488c28b2bd36)
    
  - Snap for 4924178 from 805aea1d43aafaa94fc44e5735f0327872797154 to pi-qpr1-release
    
    Change-Id: Ifd53c41b1b139c00b24c5eeb1f4b644935884e53
    
  - Merge "Remove the manifest.xml from the shared device.mk" into pi-dev
  - Remove the manifest.xml from the shared device.mk
    
    BUG: 112008105
    Test: Built auto on aosp, confirmed manifest.xml
    Change-Id: I12e501013c51261963801a393c6ea4669fd582e8
    Merged-In: I12e501013c51261963801a393c6ea4669fd582e8
    (cherry picked from commit 3b6d882bcf1db46b6b919bd349a6b5b170c2272b)
    
  - Snap for 4922203 from e3c59991b947462edeba44a87cf4adbebd53cfc2 to pi-qpr1-release
    
    Change-Id: Ifa7402cc14f2fcf58cfc3716d51a366da000681a
    
  - Remove unsupported cf_x86_64_auto build target
    
    BUG: 111907481
    Test: Target not found
    Change-Id: I1e5dd158f573e2e4eae9f529995716bd4e295bde
    
  - Move the device manifest files to device.mk
    
    BUG: 112008105
    Test: Built. Auto stuff appears in manifest.xml
    Change-Id: I3b8ddacbdd393430c86468137a73353222c81369
    
  - Added AAE specific device manifest to Cuttlefish
    
    Bug: 111763661
    Test: lunch cf_x86_auto-userdebug; make dist; launch cuttlefish and all
    AAE specific HALs should be registered
    
    Change-Id: I82beccb330cd2993f1e23a60e64ef11bf7c50ea4
    

* Update external/perfetto from branch 'master'
  to 2f60a6e277a1af558c763fcff4714ca98ecda954
  - Merge "Merge pie-platform-release (PPRL.181105.017, history only) into master"
  - Merge pie-platform-release (PPRL.181105.017, history only) into master
    
    Bug: 118454372
    Change-Id: I7dd43c588f881d4b18a4e7f81edea55d5e08899f
    
  - Merge pi-qpr1-release PQ1A.181105.017.A1 to pi-platform-release
    
    Change-Id: I9efa98649f303c655eea58ea87dcc70fe2d58e6d
    
  - Snap for 4916303 from c5e18407c277ca75b854b4416c70d23dc2c6a90e to pi-qpr1-release
    
    Change-Id: Ic4adee77a3526f949bf45bd1bf5d86c76d58edbc
    
  - traced_probes: Fix clock bug
    
    There was a bug when parsing the list of available clocks from
    /d/tracing/trace_clock.
    
    The contents of /d/tracing/trace_clock looks like:
    uptime perf mono mono_raw boot\n
    We acidentally included the newline in the name of the final clock when
    reading. This means (if boot is unfortunate enough to be the last clock
    listed) we fail to set the boot clock (since "boot" != "boot\n").
    
    Fix the parsing of trace_clock to discount the newline.
    
    Bug: 110356412
    Change-Id: I5160637efec69844fe75f8e705d02a7c486ae990
    Merged-In: I5160637efec69844fe75f8e705d02a7c486ae990
    (cherry picked from commit 22dac14815a58d00ea87a0013bb638c703843f11)
    

* Update external/sl4a from branch 'master'
  to 34b5e14ddc25bcfff2bf7ff871c4b11dc37290f4
  - Merge pie-platform-release (PPRL.181105.017, history only) into master
    
    Bug: 118454372
    Change-Id: I772b37d1ed164966c57474c4db929aa262d65908
    
  - Merge pi-qpr1-release PQ1A.181105.017.A1 to pi-platform-release
    
    Change-Id: I4faab423b43c479506111da39498f7e363de0b3e
    
  - Snap for 4916303 from 20112b515c21b698601d488326464968c4591fc8 to pi-qpr1-release
    
    Change-Id: I883ce89e4d3a59f5f5910dde2fcd58cfd67523f6
    
  - [ConnectivityManagerFacade] APIs for proxy testing
    
    CHERRY PICKED FROM AOSP
    
    Bug: 111309129
    Test: Verified the changes
    Change-Id: I5bff2876fe8f456462d941b4157a6752543e23e9
    Merged-In: I4026f4640cd9ef64372fc6631946299f5d6fcba2
    
  - [ConnectivityManagerFacade] Changes to Natt Keepalive APIs
    
    CHERRY PICKED FROM AOSP
    
    connectivityStartNattKeepalive() returns a key which allows us to listen
    for a 'Started' event using
    connectivityNattKeepaliveStartListeningForEvent(). Similarly, to listen
    to a 'Stopped' event we use
    connectivityNattKeepaliveStopListeningForEvent(). However,
    connectivityStopNattKeepalive() deletes the key, which makes the API
    useless. Added a new API to delete the key.
    
    Bug: 72420688
    Test: Verified the changes
    Change-Id: Ia7a43e5d03ee55a92b367035d7152901ec907df3
    Merged-In: I762ad5e0f8e7346d09d2c2904d7cbd65a25e58e8
    

* Update system/extras from branch 'master'
  to 1309cb5e4d53307af7ba5ead3a28377a66e6a877
  - Merge "Merge pie-platform-release (PPRL.181105.017, history only) into master"
  - Merge pie-platform-release (PPRL.181105.017, history only) into master
    
    Bug: 118454372
    Change-Id: I4b5e4e99649250b4bd65e780925c5fc3001fe710
    
  - Merge pi-qpr1-release PQ1A.181105.017.A1 to pi-platform-release
    
    Change-Id: I171c9c28f68e3f26e173dca9dc3fe0bb1bd68c95
    
  - Snap for 4939496 from fa9ce0e4a240d50fde168369c2095d1e14241a97 to pi-qpr1-release
    
    Change-Id: I07a2fb093806a835d82f109574cc774d4a487da5
    
  - Revert "Support Speck encryption."
    
    This is a partial revert of
    commit 6a0fa62dc71157f85b24ed15e39ada277f9b5201.
    
    Remove the Speck encryption support. It was eventually
    decided not to allow Speck in Android P, so this code
    is no longer needed and wasn't used outside of testing.
    
    We retain the e4crypt_get_policy_flags() changes from original
    commit, though.
    
    Bug: 112009351
    Test: Confirmed AES continues to work with FBE.
    Change-Id: I53b091dd4c5392de7a00a8c168919fb55e527eaf
    
  - simpleperf: fix test on APCT.
    
    Bug: http://b/77470883
    Test: run adb shell
    Test: /data/local/tmp/simpleperf_unit_test/simpleperf_unit_test.
    Change-Id: I640ad76b68842045f6ecdcb3cf686b7823d7d5db
    (cherry picked from commit 03a31c13168f6502883e8beb4dbc76bc064a54a0)
    

* Update system/vold from branch 'master'
  to 80647cf6072a9647ae016a5267eb4b0c91b5a174
  - Merge "Merge pie-platform-release (PPRL.181105.017, history only) into master"
  - Merge pie-platform-release (PPRL.181105.017, history only) into master
    
    Bug: 118454372
    Change-Id: Ibc7ddf231ff61272439b9a621490acaff27ce563
    
  - Merge pi-qpr1-release PQ1A.181105.017.A1 to pi-platform-release
    
    Change-Id: I090e55f0f34ff556118caaecbb21169580c66ab6
    
  - Snap for 4939496 from 17059fe53b7f535886918d06fea58a90930862fc to pi-qpr1-release
    
    Change-Id: Id8422a6cb43aa012ff53dd70a684b3b3c859ec51
    
  - cryptfs: Remove Speck support
    
    Remove the Speck encryption support. It was eventually
    decided not to allow Speck in Android P, so this code
    is no longer needed and wasn't used outside of testing.
    
    Note we don't just "git revert" the original commit
    (38723f23ff521e95ed295f500e6529c52a994c9f) because we want
    to retain the infrastructure for allowing new types of
    crypto algorithms in the future.
    
    Bug: 112009351
    Test: Attempted to setup a device with ro.crypto.fde_algorithm set to Speck, and Speck was rejected and the system defaulted to AES.
    Change-Id: I69a8b4e8632f8d30b5b54783cb986ab42d4397d9
    
  - Snap for 4922203 from 31e962fe1970b12ec216cf3e376d126d082144a4 to pi-qpr1-release
    
    Change-Id: Ia64205e7135bcd0ced71c3e82fe59ffeb23d760a
    
  - vold: meta encryption: fix /dev/block/by-name/userdata to dm-3
    
    This fixes F2FS GC failure in idle-maint.
    07-28 18:25:54.838   603 11187 D vold    : idle maintenance started
    07-28 18:25:54.846   603 11187 D vold    : Start GC on /sys/fs/f2fs/sda21
    07-28 18:25:54.847   603 11187 W vold    : Set discard gralunarity failed on/sys/fs/f2fs/sda21: No such file or directory
    07-28 18:25:54.847   603 11187 W vold    : Start GC failed on /sys/fs/f2fs/sda21: No such file or directory
    
    Bug: 111953875
    Change-Id: I1d10802121d5641cf9ba780fee249affd2cf6ffe
    Signed-off-by: Jaegeuk Kim <jaegeuk@google.com>
    

* Update tools/test/connectivity from branch 'master'
  to 15d692e629af47c32ae84fb4514f20b47108f6a8
  - Merge "DO NOT MERGE"
  - DO NOT MERGE
    
    Merge pie-platform-release (PPRL.181105.017, history only) into master
    
    Bug: 118454372
    Change-Id: I4d9f317beccbdc5dfc419daf640b4cfcd3346b2d
    
  - Merge pi-qpr1-release PQ1A.181105.017.A1 to pi-platform-release
    
    Change-Id: I6ff8e08af023c6a2da41d29056af7bb2f70308be
    
  - Snap for 4945494 from 7b00a3a220e4a4c257216503812a3ebd92b4b582 to pi-qpr1-release
    
    Change-Id: I8db466ac2800311fd3d07a3535155f22f8dc7e05
    
  - [DhcpServerTest] Add UUIDs to the new test cases
    
    CHERRY CHANGES FROM AOSP
    
    The CLs include 32 new test cases along with UUIDs
    
    Bug: 109670497
    Test: Verified the changes manually
    
    Change-Id: Iae193bb07bc5092b685cf150c6b3457b0c5998a5
    Merged-In: I4380caa039f7a45bf4b99c15629a0e2d09e6f7ff
    
  - Snap for 4920102 from 11922e8d5b6b4dedfe617b49197fc7b21a28e6ea to pi-qpr1-release
    
    Change-Id: Ib7d452939c323cdcaa4b08468716455a46521759
    
  - Merge "[ProxyTest] Add tests for proxy" into pi-dev
  - [ProxyTest] Add tests for proxy
    
    CHERRY PICKED FROM AOSP
    
    Bug: 111309129
    Test: Verified the changes
    Change-Id: I2b9980df7e61a20a2d4a7aa11e8624c79211f9de
    Merged-In: I1f507af0d16029bf360950c6618c277b4ecb9664
    
  - [WifiTethering_OTATest] Add UUIDs to the tests
    am: ff33ef895f
    
    Change-Id: Ia1bb08ff10cf1c38b3481b671693cd6839d2ac9e
    
  - [WifiTethering_OTATest] Add UUIDs to the tests
    
    Bug: 109876567
    Test: Verified the changes
    Change-Id: Ic424b4c61d32d24aa120c941ab523e3614c7c130
    Merged-In: Ic314d4397b8cef059d1944514003bcbca82d6d36
    
  - [WifiTethering_OTATest] Add UUIDs to the tests
    
    Bug: 109876567
    Test: Verified the changes
    Change-Id: Idc8eab275270c394a9b5ea11c6987716900dfd46
    Merged-In: Ic314d4397b8cef059d1944514003bcbca82d6d36
    
  - Snap for 4916303 from 029d8e1d5ff9a3e988573e288002af68ac336d9c to pi-qpr1-release
    
    Change-Id: Ic4d38fc667112d17d82bba1cfa02d545314e0ce4
    
  - Merge "Merge "Add wifi_iot_tw test package1" am: ec63061434 am: 8faa8f58d3 am: 638c6e2397" into pi-dev
  - Merge "Merge "Add wifi RVR TW test" am: 61562a0da0 am: 19160b1453 am: 4dcdf2f67c" into pi-dev
  - [Tests]Add stress test to play youtube video in loop over wifi.
    
    Also fix test run times for few tests and add more logging.
    
    Bug: 111653976
    Bug: 111604990
    Test: Local
    Change-Id: I745bc1954002c0a75c346e52ebd52af7ca148716
    (cherry picked from commit 3585b10f621ab0abf8f550edd4d9a10d07cb40b0)
    
  - Merge "Add wifi_iot_tw test package1" am: ec63061434 am: 8faa8f58d3
    am: 638c6e2397
    
    Bug: 0
    Change-Id: I38b70775f299b15d932fc6c4ff8d07ff8caebabf
    (cherry picked from commit 970fa916a10c06e1191dcc310b5cef5354ad1186)
    
  - Merge "Add wifi RVR TW test" am: 61562a0da0 am: 19160b1453
    am: 4dcdf2f67c
    
    Bug: 0
    Change-Id: Ief4cfc61866bf6825da057defc2233689c987026
    (cherry picked from commit 19d7285ecdce6725d5265a8c0689e48d1ba97261)
    
  - [LegacyVpnTest] Error fix for LegacyVpnTest
    
    CHERRY PICKED FROM AOSP
    
    Bug: 109670497
    Test: Verified the changes
    Change-Id: Ifd1bf216599c6de7e60b22a4db93678e2c916b2a
    Merged-In: I0330799b03d6d7c44f4a72ccf818fe1f82706669
    
  - Fixes for core networking tests
    
    CHERRY PICKED MULTIPLE CHANGES FROM AOSP
    
    Bug: 109670497
    Test: Verified the changes
    Change-Id: I44741796d581b4216ed7e1ce15d1fdc679389394
    Merged-In: I650dcc8f94c385e9c19ada570c910e3d0ca60a02