Update git submodules
* Update external/jacoco from branch 'master'
  to 730cc2668f7a8e9ef614b7bccf4b1586e77f9e90
  - Mark installable jars with installable: true
    
    Most jars don't need to be installed on the device.  Instead of
    using java_library and java_library_static to distinguish between
    them make java_library and java_library_static identical and use
    installable: true to identify the few jars that need to be dexed
    and installed on the device.
    
    Bug: 110885583
    Test: m checkbuild
    Change-Id: Ief76c5d49eb2e534b86813196a961a2d6e759474
    
  - Merge tag 'v0.8.0' from 'aosp/upstream-master' into master.
    
    * 6a0c097f (tag: v0.8.0) Prepare release v0.8.0
    * b9d1b54e Happy New Year 2018!
    * 6f375769 Consolidate change log for 0.8.0 release (#632)
    * 0c50b210 Restore exec files compatibility regarding Java 9 class files (#636)
    * 7f7c246f Offline instrumentation should not damage module-info (#634)
    * e050f194 Instrumentation should not damage structured locking (#627)
    * 4c0b93e8 Fix ExecutionData.merge JavaDoc (#630)
    * ff001947 Add filter for duplicates of finally blocks (#604)
    * 00f06ecc Fix typos
    
    Bug: 69463998
    Test: m EMMA_INSTRUMENT=true EMMA_INSTRUMENT_FRAMEWORK=true SKIP_BOOT_JARS_CHECK=true WITH_DEXPREOPT=false tests
    Change-Id: I00f3079bdbb0618141b4414cac0b83dcf9c0c2d5
    
  - Prepare release v0.8.0
    
  - Happy New Year 2018!
    
  - Consolidate change log for 0.8.0 release (#632)
    
    
  - Restore exec files compatibility regarding Java 9 class files (#636)
    
    
  - Offline instrumentation should not damage module-info (#634)
    
    
  - Update build files for new version of jacoco
    
    Also remove asm-debug-all-5.0.1.jar in favor of the asm 6.0 prebuilts
    in prebuilts/misc/common/asm.
    
    Bug: 69669951
    Test: m EMMA_INSTRUMENT=true EMMA_INSTRUMENT_FRAMEWORK=true SKIP_BOOT_JARS_CHECK=true WITH_DEXPREOPT=false tests
    Change-Id: Idfda865afa9d3f40a388431aebee08455e4c8db8
    
  - Merge remote-tracking branch 'aosp/upstream-master' into master
    
    * e1502d10 Add build with JDK 10-ea
    * dd7809ac Cleanup AgentTest (#618)
    * 8f046096 Remove obsolete phase binding (#617)
    * cdd0ec17 Fix test that doesn't pass bytecode verification of Eclipse OpenJ9 JVM
    * 45223410 Use default environment in Travis instead of deprecated
    * caa820ed Upgrade ASM to 6.0 (#600)
    * ec6287a6 Add filter for methods annotated with @groovy.transform.Generated (#610)
    * 88d7b01d Fix test to not require additional settings on JDK 9 (#611)
    * bdfa45fe Add test of offline instrumentation of Java 9 module-info (#608)
    * 11ac0663 Document contract for In/OutputStream resources and fix example (#605)
    * 4d6ca957 Descriptive names for all tests in FrameSnapshotTest (#609)
    * 99244757 Add test of ASM bug 317792 (#607)
    * b060c251 Update links to ASM issues
    * e094d693 Add test of ASM bug 317793 (#606)
    * ac25a3f5 Apply naming convention and add missing tests
    * b19911c2 Suppress compiler warning
    * 1962cf59 Yak shaving: add ability to merge coverage of several instructions (#601)
    * aca2da1d Show in StringSwitchTest that filter works for complex expressions (#599)
    * 4109d66f Yak shaving: determine covered branches for each instruction (#598)
    * 04f923c1 Add filter for bytecode that javac generates for String in switch (#596)
    * 8cd32471 Happy birthday JDK 9!
    * 8a2822d1 Describe correct agent option in MBeanClient example (#582)
    * 4d08365f Add "--verbose" option to "classinfo" CLI command (#578)
    * 424251f1 Fix build in Travis
    * 90a1416c Fix build in Travis
    * 4b471ef7 Remove duplicate line from the file header
    * 4b7fd7cc Add link about integration of JaCoCo into Shippable (#579)
    * 5a745a38 Fix assertions for JDK 8 >= u152 (#576)
    * 765bf090 Remove unused SVN keyword "Id"
    * fcf9baf8 Remove unused MAVEN_OPTS
    * bb2ecb52 Add Artifact.SCOPE_PROVIDED artifacts to aggregate report (#572)
    * 86856fef Use proper exception type in documentation (#557)
    * 31575a30 For Java 9 add "Automatic-Module-Name" to manifests of JAR files (#565)
    * 98a2a41e Relocate 3rd party libs in CLI nodeps JAR (#561)
    * 63d375fd Fix build for JDK 9 >= b175 (#558)
    * c85fd2a4 Update documentation about Maven artifacts (#540)
    * 05a2aa7d Descriptor of jacoco-maven-plugin should include "help" mojo (#559)
    * c10af135 Reduce chance of conflict with other agents (#555)
    * 2a2f1619 Use dest argument as folder in any case (#543)
    *   817d0ae1 Merge pull request #541 from jacoco/issue-541
    |\
    | * 1b959434 Add location to IOException when unable to read stream during analysis
    |/
    * 13f12d39 Add Command Line Interface (#525)
    * 10f3ff0d ExecDumpClient should report error when no data is retrieved (#538)
    * 938b0b4e Merge pull request #536 from mattnelson/percentages
    * 129201d6 Update documentation for limit configuration as percent.
    * c39e3d26 create reusable parseValue method for ratio limits
    * d9caed9d Support limit ratios as percents
    
    Bug: 69669951
    Test: m EMMA_INSTRUMENT=true EMMA_INSTRUMENT_FRAMEWORK=true SKIP_BOOT_JARS_CHECK=true WITH_DEXPREOPT=false tests
    Change-Id: I484df66b7890b2b6d3d0d9401a60239a4a189260
    
  - Revert "Merge remote-tracking branch 'aosp/upstream-pull-525' into master"
    
    This reverts commit 369c1a464f4b750a0df7a750d5ab6bcc90202697, reversing
    changes made to ce2d33f3145d39d9e9aa6e8b59d409f803a13955.
    
    These changes are in upstream now, revert the manual merge to simplify
    merging upstream.
    
    Bug: 69669951
    Test: m EMMA_INSTRUMENT=true EMMA_INSTRUMENT_FRAMEWORK=true SKIP_BOOT_JARS_CHECK=true WITH_DEXPREOPT=false tests
    Change-Id: I120abed4c5913abc948b81116225d3969c039549
    
  - Instrumentation should not damage structured locking (#627)
    
    
  - Fix ExecutionData.merge JavaDoc (#630)
    
    Correctly describe the behavior of the 'flag' parameter for the 'false' case.
  - Add filter for duplicates of finally blocks (#604)
    
    
  - Fix typos
    
  - Add build with JDK 10-ea
    
  - Cleanup AgentTest (#618)
    
    * Don't write to file system
    * Avoid DNS lookups (slows down builds)
    * Use new test naming conventions
    
  - Remove obsolete phase binding (#617)
    
    Since version 0.6.2 the "report" goal is bound to phase "verify".
  - Fix test that doesn't pass bytecode verification of Eclipse OpenJ9 JVM
    
    "JVMCFRE107 offset out of range in jump bytecode"
    
  - Use default environment in Travis instead of deprecated
    
    * Ubuntu Trusty instead of Precise
    * Maven 3.5.0 (that uses Java 7)
      instead of Maven 3.2.5 (that was using Java 6)
    * OpenJDK 6 requires installation
    
  - Upgrade ASM to 6.0 (#600)
    
    
  - Add filter for methods annotated with @groovy.transform.Generated (#610)
    
    
  - Fix test to not require additional settings on JDK 9 (#611)
    
    
  - Add test of offline instrumentation of Java 9 module-info (#608)
    
    
  - Document contract for In/OutputStream resources and fix example (#605)
    
    
  - Fix coverage builds am: f4e43e6b7f am: 4bce1453ad
    am: 660d690b42
    
    Change-Id: Ic5b2cdef54410fe255744ac6f72866568fb17b75
    
  - Descriptive names for all tests in FrameSnapshotTest (#609)
    
    
  - Fix coverage builds am: f4e43e6b7f
    am: 4bce1453ad
    
    Change-Id: I1193b66443f893e03b1154e7826cd4c2199e65ec
    
  - Fix coverage builds
    am: f4e43e6b7f
    
    Change-Id: Ida2aa2395e4bfcb0e685bd4db3124903e625927b
    
  - Fix coverage builds
    
    jacocoagent is installed as its own library after
    I9e6e3dc59dba8b93685d59b258d4ebc7835eab8b, so it needs to be built
    non-static.
    
    Bug: 67578832
    Test: m -j EMMA_INSTRUMENT=true EMMA_INSTRUMENT_FRAMEWORK=true SKIP_BOOT_JARS_CHECK=true
    Change-Id: Ib81bbe50e0010ed77725e885fded6af1dc8b221d
    
  - Add test of ASM bug 317792 (#607)
    
    
  - Update links to ASM issues
    
  - Add test of ASM bug 317793 (#606)
    
    
  - Convert jacoco to Android.bp am: 919bf5c9b5 am: adffb95cd0
    am: 966432bdb5
    
    Change-Id: Ic9e9faa841398765c67f1b0f1d0da602af175a68
    
  - Convert jacoco to Android.bp am: 919bf5c9b5
    am: adffb95cd0
    
    Change-Id: Ia9d4eef42d8c369a4757791b9e0189b1b62f9109
    
  - Convert jacoco to Android.bp
    am: 919bf5c9b5
    
    Change-Id: Ib3fe098d7b720bcc04b5dd4318ad9f2e149e494e
    
  - Convert jacoco to Android.bp
    
    See build/soong/README.md for more information.
    
    Test: m -j checkbuild
    Change-Id: Id7bc214c9ceb127cb29a02f82975f01939701138
    
  - Apply naming convention and add missing tests
    
    
  - Suppress compiler warning
    
  - Yak shaving: add ability to merge coverage of several instructions (#601)
    
    This is required for implementation of filter of duplicate blocks that
    compilers generate for `finally`.
  - Show in StringSwitchTest that filter works for complex expressions (#599)
    
    
  - Yak shaving: determine covered branches for each instruction (#598)
    
    This is required for merge of coverage information from several
    instructions that cover different branches, which in his turn is
    required for implementation of filter of duplicate blocks that
    compilers generate for `finally`.
  - Add filter for bytecode that javac generates for String in switch (#596)
    
    
  - Happy birthday JDK 9!
    
  - Describe correct agent option in MBeanClient example (#582)
    
    
  - Add "--verbose" option to "classinfo" CLI command (#578)
    
    
  - Fix build in Travis
    
    Disable SonarQube analysis for the time being,
    its failure will be investigated later.
    
  - Fix build in Travis
    
    Starting from 1 September 2017 Travis defaults to "dist: trusty",
    on which our build currently fails, because new environment
    is quite different from previous "dist: precise".
    
  - Remove duplicate line from the file header
    
  - Add link about integration of JaCoCo into Shippable (#579)
    
    
  - Fix assertions for JDK 8 >= u152 (#576)
    
    
  - Remove unused SVN keyword "Id"
    
    These leftovers were forgotten in
    1b885c7bc666c215c3947ad4d12099273a5f533f
    
  - Remove unused MAVEN_OPTS
    
    Illegal reflective access is permitted in JDK 9 by default
    starting from b175.
    
  - Add Artifact.SCOPE_PROVIDED artifacts to aggregate report (#572)
    
    
  - Use proper exception type in documentation (#557)
    
    As the outermost exception seen by the user is actually
    NoClassDefFoundError the FAQ entry should also mention this type.
  - For Java 9 add "Automatic-Module-Name" to manifests of JAR files (#565)
    
    
  - Relocate 3rd party libs in CLI nodeps JAR (#561)
    
    
  - Fix build for JDK 9 >= b175 (#558)
    
    
  - Update documentation about Maven artifacts (#540)
    
    
  - Descriptor of jacoco-maven-plugin should include "help" mojo (#559)
    
    
  - Reduce chance of conflict with other agents (#555)
    
    
  - Merge "Revert "Move WildcardMatcher into new 'matcher' package"" am: b1b164ac86 am: 9ef5ef62ba am: 626019de32
    am: 7501f6096c
    
    Change-Id: I848da9940449f2eff0d3d137465a92e54915f87e
    
  - Merge "Revert "Move WildcardMatcher into new 'matcher' package"" am: b1b164ac86 am: 9ef5ef62ba
    am: 626019de32
    
    Change-Id: I52320896e1d4372f16798f19f89ff172bebd1a2c
    
  - Merge "Revert "Move WildcardMatcher into new 'matcher' package"" am: b1b164ac86
    am: 9ef5ef62ba
    
    Change-Id: Ia5767fe31f24dc097eb8419cf1eba39cd55e0e2b
    
  - Merge "Revert "Move WildcardMatcher into new 'matcher' package""
    am: b1b164ac86
    
    Change-Id: I9336148cbd509a33e3c47f16e20d720308faf39f
    
  - Merge "Revert "Move WildcardMatcher into new 'matcher' package""
  - Merge "Copy jacoco-cli into dist directory" am: de8d9e2abf am: 8087f52bc1 am: 32e58fc7f2
    am: f1cd912745
    
    Change-Id: Ie8ab6caf76590ef929813c44a22eda2f8a96ea75
    
  - Merge "Copy jacoco-cli into dist directory" am: de8d9e2abf am: 8087f52bc1
    am: 32e58fc7f2
    
    Change-Id: Ie49ba3aa70ca2d3e800091a0ecac1b47c2bfe7e8
    
  - Merge "Copy jacoco-cli into dist directory" am: de8d9e2abf
    am: 8087f52bc1
    
    Change-Id: If3296c04441a51367b60fe90776f29894be3d19e
    
  - Merge "Copy jacoco-cli into dist directory"
    am: de8d9e2abf
    
    Change-Id: If1eea61aa72954bd58dce1772c8725e2900a2031
    
  - Merge "Copy jacoco-cli into dist directory"
  - Copy jacoco-cli into dist directory
    
    Test: m -j ANDROID_COMPILE_WITH_JACK=false EMMA_INSTRUMENT=true dist && stat out/dist/jacoco-cli.jar
    Bug: 36792868
    Change-Id: Ifa3a235a09ee586109e6fa7fa1df5045d870ab8b
    
  - Revert "Add ClassnameMatcher in preparation to pass into Instrumenter for filtering" am: 10750c3a7c am: 293b0ecef8 am: 5b45722f6d
    am: 702534bdee
    
    Change-Id: I14e4182b0b7cdab0ed4529b128b08927fc71d5ac
    
  - Revert "Add ClassnameMatcher in preparation to pass into Instrumenter for filtering" am: 10750c3a7c am: 293b0ecef8
    am: 5b45722f6d
    
    Change-Id: Ieb2e04a5d9304a9974f804a697d91f67b330998e
    
  - Revert "Add ClassnameMatcher in preparation to pass into Instrumenter for filtering" am: 10750c3a7c
    am: 293b0ecef8
    
    Change-Id: I13832b72e33db16f9eb54805c2d6ded296091de6
    
  - Revert "Add ClassnameMatcher in preparation to pass into Instrumenter for filtering"
    am: 10750c3a7c
    
    Change-Id: Ibd53085aaf03b90cffad9a0c30ddeb9e035dbd04
    
  - Revert "Move WildcardMatcher into new 'matcher' package"
    
    This reverts commit 8da25e49bc72ec3a2455080c53c0dc2006decd7d.
    
    Reason for revert: moving filtering out of Jacoco and into Make
    
    Change-Id: I976ae531b8bdd15b87c4c7fcfb1899d379bbc929
    
  - Revert "Add ClassnameMatcher in preparation to pass into Instrumenter for filtering"
    
    This reverts commit bbe2e9a9b2c9f829bc5e906c218244205c5bfbab.
    
    Reason for revert: moving filtering out of Jacoco and into Make
    
    Change-Id: I58b9c4eb1fc6d6984cf7cb4b9dd74bdbcf4f8956
    
  - Add ClassnameMatcher in preparation to pass into Instrumenter for filtering am: bbe2e9a9b2 am: 99916bb64e am: 3969781f7e
    am: 1442ac24eb
    
    Change-Id: Idaf9214f456c6c3ca73fb10c926786b8d10b4713
    
  - Move WildcardMatcher into new 'matcher' package am: 8da25e49bc am: 7e0c218b10 am: 1629a3f7ee
    am: c417e0b029
    
    Change-Id: I7810eabccde985fb4a4d7e4214c8db85fe836894
    
  - Some build updates for latest jacoco am: 4ed39e392f am: ff54e096d9 am: ea41174f5b
    am: 284e516a05
    
    Change-Id: I87667990d0f870eba98568211297c6273655fa77
    
  - Add ClassnameMatcher in preparation to pass into Instrumenter for filtering am: bbe2e9a9b2 am: 99916bb64e
    am: 3969781f7e
    
    Change-Id: I8f0655c4b4fd3c870dd55e38c1d5abc4b96d4893
    
  - Move WildcardMatcher into new 'matcher' package am: 8da25e49bc am: 7e0c218b10
    am: 1629a3f7ee
    
    Change-Id: Ia6657fe903c65278a266ae96d6af2aec66885197
    
  - Some build updates for latest jacoco am: 4ed39e392f am: ff54e096d9
    am: ea41174f5b
    
    Change-Id: Iae05be1f439e3bf105362b52ce7fff7e40fde136
    
  - Add ClassnameMatcher in preparation to pass into Instrumenter for filtering am: bbe2e9a9b2
    am: 99916bb64e
    
    Change-Id: I1f943c736dd87267cdf41829e889ef86d2ec0f46
    
  - Move WildcardMatcher into new 'matcher' package am: 8da25e49bc
    am: 7e0c218b10
    
    Change-Id: Iec17bfff6556af0e6198c0f060497dd6517e62e7
    
  - Some build updates for latest jacoco am: 4ed39e392f
    am: ff54e096d9
    
    Change-Id: I1567aaccc67ec31de76176f6d3e5eca025b19f34
    
  - Add ClassnameMatcher in preparation to pass into Instrumenter for filtering
    am: bbe2e9a9b2
    
    Change-Id: I97371bbfb8e51a1d4569d5ae7e847012a5309e9c
    
  - Move WildcardMatcher into new 'matcher' package
    am: 8da25e49bc
    
    Change-Id: I6cc3210ceb6fbadf57486b80b09eb307556c4f8f
    
  - Some build updates for latest jacoco
    am: 4ed39e392f
    
    Change-Id: I71f138841ca2541c529d50ff045b397b91fa43a2
    
  - Add ClassnameMatcher in preparation to pass into Instrumenter for filtering
    
    Change-Id: I17f66e03a2ae2d2177132e54ffb14815c24b4f13
    
  - Move WildcardMatcher into new 'matcher' package
    
    Change-Id: If7997e60d9fbcc53c297793530eeafa97b38d7ee
    
  - Some build updates for latest jacoco
    
    Bug: 36792868
    Test: m -j
    Change-Id: I817d12994bc795be3faa33ad7e63675e3072a88e
    
  - Use dest argument as folder in any case (#543)
    
    The instrument goal accepts folders as well as files as input. In case
    of files the instrumented copy should be written to the folder given as
    the dest option.
  - Merge pull request #541 from jacoco/issue-541
    
    Method Analyzer.analyzeClass(InputStream, String) as others should provide context information when unable to read input during analysis
  - Add location to IOException when unable to read stream during analysis
    
  - Add Command Line Interface (#525)
    
    
  - ExecDumpClient should report error when no data is retrieved (#538)
    
    
  - Merge remote-tracking branch 'aosp/upstream-pull-525' into master am: 369c1a464f am: f3a4bd65a4 am: b55f07b186
    am: b59ce01d2c
    
    Change-Id: I3c476a20363a35f1f740c118cacd4b8e97266b5e
    
  - Merge remote-tracking branch 'aosp/upstream-pull-525' into master am: 369c1a464f am: f3a4bd65a4
    am: b55f07b186
    
    Change-Id: I9105995c6444471020e08ac13cb0cb9d8ea25da0
    
  - Merge remote-tracking branch 'aosp/upstream-pull-525' into master am: 369c1a464f
    am: f3a4bd65a4
    
    Change-Id: I48f46ab181f7a8fe8076d5fcf74a443cdd88df17
    
  - Merge remote-tracking branch 'aosp/upstream-pull-525' into master
    am: 369c1a464f
    
    Change-Id: I61602ba0fa444a68a874ef8700ab26fb919abd56
    
  - Merge remote-tracking branch 'aosp/upstream-master' into master am: ce2d33f314 am: 3af440b397 am: 371076c25f
    am: a9fc8b70a6
    
    Change-Id: Ib6bd0292793f33259e9ea5b3376bccab72d29551
    
  - Merge remote-tracking branch 'aosp/upstream-master' into master am: ce2d33f314 am: 3af440b397
    am: 371076c25f
    
    Change-Id: Ib9d0ce99d3e2666dc55e1a6804041baa8e5d6c8e
    
  - Merge remote-tracking branch 'aosp/upstream-master' into master am: ce2d33f314
    am: 3af440b397
    
    Change-Id: I9a300409c76209e68111dd56fce24e4fac2fed05
    
  - Merge remote-tracking branch 'aosp/upstream-master' into master
    am: ce2d33f314
    
    Change-Id: I65e795ce209836dac9e2902be72a88d6ff2db5a5
    
  - Merge pull request #536 from mattnelson/percentages
    
    Support limit ratios as percents (#534)
  - Update documentation for limit configuration as percent.
  - create reusable parseValue method for ratio limits
    
  - Support limit ratios as percents
    
  - Change default OutputMode to none. am: 36e54806ed am: 3a3f5bfe34 am: 5d36c93ed0
    am: b6ba640a06
    
    Change-Id: If6edd498b4caf239e7516ced9bee8b8549c20e99
    
  - Merge \"Change default OutputMode to none. am: 6d4519ee21 am: 91eff0693d\" into nyc-mr1-dev-plus-aosp
    am: 82b3571954
    
    Change-Id: I423ccc8a1a8e359dc4d398cbb87cc2cd4b1cadaa
    
  - Change default OutputMode to none. am: 6d4519ee21 am: cdbeda382b
    am: 7d8c8dc6d3
    
    Change-Id: I249dc5c911c5e4b621aaa870808e6c990bc85791
    
  - Build jacoco from sources am: 831c256
    am: fffb4a0
    
    * commit 'fffb4a0d28c2696f86545b663b38d4f9715a5396':
      Build jacoco from sources
    
    Change-Id: I92e9b6140f4b18b61ea517a7841f5d476fc7d532
    
  - Build jacoco from sources am: 8d9dc82 am: 2cf7f93
    am: 6d80a3d
    
    * commit '6d80a3dfc9fc1f4f0323943f632d3c43a18b4473':
      Build jacoco from sources
    
    Change-Id: If9a22bedadc9117447cc1b301e1a4891bbbaa5b2