Update git submodules
* Update external/rust/crates/quote from branch 'master'
  to b027b17e08e552f1a51f6eafd1cec4598b3b03cb
  - Merge branch '0.6.13'
    
    Change-Id: Ibdb7c7fed2a9362c5d4dc53c8e2a873e393856dc
    
  - Release 0.6.13
    
  - Simplify is_ident function (#104)
    
    It's a way over-complicated
  - Smaller format for license section
    
  - Switch to SPDX 2.1 license expression
    
  - Update tests for new proc-macro2 escape behavior
    
  - Release 0.6.12
    
  - Merge pull request #102 from eddyb/rc
    
    Support Rc<T> in ToTokens.
  - Support Rc<T> in ToTokens.
    
  - Format with rustfmt 2018-12-10
    
  - Adjust indentation of quote macro rules
    
  - Move runtime support to its own module
    
  - Add benchmark of a representative impl
    
  - Document limitations of interpolation in a repetition
    
  - Release 0.6.11
    
  - Port examples from readme to rustdoc
    
  - Clarify example on making method calls
    
  - Clarify example on manipulating identifiers
    
  - Clarify example on combining fragments
    
  - Explain how to return tokens to the compiler
    
  - Update doc tests to 2018 edition
    
  - Move TokenStreamExt documentation to trait methods
    
  - Use PhantomData from libcore in examples
    
  - Extern crate is no longer needed in readme
    
  - Merge pull request #93 from SoftwareApe/master
    
    Added some helpful examples of special behaviors #92
  - Added some helpful examples of special behaviors.
    
    Added some examples to readme where it's difficult to use quote!, cases where I spent some time figuring out how to use it.
  - Release 0.6.10
    
  - Merge pull request #87 from dtolnay/integer128
    
    Support i128 and u128 to tokens
  - Hide unsupported integer suffixes from rustc 1.15
    
  - Support i128 and u128 to tokens
    
  - Release 0.6.9
    
  - Merge pull request #84 from rkarp/patch-1
    
    Add crate category
  - Add crate category
  - Release 0.6.8
    
  - Merge pull request #78 from dtolnay/local
    
    Use local_inner_macros to resolve all helper macros within $crate
  - Use local_inner_macros to resolve all helper macros within $crate
    
    This fixes the following error when using Rust 2018 style macro imports.
    
        use quote::quote;
    
        error: cannot find macro `quote_spanned!` in this scope
         --> src/main.rs:4:5
          |
        4 | /     quote! {
        5 | |     }
          | |_____^
    
    The `local_inner_macros` modifier resolves all macro invocations made
    from within that macro as helpers in the same crate. So if `quote!`
    expands to an invocation of `quote_spanned!` then this would be resolved
    as `$crate::quote_spanned!` rather than requiring the caller to have
    `quote_spanned` in scope.
    
    The attribute is ignored by pre-2018 compilers so quote will continue to
    work as normal with #[macro_use].
    
    In the future when dropping compatibility with pre-2018 compilers we can
    remove the `local_inner_macros` modifier and use our own explicit
    `$crate::` prefixes on invocations of helper macros.
    
  - Bump proc-macro2 requirement
    
    This is to ensure that quote continues to work with `-Z
    minimal-versions`. The 0.4.13 version of proc-macro2 adds
    `Extend<TokenStream> for TokenStream` which we use.
    
  - Clearer impl to append a single token
    
  - Optimize impl ToTokens for TokenStream
    
  - Release 0.6.7
    
  - Format with rustfmt 0.99.2
    
  - Merge pull request #77 from dtolnay/opt
    
    Performance optimizations
  - Remove useless into-conversions
    
  - Implement a fast path for idents
    
  - Recognize ident tokens
    
    FIXME: this does not work on compilers older than 1.20.0 due to a
    parsing ambiguity.
    
  - Recognize specific punctuations
    
  - Release 0.6.6
    
  - Merge pull request #76 from lukaslueg/master
    
    Ignore proc-macro feature on wasm-target
  - Ignore proc-macro feature on wasm-target
    
  - Display a Travis badge on crates.io
    
  - Release 0.6.5
    
  - ToTokens for &mut T
    
  - Update Serde snippet to 1.0 api
    
  - Release 0.6.4
    
  - Clarify that many different types can be interpolated
    
  - Build minimal versions in Travis
    
  - Release 0.6.3
    
  - Merge pull request #74 from hcpl/replace-deprecated
    
    Replace `TokenStream::empty` with `TokenStream::new`
  - Replace `TokenStream::empty` with `::new`
    
    `TokenStream::empty` is deprecated since `proc-macro2` 0.4.4.
    
  - Release 0.6.2
    
  - Quote has been updated to call_site by default
    
  - Update link to proc-macro2 Span API
    
  - Link to release notes
    
  - Release 0.6.1
    
  - Eliminate references to Tokens
    
  - Release 0.6.0
    
  - Add back a proc-macro dependency in case we find we need it
    
  - Merge pull request #73 from alexcrichton/next
    
    Update to proc-macro2 0.4
  - Brief explanation of TokenStreamExt trait
    
  - Format with rustfmt 0.7.0
    
  - Seal the TokenStreamExt trait
    
  - Move TokenStreamExt trait to ext.rs
    
  - Remove references to quote/proc-macro feature
    
  - Optimize into_token_stream for TokenStream
    
    This optimization used to be in the impl ToTokens for Tokens.
    
  - Prepare for the next proc-macro2 release
    
    Depends on alexcrichton/proc-macro2#90
    
  - Format example code in rustfmt style
    
  - Link to some limitations
    
  - Release 0.5.2
    
  - Implement ToTokens for proc_macro2::Op, Group
    
  - Release 0.5.1
    
  - Include readme metadata in Cargo.toml
    
  - Release 0.5.0
    
  - Format with rustfmt 0.4.1
    
  - Merge pull request #62 from staktrace/standalone
    
    Add proc-macro feature to control the runtime dependency on rustc toolchain libs
  - Add a feature for linking to proc_macro.
    
    This feature is enabled by default for backwards compatibility, but
    it can be disabled in order to break the runtime dependency on
    the dynamic library libproc_macro in the rustc toolchain.
    
  - Merge pull request #66 from alexcrichton/v3
    
    Update to the proc-macro2 0.3.0 branch
  - Update to the proc-macro2 0.3.0 branch
    
  - Document why quote_spanned should be formatted the way we recommend
    
  - Release 0.4.2
    
  - Merge pull request #59 from mystor/tt_eq_hash
    
    Implement Hash and PartialEq for quote::Tokens
  - Implement Hash and PartialEq for quote::Tokens
    
  - Release 0.4.1
    
  - Implement IntoIterator for Tokens
    
    This allows a Tokens to be passed to Tokens::append_all.
    
        tokens.append_all(quote!(...));
    
  - Release 0.4.0
    
  - Upgrade to proc-macro2 0.2
    
  - Set html_root_url
    
  - Readme for quote 0.4
    
  - Doc tweaks
    
  - Crate-level documentation
    
  - Tokens documentation
    
  - Implement ToTokens for TokenNode
    
  - Implement ToTokens for Literal
    
  - Default for Tokens can be derived
    
  - Organize ToTokens implementations
    
  - Remove ByteStr
    
    Users can now build a `Literal::byte_string(bytes)` and interpolate that.
    
  - ToTokens documentation
    
  - Fix doc tests for rust 1.15.1 build
    
  - Document quote_spanned macro
    
  - Document quote macro
    
  - Less subtle quote_spanned delimiter
    
  - Reduce surface area of Tokens
    
  - Make the realistic example compile
    
  - Use rust highlighting now that it has been fixed
    
  - Unignore the extern crate example
    
  - Fix ToTokens::to_tokens example code
    
  - Hide __rt module from documentation
    
  - Hex literal support no longer exists
    
  - Format with rustfmt 0.3.4-nightly
    
  - Resolve clippy lints
    
  - Merge pull request #57 from dtolnay/debug
    
    Implement Debug for Tokens
  - Implement Debug for Tokens
    
  - Merge pull request #56 from dtolnay/remove
    
    Remove ToTokens for vec, slice, arrays
  - Remove ToTokens for vec, slice, arrays
    
    These make it too easy to write code that compiles but
    does not do what you wanted, when you meant to write a
    repetition. Users should write out the repetition
    themselves.
    
        quote! { [ #(#vec,)* ] }
    
  - Merge pull request #55 from alexcrichton/quote-spanned
    
    Add a `quote_spanned!` macro
  - Add a `quote_spanned!` macro
    
    This commit adds a new `quote_spanned!` macro which works the same as `quote!`
    except that it takes a span as an argument to attach to all tokens that are
    generated as part of the quoting process.
    
  - Merge pull request #47 from alexcrichton/none
    
    Support emitting the `None` delimiter
  - Support emitting the `None` delimiter
    
  - Link to page with slides
    
  - Merge pull request #40 from alexcrichton/more-from
    
    Add `From<Tokens> for proc_macro::Tokens`
  - Add `From<Tokens> for proc_macro::Tokens`
    
  - Revert "Add convertion from `Token` to `proc_macro::Tokens`"
    
    This reverts commit 3b20d7f88f5e21dd5806964a295e5b1b14ab999e.
    
  - Add convertion from `Token` to `proc_macro::Tokens`
    
  - Update to published `proc_macro2`
    
  - Fix conflicts between PR 36 and PR 37
    
  - Merge pull request 36 from mystor/into_tokens
    
    Conflicts:
        src/to_tokens.rs
    
  - Fix quote! with looks-like-an-attribute
    
  - Fix a typo in quote!
    
  - Disable publish until proc-macro2 is figured out
    
  - Merge pull request #37 from alexcrichton/new-tokens
    
    Update to operate with proc-macro2 tokens
  - Rewrite to work with `proc_macro2` tokens
    
    This should allow quasi-quoting to hopefully work much more closely with the
    final revision of the `proc_macro` api.
    
  - Remove `impl_to_tokens_display!` as it has only 1 user now
    
  - Add `ToTokens::into_tokens` to conveniently convert `ToTokens` types into `Tokens` objects
    
  - Mention that this is like macro_rules
    
  - Merge pull request #34 from torkleyy/patch-1
    
    Document trailing comma in README
  - Document trailing comma in README
  - Nice work @asajeffrey
    
  - Release 0.3.15
    
  - Simplify the example quotes
    
  - Consistent name for the separator type parameter
    
  - Merge pull request #29 from colin-kiegel/feature/append_tokens_to_tokens
    
    append tokens to tokens
  - append tokens to tokens
    
    implement #12 via `impl AsRef<str> for Tokens`
    
  - Release 0.3.14
    
  - Merge pull request #28 from SimonSapin/into_string
    
    Add Tokens::into_string
  - Add Tokens::into_string
    
    Tokens::as_str doesn’t work for returning the contents of a `Tokens`
    created in that function.
    
  - Release 0.3.13
    
  - Include readme, licenses, tests in crates.io archive
    
    Fixes #26.
    
  - Release 0.3.12
    
  - ToTokens for Cow
    
  - Release 0.3.11
    
  - Byte strings use byte escapes not unicode escapes
    
  - Clarify recursion_limit requirement
    
  - More explanation in readme
    
  - Remove workaround for rust 1.11.0
    
  - Run tests against rust 1.13.0
    
  - Implement ToTokens for ()
    
  - 1.11.0 fails for another reason
    
    ```
    error: internal compiler error: ../src/librustc_trans/expr.rs:907: trans_var: no datum
    note: the compiler unexpectedly panicked. this is a bug.
    note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/
    thread 'rustc' panicked at 'Box<Any>', ../src/librustc_errors/lib.rs:619
    ```
    
  - Release 0.3.10
    
  - Support old rustc
    
  - Doc comment for Ident
    
  - Use as_str in tests
    
  - Release 0.3.9
    
  - Clarify the readme version
    
  - Merge pull request #19 from SimonSapin/hex
    
    Add a Hex wrapper for integer type, with a ToTokens impl using `{:X}`.
  - Merge pull request #18 from SimonSapin/lit
    
    Implement ToTokens as literals for arrays, tuples, slices, and Vec.
  - Merge pull request #17 from SimonSapin/ident
    
    Add Ident.
  - Add a Hex wrapper for integer type, with a ToTokens impl using `{:X}`.
    
    This doesn’t make a difference when rustc is parsing generated code,
    but sometimes humans need to look at that code for debugging
    and bit-packed values are much more readable in hexadecimal than decimal.
    
  - Implement ToTokens as literals for arrays, tuples, slices, and Vec.
    
    This is consistent with the existing impls for String and str
    that produce string literal syntax.
    
    Slices and Vec use array literal syntax, a `&` or `vec!` prefix
    needs to be added explicitly.
    
    Arrays and tuples have impls up to 32 and 12 members, respectively.
    This uses the same macros to generate impls as `libcore` does internally.
    
  - Add Ident.
    
    When using quote without syn to generate code in a build script,
    this is useful to synthesize identifiers in the generated code.
    
    (Quoting &str or String produces a string literal.)
    
  - Release 0.3.8
    
  - Add Tokens::parse
    
  - Release 0.3.7
    
  - Mention as_str() in documentation
    
  - Document quote!(...) sort of
    
  - Document Tokens
    
  - Document ToTokens
    
  - Document ByteStr
    
  - Crate-level rustdoc
    
  - Link to docs.rs for the rustdocs
    
  - Crate description
    
  - Merge pull request #16 from dtolnay/str
    
    Expose tokens as &str
  - Expose tokens as &str
    
  - Release 0.3.6
    
  - Allow quoting references to dynamically sized types
    
  - Mention recursion limit in readme
    
  - Re-brand
    
  - Release 0.3.5
    
  - Simplify representation of zero char inside strings
    
  - Simplify representation of the zero char
    
  - Adjust Travis build
    
  - Release 0.3.4
    
  - No need for empty [dependencies] section
    
  - Allow equality comparison of Tokens
    
  - More distinct rustdoc shield
    
  - Document quote::Tokens
    
  - Document multiple interpolations in a repetition
    
  - Release 0.3.3
    
  - Merge pull request #9 from mystor/less-spaces
    
    Avoid appending empty tokens
  - Avoid appending empty tokens
    
    This is useful as it eliminates extra spaces which are created when
    appending an empty Tokens object with `to_tokens()`.
    
  - Release 0.3.2
    
  - Merge pull request #6 from mystor/empty-quote
    
    Add support for passing no tokens to quote!()
  - Add support for passing no tokens to quote!()
    
  - Release 0.3.1
    
  - Merge pull request #5 from mystor/less-spaces
    
    Avoid extra unnecessary spaces in the tokens string
  - Add "syn" as crates.io keyword
    
  - Avoid extra unnecessary spaces in the tokens string
    
  - Underscore the loop variable
    
  - Add test for duplicate token
    
  - Bump version in readme
    
  - Release 0.3.0
    
  - Empty repetition is empty
    
  - Release 0.3.0-rc2
    
  - Do not quote \" and \' unnecessarily
    
  - Merge pull request #3 from dtolnay/rep
    
    Fancy repetition
  - Comment the helper macros
    
  - Fancy repetition
    
  - ToTokens for char
    
  - Release 0.2.3
    
  - Loop helpers
    
  - Release v0.2.2
    
  - Allow values other than vec to be used in repeaters
    
    Since we were always borrowing the value before iterating over it,
    repetitions essentially required `T where for<'a> &'a T: IntoIterator`,
    which is pretty much only true for `Vec`. By default we now own values
    passed into a repetition. `&ident` is valid as a way to retain the old
    behavior, but it's also usually easy to just get a reference elsewhere
    since the value must be assigned to a local variable.
    
  - Release 0.2.1
    
  - ToTokens for Box<T>
    
  - Release 0.2.0
    
  - Include type information when quoting numbers
    
  - Release 0.1.4
    
  - Merge pull request #1 from hauleth/patch-1
    
    Allow cloning `Tokens`
  - Allow cloning `Tokens`
  - Release 0.1.3
    
  - Add ByteStr token
    
  - Release 0.1.2
    
  - ToTokens for String
    
  - Handle outer attributes
    
  - Add documentation link
    
  - Add Travis build
    
  - Release 0.1.1
    
  - Add append_separated
    
  - Cargo metadata
    
  - quote!