Update git submodules
* Update external/flatbuffers from branch 'master'
  to 6b23ef32f8ae912762a7bdc8dc1f30b8d25e7eeb
  - Upgrade flatbuffers to b2ce86ef8aef9a9caa8bcc99e54591b92d7b2426
    
    Test: build
    Change-Id: If01d786a479d0f2f186fb0e1f98d0fe84c390202
    
  - Add compile-time checking of numerical limits in C++ code. (#5270)
    
    * Add checking of numerical_limits<T> in C++ code.
    
    * Add integer suffixes (LL/ULL) to int64 values in the IntegerBoundaryTest
    
  - Update grammar to reflect required type signature for enum declarations. (#5269)
    
    
  - Add missing test data file to BUILD file (#5264)
    
    $ cat
    /home/austin/.cache/bazel/_bazel_austin/4b3182bfa237d7e256d9f18ffe58322f/execroot/com_github_google_flatbuffers/bazel-out/k8-opt/testlogs/flatbuffers_test/test.log
    exec ${PAGER:-/usr/bin/less} "$0" || exit 1
    Executing tests from //:flatbuffers_test
    -----------------------------------------------------------------------------
    VALUE: "0"
    EXPECTED: "1"
    TEST FAILED: tests/test.cpp:2029, flatbuffers::LoadFile( (test_data_path
    + "union_vector/union_vector.json").c_str(), false, &jsonfile) in
    VALUE: "0"
    EXPECTED: "1"
    TEST FAILED: tests/test.cpp:2100, parser.Parse(jsonfile.c_str()) in
    VALUE: "0"
    EXPECTED: "1"
    TEST FAILED: tests/test.cpp:2103, VerifyMovieBuffer(jverifier) in
  - Bazel CI: fix bad value in yml (#5262)
    
    Use the "simple format" defined here:
    https://github.com/bazelbuild/continuous-integration/blob/69cf7ec23d984dcbb41fffe946e07ebf5ab7e0f1/buildkite/bazelci.py#L1453
    
    This will unbreak the "Bazel / FlatBuffers"
    pipeline on Bazel CI, see
    https://buildkite.com/bazel/flatbuffers
  - Fix a warning on compiling with clang (#5258)
    
    
  - Add inequality operator (inspired from #263) (#5257)
    
    
  - [C++] Changes in the flathash program (#5255)
    
    * Correct the usage in the flathash program
    
    As it is possible to have -- before the occurrence of the first
    input STRING.
    
    * Exit with 1 in the flathash program when an error occurs
    
  - Fixed tutorial markdown file (#5248)
    
    Path specified in tutorial file was pointing to invalid location.
  - Further fixes to make minireflect compatible with old behavior.
    
    Change-Id: I92c257ec4ab4a0cf4676bd98523b766ce25bf4f6
    
  - Unify line ending rules in '.editorconfig' and '.gitattributes' (#5231)
    
    * Unify line ending rules in '.editorconfig' and '.gitattributes'
    
    * Revert '.gitattributes'
    
    - fix invalid comments in the check-source.py
    
  - Fixed vector_delimited excluding delimiter
    
    Change-Id: I3e758d44b9845d6df91332bb609b4b7ad88659ac
    
  - Fixed shadowing warning in older gcc for vector_delimited
    
    Change-Id: Ia4d56a5eb086f86eb5d1ad6ddae64e4a51bf3aa3
    
  - Made ToStringVisitor backwards compatible with older behavior.
    
    This to support code that relied on tables being multiline,
    but not vectors.
    
    This behavior was changed in:
    https://github.com/google/flatbuffers/commit/b1a925dfc2ac78508aee89029e950057405f0a0a#diff-c45c8fbffbc64f7ff4aa2978612b10d8
    
    Change-Id: I4c95471b643b2b3fab95e06b1294e19d686b492c
    
  - Made JS enum declarations compatible with google closure
    
    Original change by: https://github.com/alexames
    
    Change-Id: Ib65bd02156d1c3637ed278a8334a2307caacaa44
    
  - Disabled constexpr for hashing functions.
    
    This was incompatible with -Wc++98-c++11-compat on some platforms,
    due to local variables in the function.
    
    Change-Id: Idef510c2cefe944eef2e0656f5a219c2158063e6
    
  - Narrows template ascii routines to prevent a possible signed overflow in generic code. (#5232)
    
    
  - Fix typo in dart documentation (#5230)
    
    
  - [C++] Object API: document custom string type requirements,
    
    implement better custom string type constructor alternative
    for Unpack() and fix bug with vector of custom string types
    in Pack().
    
    Squashed commit of the following:
    
    commit e9519c647ef949b22756ed660839dd3af854881c
    Author: Luca Longinotti <luca.longinotti@inivation.com>
    Date:   Tue Mar 5 18:24:49 2019 +0100
    
        tests: regenerate code, reverts change to CreateVectorOfStrings().
    
    commit 117e3b0679209f2aa55cbee18c4036e7da4bd4b3
    Author: Luca Longinotti <luca.longinotti@inivation.com>
    Date:   Tue Mar 5 18:15:05 2019 +0100
    
        idl_gen_cpp.cpp: move clang-format on/off outside of declaration, so they are kept properly aligned automatically.
    
    commit 4791923806965637d5b13f7003329bfbb2fdf18b
    Author: Luca Longinotti <luca.longinotti@inivation.com>
    Date:   Tue Mar 5 18:11:40 2019 +0100
    
        idl_gen_cpp.cpp: full clang-format run with provided Google format file, enforce 80 lines width.
    
    commit 2f0402f9ff43b1af0a29806932e08e6d64373345
    Author: Luca Longinotti <luca.longinotti@inivation.com>
    Date:   Tue Mar 5 18:09:32 2019 +0100
    
        CppUsage: address requested changes.
        idl_gen_cpp.cpp: fix formatting, keep CreateVectorOfStrings for normal string cases.
    
    commit 371d4e0b7972a59e5cff418c44e4043c016ce56a
    Author: Luca Longinotti <luca.longinotti@inivation.com>
    Date:   Fri Mar 1 16:35:29 2019 +0100
    
        Fix compile error with a vector of non-std::strings. CreateVectorOfStrings() expects a vector of std::string types, but that's not always the case.
    
    commit 92b90d7f0fbcfc837a94aa06bedccec0f7b4bb62
    Author: Luca Longinotti <luca.longinotti@inivation.com>
    Date:   Fri Mar 1 16:15:36 2019 +0100
    
        Document requirement for custom string types to implement empty() and be constructible from std::string.
        Add new option --cpp-str-flex-ctor to construct custom string types not via std::string, but (char * + length).
    
    commit 28cb2e92d5b7684b5df5184da3a3fad2d0cda733
    Author: Luca Longinotti <luca.longinotti@inivation.com>
    Date:   Fri Mar 1 14:31:17 2019 +0100
    
        idl_gen_cpp.cpp: clang-format run, to better separate changes in content from formatting.
    
    Change-Id: I4887ba2f2c632b9e7a8c938659b088cd95690870
    
  - [Rust] Don't use inner attributes for `allow` (#5212)
    
    * Don't use inner attributes for `allow`
    Messes with being able to easily include elsewhere
    
    * Regenerate tests
    
    * No-op to retrigger CI
    
    * Add the rest of the `allow` attributes
    
  - Small usability tweaks to the rust codegen. (#5213)
    
    
  - Fix rust crate for big-endian targets (#5229)
    
    Thanks for tackling this, @tymcauley !
    
    * big endian docker test -- wip
    
    * tweaks
    
    * tweaks
    
    * tweaks
    
    * docker tweaks
    
    * fix conditional compilation issues
    
    * reactivate other docker tests
    
    * try some more cross-platform config (from tymcauley)
    
    * Update tests/docker/languages/Dockerfile.testing.rust.big_endian.1_30_1
    
    Co-Authored-By: rw <rw@users.noreply.github.com>
    
    * Update tests/docker/languages/Dockerfile.testing.rust.big_endian.1_30_1
    
    Co-Authored-By: rw <rw@users.noreply.github.com>
    
    * Update tests/docker/languages/Dockerfile.testing.rust.big_endian.1_30_1
    
    Co-Authored-By: rw <rw@users.noreply.github.com>
    
    * Resolved Rust warnings during big-endian builds.
    
    * Unify Rust test suites for x86 and MIPS builds.
    
    Note that I had to add four extra packages to the MIPS `Dockerfile`:
    `libexpat1`, `libmagic1`, `libmpdec2`, and `libreadline7`. For a reason
    I couldn't identify, even the simplest Rust MIPS binaries run with
    `qemu-mips` would fail with a segfault when run through this
    `Dockerfile`. After installing the `gdb-multiarch` package to attempt to
    debug the issue, the binaries ran successfully. I pared down the
    packages installed by `gdb-multiarch`, and these four packages are the
    minimum subset necessary to get Rust MIPS binaries running under
    `qemu-mips`.
    
    * Changed Rust tests to use `Vector`s instead of direct-slice-access.
    
    The direct-slice-access method is not available on big-endian targets,
    but `flatbuffers::Vector`s provide an array interface that is available
    on all platforms.
    
    * Resolved FooStruct endianness issues using explicit struct constructor.
    
    This more closely resembles how FlatBuffers structs are constructed in
    generated Rust code.
    
    * Added explanation of how `FooStruct` parallels generated struct code.
    
    Also collected duplicate implementations of `FooStruct` into a common
    location.
    
  - Removed -Wc++98-compat-extra-semi for compatibility with older clang.
    
    Change-Id: I6dfadb5289a4396ad2f3d16baf1bdb99c7534174
    
  - Bazel ci (#5228)
    
    * Stop building for Windows until the build passes
    
    ERROR: D:/b/bk-windows-java8-bd0z/bazel/flatbuffers/BUILD:123:1: Couldn't build file _objs/flatbuffers_test/test.obj: undeclared inclusion(s) in rule '//:flatbuffers_test':
    this rule is missing dependency declarations for the following files included by 'tests/test.cpp':
      'tests/monster_test_generated.h'
      'tests/monster_extra_generated.h'
    
    The files in tests are being found instead of the generated files since
    Windows doesn't have any sandboxing.  For now, let's disable the rules
    and come back to it.
    
    * Fix buildifier warnings
    
    Clean up docstrings and add a module docstring.
    
  - Fixed vector of union JSON parsing.
    
    This for some reason never had a test case, and was broken.
    
    Change-Id: If832f5eb8b6c5ba8a75257464892634b38719c55
    
  - [Rust] Fixed codegen documentation for Tables (#5227)
    
    
  - [Go] Add mutation functions for vector elements (#5221)
    
    Fixes #5206