Update git submodules
* Update external/selinux from branch 'master'
  to 1633b76f8a15ccc0de5d40ce8ca2848059abc66a
  - Merge remote-tracking branch 'aosp/upstream-master' into mymerge
    
    Followed the following steps:
      # In repo client
      cd external/selinux
      repo sync .
      repo start mymerge .
      git merge aosp/upstream-master --no-ff # resolve any conflicts
      repo upload .
    
    Test: device boots and no obvious problems.
    Change-Id: I6beff804808e92d1002ead226c7d5c702f373cdc
    
  - restorecond: Install DBUS service file with 644 permissions
    
    The original 600 permissions make the service file unreadable for dbus daemon.
    
    Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1626462
    
    Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
    
  - Update VERSIONs to 2.9-rc1 for release.
    
    Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
    
  - scripts: introduce env_use_destdir.sh helper
    
    Set-up environment variables in order to use DESTDIR in Python, Ruby,
    etc. This makes testing Python scripts easier.
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - Travis-CI: add Ruby 2.6 to the test matrix
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - Travis-CI: upgrade PyPy to 6.0
    
    PyPy 6.0 was released in April 2018 but became available on Travis-CI
    only recently. Now that it is available, use it.
    
    While at it, compile Python modules with libpypy-c.so, now that PyPy
    provides this library. This would enable linking Python modules with
    -Wl,-no-undefined (or -Wl,-z,defs) and help fixing issues with
    https://github.com/SELinuxProject/selinux/pull/130.
    
    Tracking issues:
    * https://github.com/travis-ci/travis-ci/issues/9542
    * https://travis-ci.community/t/pypy-2-7-on-xenial/889
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - libselinux/audit2why.so: Filter out non-python related symbols
    
    audit2why.so used to export libsepol.a symbols. We only need Python related
    symbols:
    
    - initaudit2why for python 2
    - PyInit_audit2why for python3
    
    Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
    
  - libselinux: do not dereference symlink with statfs in selinux_restorecon
    
    When selinux_restorecon() is used to relabel symlinks, it performs the
    following syscalls (as seen by running strace on restorecond):
    
        lstat("/root/symlink", {st_mode=S_IFLNK|0777, st_size=6, ...}) = 0
        statfs("/root/symlink", 0x7ffd6bb4d090) = -1 ENOENT (No such file or directory)
        lstat("/root/symlink", {st_mode=S_IFLNK|0777, st_size=6, ...}) = 0
        lgetxattr("/root/symlink", "security.selinux", "sysadm_u:object_r:user_home_t", 255) = 30
    
    The second one triggers a SELinux check for lnk_file:read, as statfs()
    dereferences symbolic links. This call to statfs() is only used to find
    out whether "restoreconlast" xattr can be ignored, which is always the
    case for non-directory files (the first syscall, lstat(), is actually
    used to perform this check).
    
    Skip the call to statfs() when setrestoreconlast is already false.
    
    This silences an AVC denial that would otherwise be reported to
    audit.log (cf. https://github.com/SELinuxProject/refpolicy/pull/22).
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - setsebool: support use of -P on SELinux-disabled hosts
    
    As reported in #123, setsebool immediately exits with an error if
    SELinux is disabled, preventing its use for setting boolean persistent
    values.  In contrast, semanage boolean -m works on SELinux-disabled
    hosts.  Change setsebool so that it can be used with the -P option
    (persistent changes) even if SELinux is disabled.  In the SELinux-disabled
    case, skip setting of active boolean values, but set the persistent value
    in the policy store.  Policy reload is automatically disabled by libsemanage
    when SELinux is disabled, so we only need to call semanage_set_reload()
    if -N was used.
    
    Fixes: https://github.com/SELinuxProject/selinux/issues/123
    Signed-off-by: Stephen Smalley <sds@tycho.nsa.gov>
    
  - python/sepolicy: initialize mislabeled_files in __init__()
    
    Using "sepolicy gui" sometimes leads to an exception when entering the
    Files tab:
    
        Traceback (most recent call last):
          File "python/sepolicy/sepolicy/gui.py", line 1345, in tab_change
            self.show_mislabeled_files_only.set_visible(self.mislabeled_files)
        AttributeError: 'SELinuxGui' object has no attribute 'mislabeled_files'
    
    Indeed, when application_selected() calls show_applications_page(), this
    function calls tab_change(), which can use mislabeled_files in this
    line:
    
        self.show_mislabeled_files_only.set_visible(self.mislabeled_files)
    
    Make sure that mislabeled_files is initialized by defining it in
    __init__(), in order to fix this error. Its value will be properly set
    later, by calling several initializers, which is why the original
    assignment to False is kept in:
    
        self.mislabeled_files = False
        self.executable_files_initialize(app)
        self.network_initialize(app)
        self.writable_files_initialize(app)
        self.transitions_into_initialize(app)
        self.transitions_from_initialize(app)
        self.application_files_initialize(app)
        self.transitions_files_initialize(app)
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - libsemanage: set selinux policy root around calls to selinux_boolean_sub
    
    As reported in #109, semodule -p /path/to/policyroot -s minimum -n -B
    tries to use /etc/selinux/targeted/booleans.subs_dist.  This is because
    it invokes the libselinux selinux_boolean_sub() interface, which uses
    the active/installed policy files rather than the libsemanage ones.
    
    Switch the selinux policy root around the selinux_boolean_sub() call
    to incorporate the semanage root as a prefix and to use the specified
    policy store as a suffix so that the correct booleans.subs_dist file
    (if any) is used.
    
    The underlying bug is that booleans.subs_dist is not itself managed
    via libsemanage. If it was managed and therefore lived within the
    policy store, then libsemanage could access the appropriate
    booleans.subs_dist file without using the libselinux interface at all,
    and thus would not need to modify the selinux policy root.  Moving
    booleans.subs_dist to a managed file is deferred to a future change.
    
    Test:
    dnf install selinux-policy-minimum selinux-policy-targeted
    cd / && tar cf - etc/selinux var/lib/selinux | (cd ~/policy-root; tar xvpf -)
    strace semodule -p ~/policy-root -s minimum -n -B
    
    Before:
    openat(AT_FDCWD, "/etc/selinux/targeted/booleans.subs_dist", O_RDONLY|O_CLOEXEC) = 5
    
    After:
    openat(AT_FDCWD, "/home/sds/policy-root/etc/selinux/minimum/booleans.subs_dist", O_RDONLY|O_CLOEXEC) = 5
    
    Fixes https://github.com/SELinuxProject/selinux/issues/109
    
    Signed-off-by: Stephen Smalley <sds@tycho.nsa.gov>
    
  - scripts/run-flake8: run on Python scripts not ending with .py
    
    When running flake8 on a directory, it does not analyze files without an
    extension, like semanage_migrate_store, mlscolor-test, etc. Use grep to
    find files with a Python shebang and build a list which is then given to
    flake8.
    
    This commit is possible now that some clean-up patches have been
    applied, such as commit 69c56bd2f6e9 ("python/chcat: improve the code
    readability") and b7227aaec1da ("mcstrans: fix Python linter warnings on
    test scripts") and 3cb974d2d2a7 ("semanage_migrate_store: fix many
    Python linter warnings").
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - python: run all the tests with "make test"
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - python/sepolgen: refpolicy installs its Makefile in include/Makefile
    
    When running "make install-headers" on refpolicy,
    /usr/share/selinux/refpolicy/Makefile does not exist but
    /usr/share/selinux/refpolicy/include/Makefile does. Use it when
    available.
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - python/audit2allow: use local sepolgen-ifgen-attr-helper for tests
    
    Introduce option --attr-helper to sepolgen-ifgen to make it possible to
    override /usr/bin/sepolgen-ifgen-attr-helper and use it in the testuite
    in order to test the helper which has been compiled from the project
    instead of the one installed on the system.
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - python/audit2allow: make the tests useful again
    
    audit2allow testsuite requires a system which uses SELinux with a MLS
    policy. This is a lot to ask for a continuous integretation system.
    Thankfully this can be worked around by using option -p to run the tools
    with a specific configuration. Doing this, the testsuite can even be run
    on a system without SELinux.
    
    This approach requires building a custom policy for parsing test.log.
    Add a minimal policy written in CIL for this need.
    
    While at it:
    * Do not invoke "sudo sepolgen-ifgen" but produce a file in a writable
      directory (instead of /var/lib/sepolgen/interface_info)
    * Use sys.executable instead of 'python', in order to really test
      python3 and python2 when calling the test script with one of these
      interpreters.
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - Travis-CI: download refpolicy and install headers
    
    This is needed in order to run sepolgen-ifgen in audit2allow testsuite.
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>