Update git submodules
* Update external/autotest from branch 'master'
  to 09ed7a5548a09133ed46b13d23bf0474ac828f52
  - crash: improve error message for unknown files
    am: 7f854db22f
    
    Change-Id: I8a560658f9473cd97ad8eb7f601d0b631d12ed87
    
  - crash: improve error message for unknown files
    
    The UserCrashTest._run_crasher_process_and_analyze helper goes through
    the crash spool directory and makes sure all files created with reports
    are known/expected.  If it finds any it doesn't know about, it fails.
    
    Unfortunately, the "unknown file" code path is geared towards a failure
    mode that no longer really comes up: it assumes that if a file is new,
    it's because breakpad itself created a minidump and left it behind.  So
    any time crash-reporter creates a new file, we get the confusing error:
      ERROR: crasher_nobreakpad did generate breakpad minidump
    It doesn't tell us what this new file is (could be a log file), and the
    grammar being slightly broken adds to the confusion.
    
    Further, if crash-reporter creates two new files, we get the error:
      ERROR: Breakpad wrote multiple minidumps
    Which doesn't make sense if crash-reporter is creating logs and not any
    breakpad related files.
    
    Lets nuke all this special case logic and just add a generic "unknown
    file" whenever we see files we don't expect.  Now we'll get an explicit
    error about the file that we don't handle:
      ERROR: Crash reporter created an unknown file: crasher_nobreakpad.20181023.131230.12664.proclog
    
    BUG=chromium:889552
    TEST=`test_that ... logging_UserCrash` still passes, and writes a better error message w/CL:1296089
    
    Change-Id: Ieedd59b8b21264e669da4df18a96ac8773dace1e
    Reviewed-on: https://chromium-review.googlesource.com/1297191
    Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
    Commit-Ready: Mike Frysinger <vapier@chromium.org>
    Tested-by: Mike Frysinger <vapier@chromium.org>
    Reviewed-by: Ben Chan <benchan@chromium.org>