Update git submodules
* Update tools/asuite from branch 'master'
  to dd74a4beb6372f50e28c023249ffea3a5ebcdd32
  - Merge "AIDEGen: Refactor the solution of aosp/959753."
  - AIDEGen: Refactor the solution of aosp/959753.
    
    Pass IDE mapping name of representative charater args.ide[0] instead of
    ide_util_obj.ide_name() to multi_projects_locate_source() function to
    determine which IDE's ModuleData should be collected.
    
    Bug: 132402810
    Test: 1.m aidegen; aidegen-dev framework -n
          2.aidegen-dev framework -n -i e
            It shouldn't show exception:
    	AttributeError: 'NoneType' object has no attribute 'ide_name'
    	For step 2, .classpath and .project file will be created in
    	frameworks/base folder.
    
    Change-Id: I94a7f4bdd213bba988f02472b11ee0ac848cc44b