Update git submodules
* Update external/llvm from branch 'lldb-master-dev'
  to 2fbf253c00fd3a3f243ddceb3398fa012460612e
  - Merge "[VFS] Implement `RedirectingFileSystem::getRealPath`. am: f8ecfaae82" into lldb-master-dev
  - [VFS] Implement `RedirectingFileSystem::getRealPath`.
    am: f8ecfaae82
    
    Change-Id: I5dff5a07ff7a344a77bc81bbca46b9d118410dea
    
  - [VFS] Implement `RedirectingFileSystem::getRealPath`.
    
    It fixes the case when Objective-C framework is added as a subframework
    through a symlink. When parent framework infers a module map and fails
    to detect a symlink, it would add a subframework as a submodule. And
    when we parse module map for the subframework, we would encounter an
    error like
    
    > error: umbrella for module 'WithSubframework.Foo' already covers this directory
    
    By implementing `getRealPath` "an egregious but useful hack" in
    `ModuleMap::inferFrameworkModule` works as expected.
    
    rdar://problem/45821279
    
    Reviewers: bruno, benlangmuir, erik.pilkington
    
    Reviewed By: bruno
    
    Subscribers: hiraditya, dexonsmith, JDevlieghere, cfe-commits, llvm-commits
    
    Differential Revision: https://reviews.llvm.org/D54245
    
    
    
    git-svn-id: https://llvm.org/svn/llvm-project/llvm/trunk@347009 91177308-0d34-0410-b5e6-96231b3b80d8