Update git submodules
* Update external/autotest from branch 'master'
  to f59cee51caf12717a6d2c3f990a92cede1b43777
  - video_Jpeg{Decode, Encode}Accelerator: Remove args_dict out of control files
    am: 67203549a9
    
    Change-Id: I38efd5e96bf09fd6e802170b49c2ae2aca374440
    
  - video_Jpeg{Decode, Encode}Accelerator: Remove args_dict out of control files
    
    When tests are run locally by test_that, tests failed with an error
    "Unhandled TypeError: run_once() got an unexpected keyword argument 'servo_host'".
    This is caused by passing **args_dict in arguments in control files.
    This removes it in order to enable to run the tests locally.
    
    Commit title and message borrowed from Hirokazu's original submission.
    https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/1331195/
    
    BUG=None
    TEST=Verify JPEG accelerator tests pass.
         `test_that --board=${BOARD} ${DUT_IP} e:video_Jpeg.*Accelerator`
    
    Change-Id: Ib3fb07b9696745170d757337061247a3fd0a4040
    Signed-off-by: Edward Baker <edward.baker@intel.com>
    Reviewed-on: https://chromium-review.googlesource.com/1354378
    Tested-by: Casey G Bowman <casey.g.bowman@intel.com>
    Reviewed-by: Hirokazu Honda <hiroh@chromium.org>