Update git submodules
* Update build/soong from branch 'master'
  to 604374742d1230ddae984728310cefd5711ea43f
  - Merge "Revert "Remove product_is_iot.""
  - Revert "Remove product_is_iot."
    
    This reverts commit 14fa562fbbd89fabc5806734cdaadcdd2e4a577a.
    
    Reason for revert: Broken build on 5772180
    
    error: frameworks/av/media/utils/Android.bp:49:23: unrecognized property "product_variables.product_is_iot"
    
    Bug: 138764596
    Change-Id: I37944dfb974e4180a683361f514b404f92b943e5