Update git submodules
* Update cts from branch 'master'
  to ae6291f54af160232bec414287af4c12d0a72f50
  - Merge "Add TFLite NNAPI delegate tests to CTS"
  - Add TFLite NNAPI delegate tests to CTS
    
    Bug: 124643616
    Test: atest CtsTfliteNnapiDelegateTestCases --rebuild-module-info
    Change-Id: I823a3071b4e45c5bf00a84334793347339f1cfa4
    Merged-In: I823a3071b4e45c5bf00a84334793347339f1cfa4
    (cherry picked from commit 3f4a53e1af2d6d5fcd2d077440fd7fa38ca84b6c)
    

* Update external/tensorflow from branch 'master'
  to f6a21794519bbc1963536c2ef2e27f4e124f73a7
  - Merge changes from topic "tflite-nnapi-delegate-cts"
    
    * changes:
      Add presubmit tests for the NNAPI delegate
      Fix compilation problems when running nnapi_delegate_test as part of CTS
    
  - Add presubmit tests for the NNAPI delegate
    
    Bug: 124643616
    Test: atest
    Change-Id: I065e6ec5d312f9efe6ae3e4933fbe9412216f2aa
    Merged-In: I065e6ec5d312f9efe6ae3e4933fbe9412216f2aa
    (cherry picked from commit 97841695e680974f1e6510563aceb05aa992ce22)
    
  - Fix compilation problems when running nnapi_delegate_test as part of CTS
    
    This fixes the following two problems:
    
    1.
        In file included from external/tensorflow/tensorflow/lite/kernels/test_util.h:30:
        external/tensorflow/tensorflow/lite/testing/util.h:21:10: fatal error: 'tensorflow/lite/string.h' file not found
        #include "tensorflow/lite/string.h"
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
    
    2.
        ld.lld: error: undefined symbol: testing::internal::FormatMatcherDescription(bool, char const*, std::__ndk1::vector<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::allocator<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > > > const&)
        >>> referenced by nnapi_delegate_test.cc:34 (external/tensorflow//tensorflow/lite/delegates/nnapi/nnapi_delegate_test.cc:34)
        >>>               nnapi_delegate_test.o:(tflite::(anonymous namespace)::QuantizedNearMatcher::gmock_Impl<std::__ndk1::tuple<unsigned char const&, int const&> >::DescribeTo(std::__ndk1::basic_ostream<char, std::__ndk1::char_traits<char> >*) const) in archive out/target/product/crosshatch/obj_arm/STATIC_LIBRARIES/CtsTfliteNnapiDelegateTests_static_intermediates/CtsTfliteNnapiDelegateTests_static.a
    
    Bug: 130342510
    Bug: 124643616
    Test: mma CtsTfliteNnapiDelegateTests_static (with change I823a3071b4e45c5bf00a84334793347339f1cfa4)
    Change-Id: I2a3126794de8f30bd80e0a55b075fd21a201a738
    Merged-In: I2a3126794de8f30bd80e0a55b075fd21a201a738
    (cherry picked from commit 010ba1628251195c57afba368b556098c173c049)
    

* Update frameworks/ml from branch 'master'
  to c3380df293fe40fb51b8e92b5dee7aa74d88d45d
  - Merge "Add TFLite delegate tests to TEST_MAPPING"
  - Add TFLite delegate tests to TEST_MAPPING
    
    Bug: 124643616
    Test: atest
    Change-Id: Ib377c50f6bd6bb9e973074337320157ab3f9115d
    Merged-In: Ib377c50f6bd6bb9e973074337320157ab3f9115d
    (cherry picked from commit f07606179fade025925fbe816d397e8eb22d727c)