Update git submodules
* Update external/clang from branch 'lldb-master-dev'
  to 0ef3a2644cb1656b37ed4e25305fd4afff7cda13
  - Merge "Removed unused variable [NFC] am: e6df27459b" into lldb-master-dev
  - Removed unused variable [NFC]
    am: e6df27459b
    
    Change-Id: I1ee00682ee68e60bac3e8f8b3603d3d398747cf7
    
  - Removed unused variable [NFC]
    
    The compiler warned:
    ../tools/clang/lib/StaticAnalyzer/Core/RetainSummaryManager.cpp:329:19: error: unused variable 'MD' [-Werror,-Wunused-variable]
      if (const auto *MD = dyn_cast<CXXMethodDecl>(FD)) {
                      ^
    1 error generated.
    
    git-svn-id: https://llvm.org/svn/llvm-project/cfe/trunk@340524 91177308-0d34-0410-b5e6-96231b3b80d8