Update git submodules
* Update external/clang from branch 'lldb-master-dev'
  to ab1d6883ec6b16df90fcc3f260ca14cdce751fa6
  - Merge "Revert "[analyzer] [NFC] Split up RetainSummaryManager from RetainCountChecker" am: e6554b83e1" into lldb-master-dev
  - Revert "[analyzer] [NFC] Split up RetainSummaryManager from RetainCountChecker"
    am: e6554b83e1
    
    Change-Id: Ie8175971871f128dc2f18674e70e49d1aec0fac4
    
  - Revert "[analyzer] [NFC] Split up RetainSummaryManager from RetainCountChecker"
    
    This reverts commit a786521fa66c72edd308baff0c08961b6d964fb1.
    
    Bots haven't caught up yet, but broke modules build with:
    
    ../tools/clang/include/clang/StaticAnalyzer/Checkers/MPIFunctionClassifier.h:18:10:
    fatal error: cyclic dependency in module 'Clang_StaticAnalyzer_Core':
    Clang_StaticAnalyzer_Core -> Clang_Analysis ->
    Clang_StaticAnalyzer_Checkers -> Clang_StaticAnalyzer_Core
             ^
    
    git-svn-id: https://llvm.org/svn/llvm-project/cfe/trunk@340117 91177308-0d34-0410-b5e6-96231b3b80d8