Update git submodules
* Update external/selinux from branch 'master'
  to 72ba6b43698b6488ce8f2d0a1f84282bf5d181d5
  - Merge remote-tracking branch 'aosp/upstream-master' into manualmerge
    
    In particular, this merges in
    https://github.com/SELinuxProject/selinux/pull/99 , which makes Android
    builds quieter.
    
    Followed the following steps:
    
      # In repo client
      cd external/selinux
      repo sync .
      repo start mymerge .
      git merge aosp/upstream-master --no-ff # resolve any conflicts
      repo upload .
    
    Test: compiles/boots no problems.
    Bug: 115998215
    Change-Id: I0be55971cfc0c18722ff0ac755864b1b4b6657e0
    
  - checkpolicy: remove extraneous policy build noise
    
    Reduce noise when calling the checkpolicy command line. In Android, this
    creates unnecessary build noise which we'd like to avoid.
    
    https://en.wikipedia.org/wiki/Unix_philosophy
    
      Rule of Silence
      Developers should design programs so that they do not print
      unnecessary output. This rule aims to allow other programs
      and developers to pick out the information they need from a
      program's output without having to parse verbosity.
    
    An alternative approach would be to add a -s (silent) option to these
    tools, or to have the Android build system redirect stdout to /dev/null.
    
    Signed-off-by: Nick Kralevich <nnk@google.com>
    
  - checkpolicy: check the result value of hashtable_search
    
    Signed-off-by: liwugang <liwugang@xiaomi.com>
    
  - semanage: add a missing space in ibendport help
    
    Currently, in:
    
        # semanage ibendport --help
        usage: semanage ibendport [-h] [-n] [-N] [-s STORE] [ --add -t TYPE
        -z IBDEV_NAME -r RANGE ( port ) | --delete -z IBDEV_NAME -r RANGE(
        port ) | --deleteall  | --extract  | --list -C | --modify -t TYPE -z
        IBDEV_NAME -r RANGE ( port ) ]
    
    ... a space is missing between "RANGE" and "( port )" in the usage of
    --delete. Add it by splitting the string correctly in the usage line
    definition.
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - semanage: "semanage user" does not use -s, fix documentation
    
    Both "semanage user --help" and "man 8 semanage-user" state that
    "semanage user" accepts option -s, but this is incorrect: -s is not
    needed to specify the SELinux user on the command line, contrary to
    "semanage login" for example. Fix the documention.
    
    While at it, remove many spaces from the helptext of option --roles. I
    do not know where they came from, but they were reduced to a single
    space when displayed anyway.
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - libsemanage: use previous seuser when getting the previous name
    
    I missed this bug in commit 9ec0ea143ab5 ("libsemanage: use previous
    seuser when getting the previous name").
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - libsemanage: Include user name in ROLE_REMOVE audit events
    
    Use "previous" user name when no new user is available in
    semanage_seuser_audit. Otherwise "id=0" is logged instead of
    "acct=user_name" ("id=0" is hard coded value).
    
    Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1622045
    
  - Fix build break around __atomic_*() with GCC<4.7
    
    The __atomic_* GCC primitives were introduced in GCC 4.7, but Red Hat
    Enterprise Linux 6.x (for example) provides GCC 4.4. Tweak the current code to
    use the (most conservative) __sync_synchronize() primitive provided by those
    older GCC versions.
    
    Fixes https://github.com/SELinuxProject/selinux/issues/97
    
    (Really, no __atomic or __sync operations are needed here at all, since POSIX
    4.12 "Memory Synchronization" says pthread_mutex_lock() and
    pthread_mutex_unlock() "synchronize memory with respect to other threads"...)
    
  - libsemanage: reset umask before creating directories
    
    Restrictive umask may cause creating directories with with unintended
    access mode. Reset umask before creating directories to avoid this
    issue.
    
    Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1186422
    
    Signed-off-by: Vit Mojzis <vmojzis@redhat.com>
    
  - python: remove semicolon from end of lines
    
    Python does not need to end a statement with a semicolon. Doing this
    gets reported by linters such as flake8 ("E703 statement ends with a
    semicolon").
    
    Remove such semicolons in the code and enable this warning in
    scripts/run-flake8.
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - Travis-CI: upgrade to Ubuntu 16.04 LTS Xenial Xerus
    
    Ubuntu 14.04 uses SWIG 2.0.11 which produces Python files which contain
    lines ending with a semicolon:
    
        __del__ = lambda self : None;
    
    Ubuntu 16.04 uses SWIG 3.0.8, which does not put a semicolon. Moreover
    Travis CI only support Python 3.7 with Ubuntu 16.04. The reason for this
    is clearly stated on
    https://docs.travis-ci.com/user/languages/python/#development-releases-support :
    
        Recent Python branches require OpenSSL 1.0.2+. As this library is
        not available for Trusty, 3.7, 3.7-dev, 3.8-dev, and nightly do not
        work (or use outdated archive).
    
    Enabling Python 3.7 in Travis CI build matrix is therefore another
    reason to upgrade .travis.yml to Ubuntu 16.04. As this new template does
    not support Python 3.4 nor 3.5, and does not support PyPy2.7 yet, drop
    them from the build matrix.
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - libselinux: add a const to suppress a build warning with Python 3.7
    
    On systems using Python 3.7, when compiling libselinux Python wrappers
    (with "make install-pywrap"), the following warning is reported by gcc:
    
        audit2why.c: In function ‘analyze’:
        audit2why.c:364:11: warning: assignment discards ‘const’ qualifier
        from pointer target type [-Wdiscarded-qualifiers]
           permstr = _PyUnicode_AsString( strObj );
                   ^
    
    Make permstr "const char *" in order to suppress this warning.
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - libsemanage: make pywrap-test.py compatible with Python 3
    
    This program can be useful in order to test the Python API of
    libsemanage. Make it usable in Python 3 using 2to3 and some tweaks.
    
    While at it, fix warnings reported by flake8 linter.
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - libsemanage: reindent pywrap-test.py with spaces
    
    Only use spaces to indent Python code. This reduces the number of
    warnings reported by Python linters.
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - Travis-CI: run flake8 on Python code
    
    flake8 is a Python linter which is able to detect issues in Python code
    (syntax errors, undefined variables, etc.). It has been used to find
    bugs in the project. In order to prevent the introduction of new bugs
    which can be detected by it, add a script which runs it and use it in
    Travis-CI.
    
    flake8 can be used to detect code which is not written according to PEP8
    style guide (which forbids whitespaces in some places, enforces the use
    of space-indenting, specifies how many blank lines are used between
    functions, etc.). As SELinux code does not follow this style guide,
    scripts/run-flake8 disables many warnings related to this when running
    the linter.
    
    In order to silence flake8 warnings, the Python code can also be
    modified. However fixing every "do not use bare 'except'" in the project
    needs to be done carefully and takes much time.
    This is why the warnings which are disabled have been ordered in three
    lists:
    * The warnings which can be activated in a not-so-distant future after
      the code has been modified.
    * The warnings related to PEP8 which cannot be activated without a major
      cleaning work of the codebase (for example to modify white spaces)
    * The warnings which are introduced by code generated by SWIG 3.0.12,
      which would require patches in SWIG in order to be activated (there
      is right now only one such warning).
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - python/sepolicy: add missing % in network tab help text
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - python/sepolicy: do not import types
    
    This module is not used and its name conflicts with variable "types".
    
    This issue has been found using flake8. This Python linter reported:
    
        python/sepolicy/sepolicy/generate.py:657:5: F811 redefinition of
        unused 'types' from line 31
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - python/sepolicy: do not import sepolicy.generate.DAEMON twice
    
    This issue has been found using flake8. This Python linter reported:
    
        python/sepolicy/sepolicy.py:582:5: F811 redefinition of unused
        'DAEMON' from line 582
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - python/sepolicy: use variables which exist in the gui.py
    
    Some function used variables which were not defined when populating
    self.cur_dict with an operation. Fix this, even though the old values do
    not seem to be used.
    
    This issue has been found using flake8. This Python linter reported:
    
        python/sepolicy/sepolicy/gui.py:2020:101: F821 undefined name 'oldsetype'
        python/sepolicy/sepolicy/gui.py:2020:122: F821 undefined name 'oldmls'
        python/sepolicy/sepolicy/gui.py:2020:142: F821 undefined name 'oldclass'
        python/sepolicy/sepolicy/gui.py:2050:133: F821 undefined name 'oldmls'
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - python/sepolicy: fix "procotol" misspelling
    
    procotol -> protocol
    
    This issue has been found using flake8. This Python linter reported:
    
        python/sepolicy/sepolicy/gui.py:2525:132: F821 undefined name 'procotol'
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - python/sepolgen: use self when accessing members in FilesystemUse
    
    This silences the following flake8 errors:
    
        python/sepolgen/src/sepolgen/refpolicy.py:758:25: F821 undefined name 'XATTR'
        python/sepolgen/src/sepolgen/refpolicy.py:760:27: F821 undefined name 'TRANS'
        python/sepolgen/src/sepolgen/refpolicy.py:762:27: F821 undefined name 'TASK'
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - python/sepolgen: remove buggy code
    
    av_extract_params() may call __param_insert() with only 2 parameters
    instead of 4, which has no chance to work fine. Moreover it uses "PERM",
    which is undefined. As nobody complained about this code, it seems to be
    dead, so remove it.
    
    This issue has been found using flake8. This Python linter reported:
    
        python/sepolgen/src/sepolgen/interfaces.py:158:37: F821 undefined
        name 'PERM'
    
    While at it, fix a typo in a comment.
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - python/sepolgen: silence linter warning about has_key
    
    flake8 warns about using has_key():
    
        python/sepolgen/src/sepolgen/refparser.py:315:15: W601 .has_key() is
        deprecated, use 'in'
    
    However "spt.has_key(id)" uses function SupportMacros.has_key(), which
    is not the same as the "in" operator. Silence this warning by using "#
    noqa".
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - python/sepolgen: fix refpolicy parsing of "permissive"
    
    p_permissive() uses an undefined variable t, which is buggy. In order to
    ignore permissive statements, the function only needs to "pass".
    
    flake8 reported the following error:
    
        python/sepolgen/src/sepolgen/refparser.py:789:5: F821 undefined name 't'
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - python/sepolicy: use lowercase variable name
    
    SELinuxGui.files_initial_data_insert() uses both "seLinux_label" and
    "selinux_label", which leads to using an undefined variable, as reported
    by flake8:
    
        python/sepolicy/sepolicy/gui.py:1191:42: F821 undefined name 'selinux_label'
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - python/sepolicy: drop unused CheckPolicyType
    
    CheckPolicyType class is not used in sepolicy and has been written from
    an buggy copy-paste: "newval.append(v)" does not make any sense in
    CheckPolicyType.__call__, as reported by flake8:
    
        python/sepolicy/sepolicy.py:190:13: F821 undefined name 'newval'
        python/sepolicy/sepolicy.py:190:27: F821 undefined name 'v'
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - python/sepolgen: return NotImplemented instead of raising it
    
    sepolgen uses "return NotImplemented" (in access.py and matching.py) in
    order to make Python's sorting function use an other call to compare
    objects. For this to work, "NotImplemented" needs to be returned, not
    raised like _compare's default implementation does.
    
    This issue has been found using flake8. This Python linter reported:
    
        python/sepolgen/src/sepolgen/util.py:128:9: F901 'raise
        NotImplemented' should be 'raise NotImplementedError'
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - python/sepolgen: do not import twice the modules
    
    util.py starts by importing "locale" and "sys", so there is no need to
    import these modules again in the functions.
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - libselinux: fix flake8 warnings in SWIG-generated code
    
    flake8, a Python linter, complains:
    
        libselinux/src/selinux.py:100:1: F401 'errno' imported but unused
        libselinux/src/selinux.py:100:1: F401 'stat' imported but unused
        libselinux/src/selinux.py:100:14: E401 multiple imports on one line
        libselinux/src/selinux.py:130:16: E111 indentation is not a multiple of four
        libselinux/src/selinux.py:130:45: E231 missing whitespace after ','
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>