Update git submodules
* Update system/core from branch 'master'
  to 28fb130cbbd7c01ef706d5b6a5a9877b290f275c
  - Merge "Revert "libsparse: Add sparse typed callback""
  - Revert "libsparse: Add sparse typed callback"
    
    This reverts commit db69f0d47f3ccb3ff656c56fe2b68aaf5ab853f6.
    
    Reason for revert: Broke the build:
    
    In file included from system/core/libsparse/sparse.cpp:26:
    system/core/libsparse/output_file.h:34:72: error: unknown type name 'off64_t'; did you mean 'off_t'?
    int (*skip_write)(void*, off64_t), void* priv,
    ^~~~~~~
    off_t
    /Applications/Xcode6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/sys/_types/_off_t.h:30:25: note: 'off_t' declared here
    typedef __darwin_off_t off_t;
    ^
    1 error generated.
    
    Bug: 78793464
    Change-Id: I0f8bc4e9aa2f74612bfd8721d00d961e3f7e695f