Update git submodules
* Update system/core from branch 'pie-cuttlefish-testing'
  to 03fecb6220666c4019253b57f25dc33544887244
  - Merge "Fix two clang-tidy issues in crasher.cpp." into pie-cuttlefish-testing
  - Fix two clang-tidy issues in crasher.cpp.
    
    --------------------------
    pie-cuttlefish-testing broke on ASAN due to errors in the crasher
    binary. Cherry-picking in the fix from master system/core
    
    out/soong/.intermediates/system/core/debuggerd/crasher/crasher/
    android_x86_core_asan/obj/system/core/debuggerd/crasher/crasher.o
    system/core/debuggerd/crasher/crasher.cpp system/core/debuggerd/
    crasher/crasher.cpp:260:9: error: use of undeclared identifier
    '__read_chk' __read_chk(-1, buf, 32, 10);
    --------------------------
    
    TEMP_FAILURE_RETRY's result was unused for the call to read(), so now
    mark it as such to silence a possible unused result warning. For
    __read_chk(), this function is an internal implementation detail of
    FORTIFY in Bionic. Under clang-tidy, FORTIFY checks are actually
    removed, so this now results in an unknown function being called. The
    code should not be explicitly depending on an implementation detail, but
    we can just suppress the failing case to retain test coverage of the
    actual implementation.
    
    Bug: http://b/110779387
    Test: Build using WITH_TIDY=1
    Change-Id: If83ac1d6f3b6dc32c0d0fb56d8e675e53b586f78