Update git submodules
* Update external/f2fs-tools from branch 'master'
  to 19766b680b2ebe63cd8b85915458923c883aa287
  - Merge remote-tracking branch 'aosp/upstream-master' into update
    
    * aosp/upstream-master:
      fsck.f2fs: update curseg .next_blkoff/.alloc_type preferential
      fsck.f2fs: introduce check_curseg_offsets()
      f2fs-tools: relocate chksum_offset for large_nat_bitmap feature
      f2fs-tools: allow unfixed f2fs_checkpoint.checksum_offset
      fsck.f2fs: fix to repair cp_loads blocks at correct position
      sload.f2fs: introduce f2fs_sparse_initialize_meta()
      mkfs.f2fs: write fill chunk in sparse file for zeroed block
      f2fs-tools: get rid of unneeded fields in on-disk inode
      f2fs-tools: improve xattr value printing
      f2fs-tools: improve filename printing
      fsck.f2fs: open ro disk if we want to check fs only
      fsck.f2fs: fix to repair ro mounted device w/ -f
      f2fs-tools:fix memory leak in write dquot
    
    Change-Id: I478056147cd2e8d288d86b6ad7b1035a5fb3c663
    Signed-off-by: Jaegeuk Kim <jaegeuk@google.com>
    
  - fsck.f2fs: update curseg .next_blkoff/.alloc_type preferential
    
    If .next_blkoff is inconsistent, we can update curseg .next_blkoff
    to first unused block address, and change .alloc_type to SSR
    preferential, instead of move curseg to other position.
    
    This can help to repair fuzzed image which has no more free segment.
    
    Signed-off-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - fsck.f2fs: introduce check_curseg_offsets()
    
    Let check_curseg_offset() just check one curseg, and introduce
    check_curseg_offsets() to check all cursegs, no logic changes.
    
    In addition, update message printed a bit.
    
    Signed-off-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - f2fs-tools: relocate chksum_offset for large_nat_bitmap feature
    
    For large_nat_bitmap feature, there is a design flaw:
    
    Previous:
    
    struct f2fs_checkpoint layout:
    +--------------------------+  0x0000
    | checkpoint_ver           |
    | ......                   |
    | checksum_offset          |------+
    | ......                   |      |
    | sit_nat_version_bitmap[] |<-----|-------+
    | ......                   |      |       |
    | checksum_value           |<-----+       |
    +--------------------------+  0x1000      |
    |                          |      nat_bitmap + sit_bitmap
    | payload blocks           |              |
    |                          |              |
    +--------------------------|<-------------+
    
    Obviously, if nat_bitmap size + sit_bitmap size is larger than
    MAX_BITMAP_SIZE_IN_CKPT, nat_bitmap or sit_bitmap may overlap
    checkpoint checksum's position, once checkpoint() is triggered
    from kernel, nat or sit bitmap will be damaged by checksum field.
    
    In order to fix this, let's relocate checksum_value's position
    to the head of sit_nat_version_bitmap as below, then nat/sit
    bitmap and chksum value update will become safe.
    
    After:
    
    struct f2fs_checkpoint layout:
    +--------------------------+  0x0000
    | checkpoint_ver           |
    | ......                   |
    | checksum_offset          |------+
    | ......                   |      |
    | sit_nat_version_bitmap[] |<-----+
    | ......                   |<-------------+
    |                          |              |
    +--------------------------+  0x1000      |
    |                          |      nat_bitmap + sit_bitmap
    | payload blocks           |              |
    |                          |              |
    +--------------------------|<-------------+
    
    Related report and discussion:
    
    https://sourceforge.net/p/linux-f2fs/mailman/message/36642346/
    
    In addition, during writing checkpoint, if large_nat_bitmap feature is
    enabled, we need to set CP_LARGE_NAT_BITMAP_FLAG flag in checkpoint.
    
    Reported-by: Park Ju Hyung <qkrwngud825@gmail.com>
    Signed-off-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - f2fs-tools: allow unfixed f2fs_checkpoint.checksum_offset
    
    Previously, f2fs_checkpoint.checksum_offset points fixed position of
    f2fs_checkpoint structure:
    
    "#define CP_CHKSUM_OFFSET	4092"
    
    It is unnecessary, and it breaks the consecutiveness of nat and sit
    bitmap stored across checkpoint park block and payload blocks.
    
    This patch allows f2fs-tools to handle unfixed .checksum_offset.
    
    In addition, for the case checksum value is stored in the middle of
    checkpoint park, calculating checksum value with superposition method
    like we did for inode_checksum.
    
    In addition, add below change:
    - using MAX_BITMAP_SIZE_IN_CKPT to clean up codes.
    - introduce verify_checksum_chksum() to verify chksum_{offset,value}
    
    Signed-off-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - fsck.f2fs: fix to repair cp_loads blocks at correct position
    
    Let's fix the wrong start offset of cp_payload blocks in
    fix_checkpoint().
    
    Signed-off-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - sload.f2fs: introduce f2fs_sparse_initialize_meta()
    
    This patch fixes to initialize NAT/SIT/CP.payload region in sparse
    file mode for sload.
    
    Reported-and-tested-by: zhaowuyun <zhaowuyun@wingtech.com>
    Signed-off-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - mkfs.f2fs: write fill chunk in sparse file for zeroed block
    
    As zhaowuyun reported:
    
    we met one problem of f2fs, and found one issue of make_f2fs, so I write
    this email to search for your help to confirm this issue.
    
    The issue was found on one of Android projects. We use f2fs as the filesystem
    of userdata, and make sparse userdata.img using following command, which
    invoked in script mkf2fsuserimg.sh
    make_f2fs -S $SIZE -f -O encrypt -O quota -O verity $MKFS_OPTS $OUTPUT_FILE
    
    use fastboot to flash this userdata.img to device, and it encountered f2fs
    problem and leading to the mount fail of data partition.
    
    we can make this issue 100% persent reproduced by making the data partition
    dirty before flashing userdata.img.
    
    suspect that issue is caused by the dirty data in the data partition.
    so we checked that source code of make_f2fs in f2fs-tool, found that when
    making f2fs, it use dev_fill to do some process:
    
    ...
    
    we change code to the following, and the issue is gone.
    
    if (c.sparse_mode)
           return dev_write(buf, offset, len);
    
    Chao Yu:
    >
    > After checking the codes, IIUC, I guess the problem here is, unlike
    > img2simg, mkfs.f2fs won't record zeroed block in sparse image, so
    > during transforming to normal image, some critical region like
    > NAT/SIT/CP.payload area weren't be zeroed correctly, later kernel may
    > load obsoleting data from those region.
    >
    > Also, The way you provide will obviously increase the size of sparse
    > file, since with it we need to write all zeroed blocks of
    > NAT/SIT/CP.payload to sparse file, it's not needed.
    >
    > Not sure, maybe we should use sparse_file_add_fill() to record zeroed
    > blocks, so that this will make formatted image more like img2simged one.
    
    Jaegeuk:
    > We have to call sparse_file_add_fill() for dev_fill().
    
    This patch fixes to support writing fill chunk sparse file for those
    zeroed blocks in mkfs.f2fs.
    
    Reported-and-tested-by: zhaowuyun <zhaowuyun@wingtech.com>
    Signed-off-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - f2fs-tools: get rid of unneeded fields in on-disk inode
    
    As Jaegeuk reminded:
    
    Once user updates f2fs-tools which support new fields in inode layout,
    but do keep the kernel which can not support those fields, it will cause
    old f2fs fail to mount new image due to root_inode's i_extra_isize value
    sanity check.
    
    So if f2fs-tools doesn't enable feature which will use new fields of
    inode, we don't need to expand i_extra_isize to include them, let's just
    let i_extra_isize point to the end of last valid extra field's position.
    
    Signed-off-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - f2fs-tools: improve xattr value printing
    
    - Print the values of xattrs that have an unknown ->e_name_index, rather
      than ignoring them.
    
    - Replace char with u8.  Otherwise xattr values containing bytes >= 0x80
      are printed incorrectly on platforms where char is signed.
    
    - Only parse the encryption xattr if it has a known format number and
      size.  Otherwise print it as hex.
    
    - Remove incorrect le16_to_cpu() on ->e_name_len which has type u8.
    
    - Consolidate the code that prints the xattr value as hex.
    
    - Constify pointers to the xattr entry.
    
    Signed-off-by: Eric Biggers <ebiggers@google.com>
    Reviewed-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - f2fs-tools: improve filename printing
    
    - Make buffers for pretty-printed filenames 341 bytes long, long enough
      for 255 (NAME_MAX) base64-encoded bytes.  Then print encrypted
      filenames in full, base64-encoded.  This will be useful for tests I'm
      writing which verify the correct ciphertext is stored on-disk.
    
    - Rename convert_encrypted_name() to pretty_print_filename(), to make it
      clear that it handles unencrypted names too.  Also make the output
      'char' rather than 'unsigned char', as it's for printing; and remove
      the unnecessary return value.
    
    Signed-off-by: Eric Biggers <ebiggers@google.com>
    Reviewed-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - fsck.f2fs: open ro disk if we want to check fs only
    
    This patch fixes the "open failure" issue on ro disk, reported by Hagbard.
    
    "
     If I boot with kernel option "ro rootfstype=f2fs
     I get the following halfway trough boot:
    
      * Checking local filesystems  ...
     Info: Use default preen mode
     Info: Mounted device!
     Info: Check FS only due to RO
             Error: Failed to open the device!
      * Filesystems couldn't be fixed
    "
    
    Reported-by: Hagbard Celine <hagbardcelin@gmail.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - fsck.f2fs: fix to repair ro mounted device w/ -f
    
    As Hagbard Celine reported:
    
    "
    Referring to the output from the fsck running against a "ro"
    filesystem, especially this line:
    Info: Check FS only due to RO
    
    As far as i can tell this says that opposed to other filesystems
    running fsck against a "ro" mounted f2fs partition will never fix any
    errors.
    So I tried running fsck against the same partition mounted "rw":
    - mount -o remount,rw /mnt/f2fstest/
    - fsck.f2fs  -f /dev/nvme0n1p7
    Info: Force to fix corruption
    Info: Mounted device!
            Error: Not available on mounted device!
    
    I might be misunderstanding something, but all this tells me that
    unless one make a custom initramfs that runs fsck before root is
    mounted (something no distributions has, as far as I know), fsck will
    never fix an f2fs formatted root partition during boot.
    If this is by design and not a bug/unintended behavior, it should be
    documented somewhere least more people will experience system crashes
    like mine.
    
    All tests above done with kernel 5.0.5 and f2fs-tools 1.12.0 with
    "fsck.f2fs: allow to fsck readonly image w/ -f option"-patch by Chao
    Yu.
    "
    
    We try to make our fsck behavior keeping line with e2fsprogs, but w/
    -f option, we can just check a RO mounted device rather repair it, so
    let's fix this.
    
    Reported-and-Tested-by: Hagbard Celine <hagbardcelin@gmail.com>
    Signed-off-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - f2fs-tools:fix memory leak in write dquot
    
    this patch free ddquot in qtree_write_dquot to avoid memory leak
    
    Signed-off-by: Xiaojun Wang <wangxiaojun11@huawei.com>
    Reviewed-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>