Update git submodules
* Update external/mtpd from branch 'master'
  to 21c8e631ac9176bdecd6e5ce1a22d99377183aa8
  - Merge changes from topic "pppolac"
    
    * changes:
      mtpd: Use L2TP implementation from mainline kernel
      mtpd: l2tp: Fix endianness issues in log prints
      mtpd: Remove obsolete way of passing args to pppd
    
  - mtpd: Use L2TP implementation from mainline kernel
    
    Add upstream kernel implementation of L2TP protocol (OL2TP). This code
    uses pppol2tp-android plugin, which was added to pppd project.
    
    mtpd will try to use OL2TP protocol (upstream) by default. In case if
    OL2TP is disabled in kernel, mtpd will fall back to old OLAC protocol.
    
    After this patch, old implementation (PX_PROTO_OLAC) can be dropped from
    Android kernel. After some transition time we can keep only OL2TP support
    in mtpd and drop OLAC support for good.
    
    In order to use this L2TP implementation, next kernel options should be
    enabled:
    
        CONFIG_NET_IPGRE_DEMUX=y
        CONFIG_PPPOE=y
        CONFIG_L2TP=y
        CONFIG_PPPOL2TP=y
    
    For more details see: [1].
    
    [1] https://wiki.linaro.org/LMG/Kernel/PPP
    
    Change-Id: Ifb0e023817039af7a11353c0568b8c3dd234cc53
    Signed-off-by: Sam Protsenko <semen.protsenko@linaro.org>
    
  - mtpd: l2tp: Fix endianness issues in log prints
    
    Tunnel and session variables are obtained from network, thus are stored
    in network endianness. Although this fact is mentioned in this comment:
    
        // To avoid unnecessary endianness conversions, tunnels, sessions,
        // attributes, and values are all accessed in network order
    
    those variables are not being converted to host endianness when printing.
    
    So convert them to host endianness when printing. Also change the type of
    those variables to __be16 so we can distinguish them easier.
    
    Change-Id: If4a147929fbc79ada51ce5c4f6a1e929d76267aa
    Signed-off-by: Sam Protsenko <semen.protsenko@linaro.org>
    
  - mtpd: Remove obsolete way of passing args to pppd
    
    This Android-specific way of passing args to pppd was added in 4a721df1
    to avoid exposing the L2TP secret in /proc/$$/cmdline (b/2325838). But
    then 41ab620e removed the secret from the command line altogether. So we
    no longer need this hack.
    
    This reverts 4a721df1 ("Use environment variables to pass information to
    pppd.").
    
    Change-Id: I0bbe7424c94bdcfb45c8198fa49f8b5c33bf9db6
    Signed-off-by: Sam Protsenko <semen.protsenko@linaro.org>
    
  - Merge "Use -Werror in external/mtpd" am: e6baa7634b am: 8dd3de4c6b
    am: c7f0cf5a30
    
    Change-Id: Ibdf85422ce17f3b179d60f20d422893568381a5c
    
  - Merge "Use -Werror in external/mtpd" am: e6baa7634b
    am: 8dd3de4c6b
    
    Change-Id: I3ff7551dafbb3548ee511e2cc1fc55791cede87f
    
  - Merge "Use -Werror in external/mtpd"
    am: e6baa7634b
    
    Change-Id: I892c09853b45f3b91facfe3b34fb44e317934c96
    
  - Merge "Use -Werror in external/mtpd"
  - Use -Werror in external/mtpd
    
    Bug: 66996870
    Test: build with WITH_TIDY=1
    Change-Id: Ib683ac4b1bdb39cf63d327152cbb2c6c453a870d
    
  - Merge "mtpd: Run with NET_ADMIN." am: e5c6073727 am: dfc7f34c62
    am: 953eb18d01
    
    Change-Id: Ice87ce790d5b02b3e34309430cf2a11743f0e123
    
  - Merge "mtpd: Run with NET_ADMIN." am: e5c6073727
    am: dfc7f34c62
    
    Change-Id: I8afb5099159946a91a0dd1206063df4a604f1620
    
  - Merge "Protect mtpd socket from VPN" am: de148c40d2 am: e80d1cfd58
    am: cd787c027b
    
    Change-Id: Idac7b125d40dfd43b51d04070f92b4f754399c4a
    
  - Merge "Protect mtpd socket from VPN" am: de148c40d2
    am: e80d1cfd58
    
    Change-Id: I9648e9b3caee84267ae30d86fc99cf7c5ed5c1b5
    
  - Merge "Remove NET_ADMIN capability from mtpd." am: 66c4c5b6b7 am: 53e3b2676b am: b7a140235e
    am: 4532572d2c
    
    Change-Id: Ia71b58e69705f3afa89d51b24c1316b2d03ed7c0
    
  - Merge "mtpd: Use capabilities instead of GIDs." am: 7041ff1e4c am: ff7a5feb15 am: 47b30e06e7
    am: 26fdec3047
    
    Change-Id: I809295ee6b693afdaf26e8d8d2fab6e85c78022f
    
  - Merge "mtpd: Convert Android.mk to Android.bp" am: 4550f59821 am: beb79653f9 am: 37d91651ea
    am: 260e0b3b02
    
    Change-Id: I1bcd62ed3472cd7f700e2dc0bb1640b56426580f
    

* Update external/ppp from branch 'master'
  to 813c1e1d6d2ba87a6428100e735ba1d041e7aac2
  - Merge changes from topic "pppolac"
    
    * changes:
      pppd: Convert Android.mk to Android.bp
      pppd: Add rules for building the pppol2tp-android plugin
      pppd: Fix pppol2tp-android.so build
      pppd: Enable plugin support in pppd
      pppd: Add pppol2tp-android plugin
      pppd: Remove obsolete way of receiving args from mtpd
    
  - pppd: Convert Android.mk to Android.bp
    
    Since Android moved from makefiles to blueprint files [1], all
    Android.mk files should be coverted to corresponding Android.bp files.
    To do so, next command was used:
    
        $ androidmk Android.mk > Android.bp
    
    A bit of polishing was done to resulting Android.bp file (like moving
    "-ldl" flag to shared_libs, which wasn't done automatically, and
    extracting common CFLAGS to cc_defaults section).
    
    Also add Android.bp in ppp/, to actually run ppp/pppd/Android.bp during
    the build.
    
    [1] https://android.googlesource.com/platform/build/soong/+/master/README.md
    
    Change-Id: I45f3e3633f3813381d7710dccbad4da99ce2cb47
    Signed-off-by: Sam Protsenko <semen.protsenko@linaro.org>
    
  - pppd: Add rules for building the pppol2tp-android plugin
    
    Build plugin as shared library. It uses some symbols from pppd, so let's
    allow building the plugin with undefined symbols, as they will be
    resolved at runtime, when plugin is loaded (on dlopen() call).
    
    Plugin will be installed to next path:
      - on 32-bit systems: /system/lib/
      - on 64-bit systems: /system/lib64/
      - on Multilib build: to both paths above
    
    We install it in /system/$LIB/ rather than /system/$LIB/pppd/$VERSION/,
    because we previously modified pppd to look in /system/$LIB for plugins,
    as it is the only allowed path for dlopen().
    
    While at it, extract flags that common for pppd and plugins to separate
    variable, to avoid code duplication.
    
    Also, add pppol2tp-android as pppd dependency, so it will be built and
    installed along with pppd. Let's use LOCAL_REQUIRED_MODULE instead of
    LOCAL_SHARED_LIBRARIES, because latter would lead to linking pppd binary
    against pppol2tp-android.so, which we don't want, as pppol2tp-android.so
    is just a plugin and should be loaded via dlopen() only when it's needed.
    
    -Wno-pointer-sign is added to avoid next error shown by presubmit
    (Treehugger Robot), because 32-bit ABI is broken:
    
            error: passing 'int *' to parameter of type 'socklen_t *'
            (aka 'unsigned int *') converts between pointers to integer
            types with different sign [-Werror,-Wpointer-sign]
    
    -Wno-unused-variable flag is removed, because pppd builds cleanly now.
    
    [1] https://lwn.net/Articles/507794/
    
    Change-Id: I4b51a0f2bf99550c0fe126b6e56e08127dde812b
    Signed-off-by: Sam Protsenko <semen.protsenko@linaro.org>
    
  - pppd: Fix pppol2tp-android.so build
    
    This patch enables USING_UAPI for pppol2tp-android plugin and fixes
    related build errors.
    
    1. Enable USING_UAPI for pppol2tp-android build. When trying to build
    pppol2tp-android.so as is (in current pppd codebase) we will see build
    errors like this one:
    
        bionic/libc/kernel/uapi/linux/ppp_defs.h:59:6:
            error: redefinition of 'NPmode'
        external/ppp/pppd/include/net/ppp_defs.h:142:6:
            note: previous definition is here
    
    This is basically because USING_API option is not defined when building
    pppol2tp-android.c, though it should be. Enabling that option fixes the
    build. Detailed explanation is below.
    
    Unlike the upstream pppd project, we don't keep include/linux/* headers
    inside of pppd codebase. Instead, we define USING_UAPI when such headers
    (user-space API [1]) are used, providing missing functionality in
    ppp_defs.h file. From pppol2tp-android.c file it's obvious that UAPI is
    used there (as linux/* files are included there). So we need to enable
    USING_UAPI definition. Whether UAPI can be used or not is checked by
    inspecting PPP_ADDRESS definition (if defined -- then we are actually
    using UAPI, so USING_UAPI is defined). But for PPP_ADDRESS to be defined
    we need to include <linux/ppp_defs.h> first (just like it's done in
    sys-linux.c). So let's do that for all Linux systems, before actually
    checking PPP_ADDRESS.
    
    2. If we try to build pppol2tp-android plugin with current pppd
    codebase, we will see next build errors (when USING_UAPI is enabled):
    
        external/ppp/pppd/include/net/ppp_defs.h:142:17:
            error: field has incomplete type 'struct ifreq'
        external/ppp/pppd/include/net/ppp_defs.h:143:21:
            error: field has incomplete type 'struct ppp_stats'
    
    Let's include net/if.h for struct ifreq, and linux/ppp_defs.h for
    struct ppp_stats.
    
    [1] https://lwn.net/Articles/507794/
    
    Change-Id: I3338a78b5579229ebe3dbd908a9a9f37aa63e042
    Signed-off-by: Sam Protsenko <semen.protsenko@linaro.org>
    
  - pppd: Enable plugin support in pppd
    
    This patch makes it possible for pppd to load plugins in Android. Next
    changes were made:
    
    1. Link pppd with libdl library, which allows dynamic loading of shared
       libraries.
    
    2. Use -rdynamic to export all pppd symbols in dynamic symbol table,
       so that plugins can link their undefined symbols against pppd.
    
    3. Change plugins search path in pppd to:
       - /system/lib/    (on 32-bit systems)
       - /system/lib64/  (on 64-bit systems)
    
    Last change was done for two reasons:
    
    1. Fix plugin loading on 64-bit architectures
    
       On ARM64 pppd will try to load 32-bit plugins (.so) files from /lib,
       which leads to this kind of errors:
    
           E pppd    : dlopen failed:
                       "/system/lib/pppd/2.4.7/pppol2tp-android.so"
                       is 32-bit instead of 64 bit
           E pppd    : Couldn't load plugin pppol2tp-android.so
    
       To overcome this issue let's make pppd look for plugins in lib/ or
       in lib64/ directory based on __LP64__ definition.
    
    2. Search for plugins in /system/${LIB}
    
       Bionic loader allows us to dlopen() libraries only from
       /system/${LIB} root directory (as specified in ld.config.txt, see
       "default" linker namespace). When using upstream pppd location, which
       is /system/${LIB}/pppd/2.4.7/, next error occurs in logcat, when pppd
       is trying to load some plugin:
    
       pppd : dlopen failed: library
              "/system/lib64/pppd/2.4.7/pppol2tp-android.so"
       needed or dlopened by "/system/bin/pppd" is not accessible for the
       namespace "(default)"
    
       Make pppd look only in /system/${LIB} root directory to fix this
       issue.
    
    Change-Id: I13c8c30337b1307911bdafa711afa1c3c34e99a6
    Signed-off-by: Sam Protsenko <semen.protsenko@linaro.org>
    
  - pppd: Add pppol2tp-android plugin
    
    mtpd tool was reworked to use mainline kernel implementation of L2TP.
    So now mtpd relies on pppol2tp-android plugin. This patch implements
    pppol2tp-android plugin from scratch, as mainline version [1] is licensed
    under GPL and can't be adopted in Android.
    
    [1] https://github.com/paulusmack/ppp
    
    Change-Id: I41394e81e70d511f53ce262e411517af6a1ac564
    Signed-off-by: Sam Protsenko <semen.protsenko@linaro.org>
    
  - pppd: Remove obsolete way of receiving args from mtpd
    
    Since encrypted way of passing arguments from mtpd to pppd via
    environment was removed from mtpd, let's remove it in pppd as well.
    
    This reverts commit 1661f734 ("Add support to get information from
    environment variables").
    
    Change-Id: I53bb2b303bf6fd84546bd7f3bfc4fd35421f457f
    Signed-off-by: Sam Protsenko <semen.protsenko@linaro.org>
    
  - Merge "Remove unused include" am: ff3b334724 am: 7e60466a00
    am: 52e88aa89c
    
    Change-Id: I0ea0ba5eb808c7025a63cbba956c49bbeaf5967e
    
  - Merge "Remove unused include" am: ff3b334724
    am: 7e60466a00
    
    Change-Id: If7005129f7f4cf97e05ec444c802f0430ad9474b