Update git submodules
* Update system/core from branch 'master'
  to f6ee8fe5155557bf6b796038ef982a9d03c99c07
  - Merge "Revert "Add derived UsbTransport class with USB reset method""
  - Revert "Add derived UsbTransport class with USB reset method"
    
    This reverts commit ceb7cbf5fde0ff26a35d442135d01e52b0ef0771.
    
    Reason for revert: Broke mac builds:
    system/core/fastboot/usb_osx.cpp:513:35: error: use of undeclared identifier 'USB_TRANSACTION_TIMEOUT'
    USB_TRANSACTION_TIMEOUT, USB_TRANSACTION_TIMEOUT);
    ^
    
    Change-Id: Ibe2f9ff2d5c63f9d33f4bd6d9ba962604cf8caeb