Update git submodules
* Update bionic from branch 'master'
  to f7f5ba4cde75758f3ec9c26d77b039b8bf6a26fc
  - Merge changes I48210ea1,I5f717dd1
    
    * changes:
      clean_header: Run outside of $ANDROID_BUILD_TOP
      clean_header: Fix error handling for no-such-file case
    
  - clean_header: Run outside of $ANDROID_BUILD_TOP
    
    Enable the use case where we run clean_header.py from outside of
    $ANDROID_BUILD_TOP. Previously, this script required the current working
    directory to be under $ANDROID_BUILD_TOP. Running it from a different
    directory resulted in the following error message:
    
     clean_header.py: error: Not in android tree pointed at by ANDROID_BUILD_TOP (....)
    
    Change-Id: I48210ea1a0033228a9aaa4124d28247b07cee6d4
    
  - clean_header: Fix error handling for no-such-file case
    
    The function cleanupFile should always return a single value (as opposed
    to a tuple or list). In addition, if it encounters an error, it is
    expected to return a value that evaluates to False. As it stands,
    however, it returns (None, None) in certain error cases. Change this
    function to return None, in those cases.
    
    We previously saw the following error message, when we tried to run
    clean_header.py on a non-existent file.
    
    Traceback (most recent call last):
      File "clean_header.py", line 208, in <module>
        b.updateGitFiles()
      File "utils.py", line 164, in updateGitFiles
        self._writeFile(dst)
      File "utils.py", line 136, in _writeFile
        f.write(self.new_data[dst])
    TypeError: expected a string or other character buffer object
    
    Change-Id: I5f717dd1a4388f598f0fd4bfd5e6129017de9095