Update git submodules
* Update external/googletest from branch 'master'
  to a1824beabf0bb19faf1f05b78a878e2e3f5a357b
  - Upgrade googletest to 8b6d3f9c4a774bef3081195d422993323b6bb2e0
    
    Upstream deprecated all *_TEST_CASE_* macros in favor of new *_TEST_SUITE_* macros. But there are still thousands of references to the old ones in Android. As suggested here:
    
    https://github.com/google/googletest/commit/db9b85e27522628ef173149a692031b7f2154b55
    
    I defined GTEST_INTERNAL_DEPRECATED to empty to suppress warnings.
    
    Test: build
    Change-Id: Ifffd9f98ab40adde65031d45acf9c47cc252b069
    
  - Merge pull request #2158 from CarloWood:master
    
    PiperOrigin-RevId: 236716851
    
  - Googletest export
    
    Fix emission of -Wzero-as-null-pointer-constant when comparing integers.
    
    The following code fails to compile:
    
    #pragma clang diagnostic error "-Wzero-as-null-pointer-constant"
    void foo() {
      EXPECT_EQ(0, 0);
    }
    
    This happens because gtest checks the first argument to EXPECT_EQ and
    ASSERT_EQ is a null pointer constant. The magic it does to do this causes the
    warning to be emitted.
    
    This patch removes that check. It replaces the explicit check with a Compare
    overload that can only be selected when 0 or nullptr is passed on the LHS
    with a pointer on the right.
    
    This patch does not suppress -Wzero-as-null-pointer-constant when users
    are actually using it as NULL.
    
    PiperOrigin-RevId: 236654634
    
  - Googletest export
    
    Build gmock cleanly with clang -Wextra-semi and -Wextra-semi-stmt
    
    Extends 56ef07a20308 to take -Wc++98-compat-extra-semi
    (https://reviews.llvm.org/D43162) and -Wextra-semi-stmt
    (https://reviews.llvm.org/D52695) into account.
    
    For https://crbug.com/926235.
    
    PiperOrigin-RevId: 236643095
    
  - Googletest export
    
    Let embedders customize GTEST_INTERNAL_DEPRECATED().
    
    GTEST_INTERNAL_DEPRECATED is currently used to nudge googletest users to migrate off old TEST_CASE macros to the new TEST_SUITE macros. This move is non-trivial for Chromium (see https://crbug.com/925652), and might be difficult for other big projects with many dependencies.
    
    This CL facilitates moving off of deprecated APIs by making it possible for an embedder to define GTEST_INTERNAL_DEPRECATED() in gtest/internal/custom/gtest-port.h. Example usage:
    
    1) #define GTEST_INTERNAL_DEPRECATED() to nothing, to disable deprecation warnings while migrating off googletest's deprecated APIs. This can be preferable to having to disable all deprecation warnings (-Wno-error=deprecated or -Wno-deprecated-declarations).
    
    2) #define GTEST_INTERNAL_DEPRECATED() for an unsupported compiler.
    
    PiperOrigin-RevId: 236171043
    
  - Googletest export
    
    Build gmock cleanly with clang -Wextra-semi
    
    For https://crbug.com/926235.
    From https://github.com/google/googletest/pull/2139.
    Fixes https://github.com/google/googletest/issues/2138.
    
    PiperOrigin-RevId: 235832527
    
  - Minor build system fixes.
    
  - Googletest export
    
    Replace more pump'd code with variadic templates.
    
    PiperOrigin-RevId: 235584585
    
  - Merge pull request #2152 from rsinnet/patch-1
    
    Fix grammatical error in primer.md
  - Fix grammatical error in primer.md
  - Merge pull request #2147 from ngie-eign:gtest-test-death-test-dont-hardcode-test-name
    
    PiperOrigin-RevId: 235248114
    
  - Merge pull request #2126 from ngie-eign:clang-add-more-strict-warnings
    
    PiperOrigin-RevId: 235220570
    
  - Don't hardcode the filename in `CxxExceptionDeathTest.PrintsMessageForStdException`
    
    Due to some caveats in the FreeBSD build system and the fact that the
    source file is used to compile 2 different death tests with different
    flags, I needed (as a shortterm workaround) to copy the test to 2
    differently named files.
    
    While this works for compiling the test, as I discovered, this doesn't
    work with running `CxxExceptionDeathTest.PrintsMessageForStdException`,
    as the testcase hardcodes `googletest-death-test_ex_test.cc`. Use `__FILE__`
    when looking for failures, as opposed to looking for the hardcoded name
    as it can vary depending on how the test was built.
    
    Signed-off-by: Enji Cooper <yaneurabeya@gmail.com>
    
  - Merge pull request #2137 from ngie-eign:clang-ignore-sign-conversion
    
    PiperOrigin-RevId: 235012245
    
  - Merge pull request #2061 from samolisov:building-with-bazel-as-a-dll-on-windows
    
    PiperOrigin-RevId: 234845565
    
  - Merge pull request #2125 from ngie-eign:clang-unused-parameter
    
    PiperOrigin-RevId: 234844287
    
  - Merge pull request #2123 from ngie-eign:clang-inconsistent-missing-override
    
    PiperOrigin-RevId: 234840107
    
  - Googletest export
    
    Internal Change
    
    PiperOrigin-RevId: 234823465
    
  - Googletest export
    
    Update gtest-death-test to use new Fuchsia API
    
    Fuchsia has renamed this API and removed the need for several parameters. We now use the newer, simpler API.
    
    PiperOrigin-RevId: 234617715
    
  - Merge pull request #2141 from dspinellis/index-fix
    
    Avoid array index out of range
  - Avoid array index out of range
    
    Issue: #2140
    
  - Ignore `-Wsign-conversion` issues
    
    clang++ compilation when `-Wsign-conversion` is currently broken and the
    issues within the code are varied and widespread. For the time being
    ignore `-Wsign-conversion` issues, even though some of them are valid
    and bleed over into issues that would be found with
    `-Wtautological-compare`, et al.
    
    Signed-off-by: Enji Cooper <yaneurabeya@gmail.com>
    
  - Fix clang `-Wunused-parameter` warnings
    
    Comment out unused method parameters in their relevant definitions.
    
    Signed-off-by: Enji Cooper <yaneurabeya@gmail.com>
    
  - Fix clang `-Winconsistent-missing-override` warnings
    
    `DescribeTo(..)` and `MatchAndExplain(..)` in `gmock-matchers_test` both
    override virtual methods. Remove the `virtual` keyword and apply `override` to
    them instead.
    
    Signed-off-by: Enji Cooper <yaneurabeya@gmail.com>
    
  - Fix clang `-Winconsistent-missing-override` warnings
    
    `DescribeTo(..)` and `MatchAndExplain(..)` in `gmock-matchers_test` both
    override virtual methods. Remove the `virtual` keyword and apply `override` to
    them instead.
    
    Signed-off-by: Enji Cooper <yaneurabeya@gmail.com>
    
  - Add `cxx_strict_flags` for clang to match FreeBSD's WARNS flags
    
    Signed-off-by: Enji Cooper <yaneurabeya@gmail.com>
    
  - Merge pull request #2112 from knuto:pr/fix_null_pointer
    
    PiperOrigin-RevId: 233825166
    
  - Merge pull request #2121 from ngie-eign:add-dragonflybsd-and-kfreebsd-support
    
    PiperOrigin-RevId: 233789488
    
  - Merge pull request #2114 from knuto:pr/libtool_support
    
    PiperOrigin-RevId: 233773676
    
  - Merge pull request #2119 from ngie-eign:clang-wunused-private-field
    
    PiperOrigin-RevId: 233762751
    
  - Merge pull request #2120 from ngie-eign:clang-compile-with-basic-warns-flags
    
    PiperOrigin-RevId: 233762520
    
  - Merge pull request #2113 from knuto:pr/set_old_gtest_ver
    
    PiperOrigin-RevId: 233748252
    
  - Import `patch-bsd-defines` from FreeBSD ports [1]
    
    As noted in the patch description:
    * Add DragonFly and GNU/kFreeBSD support.
    * Implement GetThreadCount() for BSDs.
    
    1. https://svnweb.freebsd.org/ports/head/devel/googletest/files/patch-bsd-defines?revision=488934
    
    Signed-off-by: Enji Cooper <yaneurabeya@gmail.com>
    
  - Compile clang with `-Wall -Wshadow -Werror`
    
    It was not compiling any of the code with warnings prior to this.
    
    Signed-off-by: Enji Cooper <yaneurabeya@gmail.com>
    
  - Fix -Wunused-private-field issues with clang
    
    Provide dummy accessors for private values that are set in initializers,
    but not actually used.
    
    Signed-off-by: Enji Cooper <yaneurabeya@gmail.com>
    
  - Googletest export
    
    Internal Change
    
    PiperOrigin-RevId: 233614147
    
  - Merge pull request #2107 from ciband:feat/finish_platformio_support
    
    PiperOrigin-RevId: 233108234
    
  - Merge pull request #2101 from MaEtUgR:fix-cmake-cygwin
    
    PiperOrigin-RevId: 233096223
    
  - Googletest export
    
    Internal changes.
    
    PiperOrigin-RevId: 232953166
    
  - Googletest export
    
    Fix matcher comparisons for std::reference_wrapper.
    
    The googletest docs indicate that std::reference_wrapper should be used to for
    objects that should not be copied by the matcher (in fact, the ByRef() function
    is basically the same as a call to std::cref).
    
    However, for many types (such as std::string), the overloaded operator== will
    not resolve correctly. Specifically, this is problematic if operator== depends
    on template argument deduction, where the same type is named on LHS and RHS.
    
    Because template argument deduction happens before any implict conversions for
    purposes of overload resolution, attempting to compare T with
    std::reference_wrapper<T> simply looks like a comparison of unlike types.
    
    For exapmle, std::reference_wrapper<std::string> is implicitly convertible to
    'const std::string&', which would be able to choose an overload specialization
    of operator==. However, the implicit conversion can only happen after template
    argument deduction for operator==, so a specialization that would other be an
    applicable overload is never considered.
    
    Note also that this change only affects matchers. There are good reasons that
    matchers may need to transparently hold a std::reference_wrapper. Other
    comparisons (like EXPECT_EQ, et. al.) don't need to capture a reference: they
    don't need to defer evaluation (as in googlemock), and they don't need to avoid
    copies (as the call chain of matchers does).
    
    PiperOrigin-RevId: 232499175
    
  - Googletest export
    
    Internal change
    
    PiperOrigin-RevId: 232362580
    
  - Set gtest version correctly for older cmake versions
    
    Signed-off-by: Knut Omang <knut.omang@oracle.com>
    
  - Generate a libgtest.la to help libtool managing dependencies
    
    When building and using googletest from an install tree
    we want libtool to generate rpath in the dependent binaries
    to allow them to be executed from a build without a need
    for LD_LIBRARY_PATH or similar.
    
    For libtool based project this happens automatically
    as projects generates .la files and install them.
    Provide such a file for gtest as well to allow it to
    work smoothly with libtool based projects.
    
    Signed-off-by: Knut Omang <knut.omang@oracle.com>
    
  - Stop TestInfo::Run() calling a function through null pointer
    
    If the object was never created then trying to call &Test::DeleteSelf_
    will dereference a null pointer, with undefined behaviour.
    
    Fixes #845
    
  - fix:  Correct *-all.cc file paths
  - Merge pull request #2100 from ngie-eign/test-clang-osx-every-travis-run
    
    Test out changes with clang/OSX each PR using Travis CI
  - Merge pull request #2103 from kw-udon/fix-json-in-advanced-md
    
    Fix an invalid example of JSON report in advanced.md
  - Fix an invalid example of JSON report in advanced.md
    
    This is just a mistake in the document. Google Test doesn't output
    such an invalid JSON report.
    
    Signed-off-by: Keiichi Watanabe <keiichiw@chromium.org>
    
  - Update .travis.yml
  - Update .travis.yml
  - Test out changes with clang/OSX each PR using Travis CI
    
    This will help ensure that test coverage isn't missed when changes that
    can impact OSX with clang are submitted. Although not perfect, testing
    changes on OSX with clang is an ok proxy [for now] for testing changes on
    FreeBSD with clang (testing on FreeBSD is non-trivial, as Travis CI doesn't
    support operating systems other than Linux and OSX).
    
    In order to support this, install the packages via homebrew using a
    `addons::homebrew::packages` block (similar to `addons::apt::packages`
    for Ubuntu), as documented in the Travis CI docs
    ( https://docs.travis-ci.com/user/installing-dependencies/ ). While
    here, try pushing apt* calls into the Travis config for Ubuntu, instead
    of delaying the equivalent calls in the `ci/*.sh` scripts. Keep the
    `ci/*.sh` scripts for ease of testing locally (and extend the OSX one to
    install gcc 4.9 and llvm 3.9, like the travis config does).
    
    In order to accomodate this change (and because the homebrew package for
    llvm@3.9 doesn't automatically add clang*-3.9 to `$PATH`), `$PATH` needs
    to be adjusted to find the llvm@3.9 toolchain.
    
    Signed-off-by: Enji Cooper <yaneurabeya@gmail.com>
    
  - Googletest export
    
    Address -Wgnu-zero-variadic-macro-arguments
    Originally in OSS PR #2063 https://github.com/google/googletest/pull/2063
    Fix regression in INSTANTIATE_TEST_SUITE_P macro to accept function pointers properly.
    
    PiperOrigin-RevId: 232316698
    
  - Googletest export
    
    Mark legacy _TEST_CASE_ macros as deprecated
    
    PiperOrigin-RevId: 232303251
    
  - Googletest export
    
    Update example code in gtest.h to prefer override over virtual now
    that it is widely available in C++11.
    
    PiperOrigin-RevId: 232057792
    
  - Merge pull request #2098 from ciband:feat/finish_platformio_support
    
    PiperOrigin-RevId: 232028696
    
  - cmake: detect Cygwin which needs extensions to build
    
  - cmake: move global project definition to beginning
    
    such that necessary cmake variables to detect Cygwin are defined
    when setting the C++ standard and we can distinguish.
    
  - Googletest export
    
    Fix stack overflow in AnyOfArray tests.
    
    PiperOrigin-RevId: 231881125
    
  - chore: Add PlatformIO supported platforms list
  - fix: Add Arduino to embedded platform list
    
    Added Arduino to the embedded platform list to allow for a stubbed out version
    of GetCurrentDir.
    
  - fix: Add *_all.cc files to ignore list
    
    Added [gmock|gtest]_all.cc to PIO ignore list to avoid getting duplicate
    symbols since PIO will compile the individual files.
    
  - Merge pull request #2092 from Billy4195/Update_README
    
    Fix README.md broken link
  - Fix README.md broken link
    
    Fix the **include/gtest/internal/gtest-port.h** link in the `Tweaking Google Test` title
  - Enable CI on Windows (appveyor) with Bazel
    
    Signed-off-by: Pavel Samolysov <samolisov@gmail.com>
    
  - Enable building as a shared library (dll) on Windows with Bazel
    
    While the google test library is being built as a shared library using Bazel,
    so that there is a rule like
    
    cc_test(
         name = "iterator_traits_test",
         linkstatic = 0,
         deps = ["@gtest//:gtest_main"],
         ...
    )
    
    in a BUILD file, the following error appears on Windows:
    
    INFO: Found 1 test target...
    ERROR: C:/../external/gtest/BUILD.bazel:55:1: output 'external/gtest/gtest.if.lib' was not created
    ERROR: C:/../external/gtest/BUILD.bazel:55:1: not all outputs were created or valid
    Target //test:iterator_traits_test failed to build
    
    The reason is a missing "win_def_file" attribute of the "gtest" and
    "gtest_main" rules in the BUILD.bazel inside the google test library
    package.
    
    The "windows_export_all_symbols" feature is added to the rules, this
    feature forces Bazel to export all symbols from the google test library
    to linker. I believe exporting all symbols from a testing library makes
    no problem for the application from a point of view on encapsulation.
    
    Signed-off-by: Pavel Samolysov <samolisov@gmail.com>