Update git submodules
* Update external/lldb from branch 'lldb-master-dev'
  to a3601b3b77651056f8814d9a25516f2d33a55009
  - Fix buildbot regression by rL339929: NameError: global name 'test_directory' is not defined
    am: 288ba435b6
    
    Change-Id: I7844047de88142313e973c1742ff3535c06a4118
    
  - Fix buildbot regression by rL339929: NameError: global name 'test_directory' is not defined
    
    With buildbot slave under test - I get after rL339929:
    http://lab.llvm.org:8014/builders/lldb-x86_64-fedora-28-cmake/builds/243/steps/test1/logs/stdio
    
      File "/home/buildbot/lldbroot/lldb-x86_64-fedora-28-cmake/scripts/../llvm/tools/lldb/test/dotest.py", line 7, in <module>
        lldbsuite.test.run_suite()
      File "/quad/home/buildbot/lldbroot/lldb-x86_64-fedora-28-cmake/llvm/tools/lldb/packages/Python/lldbsuite/test/dotest.py", line 1177, in run_suite
        configuration.results_formatter_object)
      File "/quad/home/buildbot/lldbroot/lldb-x86_64-fedora-28-cmake/llvm/tools/lldb/packages/Python/lldbsuite/test/dosep.py", line 1692, in main
        dst = core.replace(test_directory, "")[1:]
    NameError: global name 'test_directory' is not defined
    
    Patch by Vedant Kumar.
    
    Differential Revision: https://reviews.llvm.org/D51874
    
    
    git-svn-id: https://llvm.org/svn/llvm-project/lldb/trunk@343726 91177308-0d34-0410-b5e6-96231b3b80d8