Update git submodules
* Update external/selinux from branch 'master'
  to 781054cc2f2ac32f1f99bccb68b0d66aa8215ea0
  - Merge remote-tracking branch 'aosp/upstream-master' into mymerge
    
    Followed the following steps:
      # In repo client
      cd external/selinux
      repo sync .
      repo start mymerge .
      git merge aosp/upstream-master --no-ff # resolve any conflicts
      lunch && make -j
      repo upload .
    
    Test: compiles and boots
    Change-Id: I75ccf5307012a2517c0fdf13bea806e10b8b8595
    
  - restorecond: Do not link against libpcre
    
    For some reasons, restorecond was explicitly linking against libpcre but
    the code is not using any of its symbols
    
    Closes: https://github.com/SELinuxProject/selinux/issues/137
    
    Signed-off-by: Laurent Bigonville <bigon@bigon.be>
    
  - restorecond: use /run instead of /var/run
    
    On most distributions, /var/run is a symbolic link to /run so using
    /var/run or /run lead to the same result. Nevertheless systemd started
    to warn about using /var/run in a service file, logging entries such as:
    
        /usr/lib/systemd/system/restorecond.service:8: PIDFile= references
        path below legacy directory /var/run/, updating
        /var/run/restorecond.pid → /run/restorecond.pid; please update the
        unit file accordingly.
    
    Switch to /run in order to follow this advice.
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - gui: Install .desktop files to /usr/share/applications by default
    
    /usr/share/applications is a standard directory for .desktop files.
    Installation path can be changed using DESKTOPDIR variable in installation
    phase, e.g.
    
    make DESKTOPDIR=/usr/local/share/applications install
    
    Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
    
  - gui: Install polgengui.py to /usr/bin/selinux-polgengui
    
    polgengui.py is a standalone gui tool which should be in /usr/bin with other
    tools.
    
    Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
    
  - Update VERSIONs to 2.9 for release.
    
    Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
    
  - libselinux: Do not define gettid() if glibc >= 2.30 is used
    
    Since version 2.30 glibc implements gettid() system call wrapper, see
    https://sourceware.org/bugzilla/show_bug.cgi?id=6399
    
    Fixes:
    cc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I../include -D_GNU_SOURCE  -DNO_ANDROID_BACKEND   -c -o procattr.o procattr.c
    procattr.c:28:14: error: static declaration of ‘gettid’ follows non-static declaration
       28 | static pid_t gettid(void)
          |              ^~~~~~
    In file included from /usr/include/unistd.h:1170,
                     from procattr.c:2:
    /usr/include/bits/unistd_ext.h:34:16: note: previous declaration of ‘gettid’ was here
       34 | extern __pid_t gettid (void) __THROW;
          |                ^~~~~~
    
    Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
    
  - libselinux: Add security_reject_unknown(3) man page
    
    Commit c19395d72295 ("libselinux: selinux_set_mapping: fix handling of unknown
    classes/perms") added a new interface security_reject_unknown() which needs to
    be documented.
    
    Signed-off-by: Petr Lautrbach <plautrba@redhat.com>