Update git submodules
* Update external/autotest from branch 'master'
  to ec1fa878b6e8ada9885c207725bcd25795ceffee
  - model_logic: limit objects size for _get_pivot_iterator
    am: 23e5ca8562
    
    Change-Id: I8aa9ddcc5c96da283cbbb27c5244974c5b73b351
    
  - model_logic: limit objects size for _get_pivot_iterator
    
    If there are too many arguments for sqlite3 query, it will cause
    `django.db.utils.DatabaseError: too many SQL variables`
    
    BUG=b:120473422
    TEST=test_that $IP suite:arc-cts, no DatabaseError
    
    Change-Id: I9e91d8866c93081202ae96225f9807636b6be930
    Reviewed-on: https://chromium-review.googlesource.com/1361180
    Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
    Tested-by: Hsin-Yi Wang <hsinyi@chromium.org>
    Reviewed-by: Hung-Te Lin <hungte@chromium.org>