Update git submodules
* Update external/clang from branch 'lldb-master-dev'
  to 27af9a2123d4eb7a8e405a9c7a91fc21a5f6b302
  - Merge "[clang-check-codegen][cfstring] Accept either @ or % for progbits to make ppc64be bots happy. am: 77c4d242ac" into lldb-master-dev
  - [clang-check-codegen][cfstring] Accept either @ or % for progbits to make ppc64be bots happy.
    am: 77c4d242ac
    
    Change-Id: I67038edc5bf1f99d83be128ba7223dced6e99c03
    
  - [clang-check-codegen][cfstring] Accept either @ or % for progbits to make ppc64be bots happy.
    
    PPC64BE bots use % instead of @ for directives like progbits. Since CFString tests also
    check asm output, they fail on the following:
    
      cfstring3.c:44:19: error: CHECK-ASM-ELF: expected string not found in input
      // CHECK-ASM-ELF: .section cfstring,"aw",@progbits
      <stdin>:30:2: note: possible intended match here
      .section cfstring,"aw",%progbits
    
    Updating that check with a {{[@%]}}progbits regex to make those bots happy.
     
    
    
    git-svn-id: https://llvm.org/svn/llvm-project/cfe/trunk@343044 91177308-0d34-0410-b5e6-96231b3b80d8