Update git submodules
* Update frameworks/support from branch 'androidx-concurrent-release'
  to 41d4c1e9a3ba84142c6828c1796ae919da511ec6
  - Merge "Snap for 5633419 from b47a4f6e3abdab26be9e57a743a22c4a06c32a3b to androidx-concurrent-release" into androidx-concurrent-release
  - Snap for 5633419 from b47a4f6e3abdab26be9e57a743a22c4a06c32a3b to androidx-concurrent-release
    
    Change-Id: Ibb88ba79bdfffc9befbcb48ff39242f76f930061
    
  - Merge "Merge room-common-java8 into room-common" into androidx-master-dev
  - Merge "Update media, media2, mediarouter, and concurrent-listenablefuture to rc01" into androidx-master-dev
  - Merge "Move alpha libraries to target Java 8." into androidx-master-dev
  - Merge "Ensure ActionBar is not updated when destination is floating window" into androidx-master-dev
  - Merge "Update to kotlin mockito 2.1.0" into androidx-master-dev
  - Update media, media2, mediarouter, and concurrent-listenablefuture to
    rc01
    
    Once this CL lands, we will snap the release branches to that build
    and then move all versions to the next minor alpha version
    
    ag/7931701 is the internal update so that a merge conflict won't occur
    
    Bug: b/134485892
    Test: ./gradlew checkApi verifyDependencyVersions
    Change-Id: I3dc544c04e3c4d10fc30ba89627339142f6f0190
    Merged-In: I3dc544c04e3c4d10fc30ba89627339142f6f0190
    
  - Merge "Update migration for MDC classes used by navigation-ui" into androidx-master-dev
  - Merge "Check integer key existence of MediaFormat" into androidx-master-dev
  - Check integer key existence of MediaFormat
    
    It fixes the failing test MediaControllerCallbackTest#testOnSubtitleData
    
    Bug: 134375069
    Test: ./media2/session/version-compat-tests/runtest.sh 1 &&
          ./gradlew :media2:media2-session:connectedCheck
    Change-Id: Idc7adad1177927ea81f4238bd3931c4f92387fae
    
  - Update to kotlin mockito 2.1.0
    
    Test: ./gradlew cC
    Change-Id: I8f0e62f031e46ff3f939531f100ec241ce3eee7f
    
  - Merge "Use a constant for Mockito-Kotlin" into androidx-master-dev
  - Merge room-common-java8 into room-common
    
    Now that room-common targets java8, we no longer need the second
    library.
    
    Bug: 134425740
    Test: ./gradlew buildOnServer
    Change-Id: I7c847c23a7a737c2ae2e42d2f249f094f8890e9b
    
  - Move alpha libraries to target Java 8.
    
    Add a check so that any library that moves to alpha
    has to move to Java 8 as well.
    
    Also add a workaround to WorkManagerImplTest that is hit when moving
    to Java 8:
    /work/workmanager/src/androidTest/java/androidx/work/impl/WorkManagerImplTest.java:1387: error: reference to Preferences is ambiguous
            Preferences preferences = new Preferences(ApplicationProvider.getApplicationContext());
                                      ^
      both constructor Preferences(Context) in Preferences and constructor Preferences(SharedPreferences) in Preferences match
    
    Test: ./gradlew buildOnServer
    
    Change-Id: I1285b4ce12047511c98f44d58e13fac3aac9b0ad
    
  - Merge "Clarify row id return value with IGNORE and REPLACE conflict resolutions" into androidx-master-dev
  - Merge "Disable double activity animation when opening app with deeplink" into androidx-master-dev
  - Update migration for MDC classes used by navigation-ui
    
    Update the migration.config file to use the new
    package names for Material classes used by the
    navigation-ui artifacts.
    
    Test: manually inspected output classes.jar
    Change-Id: If85f8356fea1951b9005a0c04ab4bca83887a602
    
  - Use a constant for Mockito-Kotlin
    
    Test: ./gradlew cC
    Change-Id: I953a6d390fc5e8c95cedc36fdc415eba891dc2a5
    
  - Merge "Added simple Scroller benchmark test." into androidx-master-dev
  - Clarify row id return value with IGNORE and REPLACE conflict resolutions
    
    Bug: 132915693
    Test: N/A
    Change-Id: I5ca14d4c653f5d55c05733d87ef2249c461adbc2
    
  - Merge "Stop IDE inspection for empty parentheses after annotations" into androidx-master-dev
  - Disable double activity animation when opening app with deeplink
    
    When using handleDeepLink(Intent) to open an app, Navigation enforces
    that Intents that set the NEW_TASK flag also set the CLEAR_TASK flag.
    This ensures a consistent activity back stack, and means that the
    Activity should be created twice when the calling app only uses
    NEW_TASK. Both Activity creations are currently being animated, causing
    what appears as a flash before the app starts.
    
    This change ensures that the second Activity creation animation is
    disabled.
    
    Test: Tested in app, all tests pass.
    BUG: 130362979
    Change-Id: Ie765aea34176508b7c1b4b897ca25e0d11b2d819
    
  - Merge "Deprecate setClickable() and replace method with setEntireItemClickable()." into androidx-master-dev
  - Merge "Enable threaded downloadable font fetch in background thread" into androidx-master-dev
  - Merge "Remove hard-coded compile and target sdk version" into androidx-master-dev
  - Enable threaded downloadable font fetch in background thread
    
    This is workaround for not using caller's Handler.
    This CL only change the behavior if the downloadable font is specified
    in layout XML. The public API behavior is kept as it is.
    
    Bug: 128517548
    Test: ./gradlew core:connectedAndroidTest
      on API 19 through API 29 except for 20
    Test: ./gradlew appcompat:connectedAndroidTest
      on API 19 through API 29 except for 20
    Test: Manally done
    Change-Id: I6da1b1ebfa753654009be9eac11914304b834072
    
  - Deprecate setClickable() and replace method with setEntireItemClickable().
    
    Bug: 133358906
    Test: ./gradlew :car:connectedCheck
    
    Change-Id: I2ae37f9144b4d53f8224c46783c70d5a02140c9b
    
  - Merge "Clean up deprecation in androidx.viewpager, set deprecation as fatal" into androidx-master-dev
  - Merge "Add documentation for PublishDocsRules" into androidx-master-dev
  - Remove hard-coded compile and target sdk version
    
    These values are already set via AndroidXPlugin.
    
    Test: ./gradlew assembleDebug
    Change-Id: I90fd42e8547332a240779cbf6d12661b8352408a
    
  - Merge "Add repaint boundary" into androidx-master-dev
  - Merge "Relax restriction scope to PREFIX for methods in media" into androidx-master-dev
  - Merge "Fix indentation in NavigationUI comments." into androidx-master-dev
  - Relax restriction scope to PREFIX for methods in media
    
    They are used in media2-session.
    
    Bug: 134384704
    Test: ./gradlew :media:check :media2:media2-session:check
    Change-Id: Idce6a53067fd7371c245701e203ac1e09bae9a57
    
  - Add repaint boundary
    
    Repaint boundaries allow us to segment where invalidations
    propagate in the hierarchy. On older platforms, Views are
    repaint boundaries. On newer platforms, RenderNodes are
    used for repaint boundaries.
    
    This CL also allows for a difference between remeasure
    and relayout calls. When a Model is read in the layout()
    lambda, the Layout only needs to call the layout lambda
    and not the whole lambda of the Layout when that Model
    changes. This saves measurement of most of the children.
    This difference is especially useful for something like
    VerticalScroller, where the layout lambda only moves
    its child, which is in a RepaintBoundary.
    
    Test: gradlew connectedCheck
    Test: ran ui-demos
    
    Change-Id: Ibbf8c8f9de90984e2113a4e1f13fa8fa3904e66c
    
  - Stop IDE inspection for empty parentheses after annotations
    
    For composable lambdas, Kotlin currently requires empty parentheses
    to distinguish between the annotation and the functional type, i.e:
    
    children: @Composable() () -> Unit
    
    However, the IDE inspection says that the () after @Composable is
    unecessary, and recommends removing this - breaking the build. Until
    Kotlin supports this type of expression
    (https://youtrack.jetbrains.com/issue/KT-31734) we should simply
    disable warnings.
    
    Test: Manually verified
    Change-Id: I39506cb6c8b2223db9a79947d98dbcbd8d17b283
    
  - Fix indentation in NavigationUI comments.
    
    Test: all test pass
    Change-Id: I38f3edff0c5c439350c684d5c23910774504c048
    
  - Ensure ActionBar is not updated when destination is floating window
    
    When showing a dialog destination, the actionbar updates to show an up
    arrow. This behavior is unexpected and it is not possible to use the
    back button. The action bar should remain the same when interacting with
    any floating window.
    
    This change adds a marker inferface, FloatingWindow, that should be
    implemented by classes considered to be floating windows.
    AbstractAppBarOnDestinationChangeListener checks if the destination is an
    instance of FloatingWindow to determine if the AppBar should be
    updated.
    
    Added label for dialog destination in integration app for testing.
    
    Test: Tested in integration app. ./gradlew checkApi
    BUG: 133600763
    Change-Id: Ie4efab6c265eca13583bd21615f8d571c2236443
    
  - Add documentation for PublishDocsRules
    
    Baby steps toward getting artifact ID associations working again.
    
    Bug: 130297985
    Test: n/a, docs only
    Change-Id: Ie5dc32d2060a697d5dc4107f7f73ea51b91f3180
    
  - Clean up deprecation in androidx.viewpager, set deprecation as fatal
    
    Removes dead code and replaces invalidate(Rect) call as documented.
    
    Bug: 134064312
    Test: ViewPagerWithTabStripTest
    Change-Id: I1633ef81701cb343514a1d87c250e1c6df6c7cb8
    
  - Added simple Scroller benchmark test.
    
    Benchmarks for composition and layout of
    VerticalScroller.
    
    Test: new tests
    Change-Id: I7a57098d145ce0fb849c07a518423d539529a690
    

* Update prebuilts/androidx/external from branch 'androidx-concurrent-release'
  to d028345f552332b99bc8d8a55353ba45b9f6cc54
  - Merge "Snap for 5633419 from a3fc306641ac3d1c3d1e755d81ba27dea7877b36 to androidx-concurrent-release" into androidx-concurrent-release
  - Snap for 5633419 from a3fc306641ac3d1c3d1e755d81ba27dea7877b36 to androidx-concurrent-release
    
    Change-Id: I3832c0f9544070af39893721b629da06a94f01ec
    
  - Merge "Add prebuilts for kotlin mockito 2.1.0" into androidx-master-dev
  - Add prebuilts for kotlin mockito 2.1.0
    
    Test: ./gradlew cC
    Change-Id: I643c4e456861579774598d6c0d106f9fcee66718
    

* Update prebuilts/androidx/internal from branch 'androidx-concurrent-release'
  to 281b0a674df185b26b47443ebfa1a035c3dd7413
  - Merge "Snap for 5633419 from 50f48b81a620e9b0db68239b03abe40266fc7dbc to androidx-concurrent-release" into androidx-concurrent-release
  - Snap for 5633419 from 50f48b81a620e9b0db68239b03abe40266fc7dbc to androidx-concurrent-release
    
    Change-Id: I45ed6df9e9b94367bd356fc0fcee703a50939265
    
  - Merge "Import prebuilts media-1.1.0-beta02 from build 5630214" into androidx-master-dev
  - Import prebuilts media-1.1.0-beta02 from build 5630214
    
    This commit was generated from the command:
    ./import_release_prebuilts.py 5630214 --groups media
    
    Test: ./gradlew buildOnServer
    Change-Id: I3baa32eedfbd06a13097d7ce73a1de1f0c73b13d