Update git submodules
* Update build/soong from branch 'master'
  to c0c9ef996497250493bbe0f45b3ab71b831d071c
  - Provide an option to reduce build's verbosity.
    
    If ANDROID_QUIET_BUILD environment variable is set to '1', do not show 20
    lines of the environment variables. In addition, for the failing step show
    only the step name and output, omitting the command proper (the verbose log
    as well as error.log still contains it).
    If build succeeds, the output of the build itself consists of a single
    line:
    ```
    > m androidmk
    [100% NN/NN] <last command>
    ```
    
    When it fails, the output does not contain sometimes very long command
    line:
    ```
    > m androidmk
    [ 97% NN/MM] test androidmk
    FAILED: <step>
    --- FAIL: TestEndToEnd (0.01s)
        androidmk_test.go:1025: failed testcase 'prebuilt_etc_TARGET_OUT_ETC'
            input:
            include $(CLEAR_VARS)
            LOCAL_MODULE := etc.test1
            LOCAL_MODULE_CLASS := ETC
            LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/foo/bar
            include $(BUILD_PREBUILT)
    
            expected:
            prebuilt_etc {
                name: "etc.test1",
                filename: "foo/bar",
            }
    
            got:
            prebuilt_etc {
                name: "etc.test1",
                filename: "foo/bar",
    
            }
    
    FAIL
    17:50:53 ninja failed with: exit status 1
    ```
    [The related change in build/make/envsetup.sh suppresses timing display
    when the same variable is set.]
    
    Change-Id: I4d3c72457de031ff58a324c2fe98f4c1d10f8239
    Test: treehugger