Update git submodules
* Update bionic from branch 'master'
  to 05ba56d6c0811928b555393e912b1080bc90c923
  - Merge "Fix up a few bionic tests for the clang-r339409 update."
  - Fix up a few bionic tests for the clang-r339409 update.
    
    Disable -Wmemset-transposed-args to ensure that FORTIFY still works
    without it. Also, we can finally enable checking for
    FLT_HAS_SUBNORM/DBL_HAS_SUBNORM/LDBL_HAS_SUBNORM now that those are
    available in Clang.
    
    Bug: http://b/110779387
    Test: build and run bionic unit tests
    Change-Id: I4bf19b870c44d981ecbd1089d0ae6a2496be5441
    

* Update build/soong from branch 'master'
  to ee15f2a7c7d65b9552704468972a8d5372b88046
  - Merge "Switch to clang-r339409."
  - Switch to clang-r339409.
    
    This also changes over llvm-strip to use the -o flag, rather than
    relying on nonstandard (and no longer functional) positional arguments.
    
    Bug: http://b/111998531
    Test: Multiple new builds. For googlers - http://go/clang-r339409-testing
    Change-Id: I8c82d06304af24a001e6552e36e2f540d8e364ce
    

* Update cts from branch 'master'
  to 8b6de71b480048b40b3cd4445182d4e8ec630d2a
  - Merge "Suppress verification of libclang_rt.ubsan_standalone*.so libraries."
  - Suppress verification of libclang_rt.ubsan_standalone*.so libraries.
    
    These libraries are now compiled with -Wl,-z,global, which flags them as
    GLOBAL libraries. Previously, these libraries would fail to load via
    dlopen(). While they are not technically public, we do want them to
    remain GLOBAL, so that they are loaded appropriately for interception.
    
    Bug: http://b/116968618
    Bug: http://b/110779387
    Test: Build with new toolchain and run CTS LinkerNamespacesTest.
    Change-Id: Icefa4c238b425e52e8406bbd8c289384cbfd8671
    

* Update external/honggfuzz from branch 'master'
  to 2e1650918b54f0c331b7a2d55c1f5b24a4fb7775
  - Suppress -Watomic-alignment on 32-bit x86 targets.
    
    external/honggfuzz/linux/perf.c:323:5: error: misaligned or large atomic
    operation may incur significant performance penalty
    [-Werror,-Watomic-alignment]
        ATOMIC_SET(pem->aux_tail, 0);
        ^
    external/honggfuzz/libcommon/util.h:44:26: note: expanded from macro
    'ATOMIC_SET'
    \#define ATOMIC_SET(x, y) __atomic_store_n(&(x), y, __ATOMIC_SEQ_CST)
                              ^
    
    Bug: http://b/110779387
    Test: Build x86 emulator with new toolchain.
    
    Change-Id: I47eec2e1b3f19232df7aa347a59ce95657cbb5b1