Update git submodules
* Update tools/asuite from branch 'master'
  to dee5f5e48b09cf2f2f91fc540286d3965da8e542
  - Merge "AIDEGen: Fix exception happen when add -n"
  - AIDEGen: Fix exception happen when add -n
    
    ide_util_obj = _get_ide_util_instance(args) may get None.
    If direct use ide_util_obj.ide_name(), it may crash AIDEGen.
    This patch checks it is None or not, then use it.
    
    Bug: 132402810
    Test: 1.m aidegen; aidegen-dev framework -n
            It shouldn't show exception:
    	AttributeError: 'NoneType' object has no attribute 'ide_name'
    
    Change-Id: Id9ca897730a3930ee3e50ffa0c527665ec413503