Update git submodules
* Update external/kmod from branch 'master'
  to 3548f5a47e20a9cb60b1b7e7ebd3880dd190088f
  - Merge tag 'v25' into HEAD
    
    kmod 25
    
    Change-Id: I85ca3d431e98fea79526573a9862869a65c85118
    
  - kmod 25
    
  - testsuite: also wrap gettid in syscall()
    
    Not a perfect solution for overriding syscall(), but at least
    it makes the testsuite to pass in a modified nsswitch.conf (one that has
    a module which calls syscall() to get the thread id).
    
  - testsuite: explain why overriding function may fail
    
    On my computer `testsuite/test-modprobe modprobe_install_cmd_loop` was
    failing because when it forks off the shell the child process ends up
    calling syscall() which are are supposed to wrap. Here's the backtrace:
    
    	#0  0x00007ffff6fdb66b in raise () from /lib64/libc.so.6
    	#1  0x00007ffff6fdd381 in abort () from /lib64/libc.so.6
    	#2  0x00007ffff77bac97 in syscall (__sysno=<optimized out>)
    	    at testsuite/init_module.c:362
    	#3  0x00007fffef92d4e7 in hashmap_base_new.lto_priv () from /lib64/libnss_systemd.so.2
    	#4  0x00007fffef953f50 in sd_bus_open_system () from /lib64/libnss_systemd.so.2
    	#5  0x00007fffef943123 in _nss_systemd_getpwuid_r () from /lib64/libnss_systemd.so.2
    	#6  0x00007ffff707eea5 in getpwuid_r@@GLIBC_2.2.5 () from /lib64/libc.so.6
    	#7  0x00007ffff707e608 in getpwuid () from /lib64/libc.so.6
    	#8  0x00005555555859e1 in get_current_user_info.part ()
    	#9  0x00005555555a375a in initialize_shell_variables ()
    	#10 0x0000555555580fde in shell_initialize ()
    	#11 0x00005555555846ff in main ()<Paste>
    
    The reason it fails on my system and not on, for e.g., a new one set up with
    mkosi is that the call to getpwuid() depends on the contents
    /etc/nsswitch.conf. The systemd module calls syscall() to implement gettid()
    which we can't forward due to being a variadic function.
    
    No fix is provided here, but at least it's explained why this happens.
    
  - testsuite: add missing error handling
    
    If we passed an invalid argument to a test it would segfault rather than
    returning an error code.
    
  - testsuite: add Fedora's mkosi configuration
    
    To use the Fedora configuration rather than the default, one should
    use:
    
    	# make DISTRO=fedora mkosi
    
    While at it also reduce the root partition size for Arch, since it
    doesn't need that much.
    
  - testsuite: generalize mkosi support for other distros
    
    Instead of using the mkosi.default symlink, use an env var passed from
    the build system. We would need to pass the --default switch nonetheless
    or change the symlink, making the git tree dirty.
    
    Also, search for installed kernel headers in a way that's compatible
    with more distros. On Fedora, for example, the
    /usr/lib/modules/<kver>/build symlink is only available if there's a
    kernel installed. We don't care about a kernel installed since we don't
    need to boot it on a real machine: the only thing we need is the
    kernel-devel package.
    
  - build: use tool from configure
    
    This way we make sure the tool will be the one we actually configured
    before going through sudo.
    
  - build: add mkosi hooks
    
    Right now there's support for building on Archlinux only.
    
  - depmod: module_is_higher_priority: fix modname length calculation
    
    depmod_module_is_higher_priority checks module's path if it is under
    module root directory and if so uses relative to the root path to
    lookup the module in override and search lists.
    
    Originally only relative path was used in the function, so the
    variables with full path and and path length were changed:
    
           newpath += cfg->dirnamelen + 1;
           newlen -= cfg->dirnamelen + 1;
           oldpath += cfg->dirnamelen + 1;
           oldlen -= cfg->dirnamelen + 1;
    
    Commit 7da6884e7357ac05772e90f6d7e63b1948103fc4 (depmod: implement
    external directories support) changed the logic since it need the
    full path to the module for comparations as well.
    
    Unfortunately, it introduce a mistake in calculation of the relative
    paths replacing '-=' with assignment to a new variable -- the
    'cfg->dirnamelen + 1' value must be substracted all together. It
    breaks, for example, overrides lookup.
    
    Fix the calculation by putting braces around the value in the
    subsctuction expression.
    
    Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
    
  - testsuite: depmod: add override test
    
    Simple test to check if depmod honors override keyword. Uses
    mod-simple.ko for foo/ and override/ directories, search.conf to
    search in foo and built-in and simple override configuration:
    
    override mod-simple 4.4.4 override
    
    The resulting modules.dep should point to the override directory.
    
    Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
    
  - depmod: Don't add .TOC. when it's in the kernel.
    
    d46136bb59c4 ("depmod: Ignore PowerPC64 ABIv2 .TOC. symbol") adds fake
    .TOC. unconditionally but when there is .TOC. in the kernel adding the
    fake one breaks resolving .TOC.
    
    Fixes: d46136bb59c4 ("depmod: Ignore PowerPC64 ABIv2 .TOC. symbol")
    
    Signed-off-by: Michal Suchanek <msuchanek@suse.de>
    
  - man/depmod: Add references in other man pages
    
    Depmod man page is not referenced in some man pages. This makes it
    harder to find through reading documentation.
    
    References added to:
    
    	-man/insmod.xml
    	-man/lsmod.xml
    	-man/modprobe.xml
    	-man/rmmod.xml
    
    Signed-off-by: Christopher Díaz Riveros <chrisadr@gentoo.org>
    
  - libkmod-elf: resolve CRC if module is built with MODULE_REL_CRCS
    
    Normally exported symbol's crc is stored as absolute (SHN_ABS)
    value of special named symbol __crc_<symbol name>.
    
    When the kernel and modules are built with the config option
    CONFIG_MODULE_REL_CRCS, all the CRCs are put in a special section
    and the __crc_<symbol name> symbols values are offsets in the
    section. See patch description of the commit:
    
    https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=56067812d5b0e737ac2063e94a50f76b810d6ca3
    
    Add kmod support of this configuration.
    
    Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
    
  - man/depmod.d: add external keyword description
    
    The commit 'depmod: implement external directories support' added
    external directories support (see
    7da6884e7357ac05772e90f6d7e63b1948103fc4).
    
    This patch documents the extention in the manpage.
    
    Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
    
  - shared/util.c: assert_cc() can only be used inside functions
    
    shared/macro.h has two versions of assert_cc, one that uses gcc
    _Static_assert(), which requires recent enough gcc versions, and one
    that uses a fake array to trigger a build error. The latter can only
    work inside functions, so assert_cc() should only be used inside
    functions.
    
    Fixes the following build failure when building kmod with old gcc
    versions such as gcc 4.3.x:
    
    shared/util.c:52: error: expected identifier or '(' before 'do'
    shared/util.c:52: error: expected identifier or '(' before 'while'
    
    Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>
    
  - testsuite: add tests for external directory support
    
    The following tests added:
    
    - depmod_search_order_external_first -- checks if external module
      is taken in use when it has higher priority;
    - depmod_search_order_external_last -- checks if external module
      is skipped when it has lower priority;
    - test_modinfo_external -- checks if modinfo is able to look up
      correct external module;
    - modprobe_external -- checks if modprobe is able to look up
      correct external module and loads it.
    
    Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
    
  - depmod: implement external directories support
    
    The idea is to add a configuration keyword, external, which
    will list directories for scanning for particular kernel version
    mask:
    
    external 4.10 /the/modules/dir /second/modules/dir
    
    And extend "search" keyword to set it's priority with pseudo dir
    "external" (as it's done for built-in):
    
    search subdir external subdir2 built-in subdir3
    
    (actually, the version is the same as for override keyword: * or
    posix regexp, so example above is a bit incorrect).
    
    All other logic left the same: if there are duplicates, only one
    is under consideration and it is unloadable if it is bad.
    
    The resulting modules.dep will contain entries a-la:
    
    /the/modules/dir/module1.ko:
    kernel/module2.ko: /the/modules/dir/module1.ko
    
    (here /lib/modules/$(uname -r)/kernel/module2.ko depends of
    symbols, provided by /the/modules/dir/module1.ko and external has
    higher priority).
    
    modprobe and modinfo understand it out of box.
    
    This is a pretty simple extention of existing logic, since now
    depmod already is able to:
    
    a) scan modules with full path from command line without -a
    switch;
    b) detects broken symbol dependencies and broken modversions,
    what assumes, that modules are already are not built for the
    existing kernel.
    
    Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
    
  - test-depmod: avoid warning when we don't have zlib
    
    testsuite/test-depmod.c:31:21: warning: ‘depmod_modules_order_for_compressed’ defined but not used [-Wunused-function]
     static noreturn int depmod_modules_order_for_compressed(const struct test *t)
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
  - depmod: rewrite depmod modules search with scratchbuf
    
    The recursive search code used used pretty big, PATH_MAX,
    automatic storage buffer for the module directory scanning. Some
    time ago there was scratchbuf implemented, which dynamically
    reallocates its buffer on demand. The patch takes it in use for
    the scanning code also. The initial size is hardcoded to 256
    bytes which sounds good enough for most usecases so there should
    be not many reallocations.
    
    Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
    
  - depmod: create depmod dir independent search function
    
    Prepare to implement external directories support.
    
    The patch splits depmod_modules_search() function to two
    functions: depmod_modules_search(), called by the high level with
    intention to search all possible modules, and
    depmod_module_search_path(), which takes path as a parameter and
    scans modules under the path only. Initially it is used to scan
    the same depmod->cfg->dirname path only.
    
    Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
    
  - depmod: search key: move builtin detection under the add function
    
    Prepare to implement external directories support.
    
    It's better to isolate behaviour difference under the
    cfg_search_add() call, then make the client code aware of it.
    
    In case of external modules/directories support, there will be
    one more keyword added, so making the clients aware of it makes
    even less sense.
    
    Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
    
  - depmod: fix errorpath memleaks in report cycles logic
    
    The c7ce9f0c80f3d561078a78205a14c5ba7663cfdd commit (depmod:
    handle nested loops) introduced a bunch of possible memory leaks
    in error path. In the real world scenario it is not a problem,
    since the utility quits if it detects any of the errors, but from
    the programming point of view, it is not nice. So, add the
    cleanups.
    
    Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
    
  - libkmod: modinfo: implement signature output
    
    Signature was ignored from the modinfo. Implement its parsing
    from the module data and add its output to the modinfo utility.
    
    Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
    
  - libkmod: modinfo: implement line splitting in hex_to_str
    
    The key output is usually short, but for signature it is more
    readable to output it in several lines.
    
    Implement line splitting. Set line limit hardcoded to 20 hex
    numbers (not characters).
    
    Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
    
  - libkmod: modinfo: use own function for sig_key hex output
    
    Refactor the code a bit to make it easier to extend for signature
    output.
    
    kmod_module_get_info() creats a hex string for the sig_key data
    inplace. Separate it into own kmod_module_hex_to_string function
    and handle the branch in the new kmod_module_info_append_hex,
    keeping the same signature as the non-hex version.
    
    Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
    
  - libkmod: modinfo: fix sig_id output
    
    For some reason the key for sig_id was set to "signature". The
    length was calculated against the proper string, as the result in
    the output it was truncated to "signat".
    
    Pass the proper key to the kmod_module_info_append() call.
    
    Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>