Update git submodules
* Update art from branch 'master'
  to e58624f221b967553d7b71f14d8677ceaa000553
  - Various renames following the name change from "Runtime APEX" to "ART APEX".
    
    In particular ANDROID_RUNTIME_ROOT is now ANDROID_ART_ROOT.
    
    Test: Build & boot
    Test: art/tools/run-gtests.sh in chroot
    Test: art/test/testrunner/testrunner.py --target --64 in chroot
    Test: art/tools/run-libcore-tests.sh --mode=device --variant=X64 in chroot
    Test: art/tools/run-jdwp-tests.sh --mode=device --variant=X64 in chroot
    Test: m test-art-host-gtest
    Test: art/test/testrunner/testrunner.py --host --64
    Test: art/tools/run-jdwp-tests.sh --mode=host
    Bug: 135753770
    Change-Id: Ia74da964e54cf396d66e9e12ea56da4e9483662a
    

* Update external/vogar from branch 'master'
  to e29e8a57f3e0bb2f7cc2f194606ca205f9d8a6cb
  - Rename ANDROID_RUNTIME_ROOT to ANDROID_ART_ROOT following APEX module name change.
    
    Test: Build & boot
    Test: art/tools/run-libcore-tests.sh --mode=device --variant=X64 in ART chroot test environment
    Test: art/tools/run-libcore-tests.sh --mode=host
      (fails on org.apache.harmony.tests.java.lang.MathTest#test_cbrt_D, but seems unrelated:
      junit.framework.AssertionFailedError: expected:<3.0> but was:<3.0000000000000004>)
    Bug: 135753770
    Change-Id: Icfd23c0dc0a3d868dc519d8c28c9413ce37cfdb0
    

* Update frameworks/base from branch 'master'
  to 80fd44500cb4c72b504512b45cac8742ccff7db5
  - Merge "Rename ANDROID_RUNTIME_ROOT to ANDROID_ART_ROOT following APEX module name change."
  - Rename ANDROID_RUNTIME_ROOT to ANDROID_ART_ROOT following APEX module name change.
    
    Test: Boot
    Bug: 135753770
    Change-Id: I930027fb0ad18d9d06165bbfbfe54d88bc28530d
    

* Update system/core from branch 'master'
  to 0560d0ef6f80da76298057b6cf06d1766a1266e9
  - Merge "Rename ANDROID_RUNTIME_ROOT to ANDROID_ART_ROOT following APEX module name change."
  - Rename ANDROID_RUNTIME_ROOT to ANDROID_ART_ROOT following APEX module name change.
    
    Test: Boot
    Bug: 135753770
    Change-Id: Ie9a8043ee350164c01a66f1a7ab1b3205076a5c4