Update git submodules
* Update build/make from branch 'master'
  to fea4263ec19fcdad39d21a9700570f5cd0159342
  - Merge "releasetools: Fix the error message."
  - releasetools: Fix the error message.
    
    This avoids showing a message as below:
    
    raise BuildImageError("Failed to get tune2fs usage:\n{}".format(output))
    UnboundLocalError: local variable 'output' referenced before assignment
    
    The `output` won't be set under such a case, which unfortunately hides
    the real cause. This CL addresses the issue by letting it throw
    implicitly, which contains the command and outputs.
    
    Test: `m dist`
    Test: `python -m unittest test_build_image`
    Change-Id: Icf015bab8869d150516246ed73552f6502127cdf