Update git submodules
* Update external/qemu from branch 'emu-master-dev'
  to 392b28a8d7b078a95577d524fa69f7e34b97164f
  - Merge "Fix build protoc build dependency." into emu-master-dev
  - Fix build protoc build dependency.
    
    Build refactoring towards using CMake exposed a concurrency issue. The
    build could fail due to the protoc headers not being available:
    
    android/android-emu/android/skin/qt/extended-pages/camera-virtualscene-subpage.cpp:17:51:
    fatal error: android/metrics/proto/studio_stats.pb.h: No such file
    
    Turns the generated .o file depends on studio_stats and not the .cpp
    file. Due to this we now take an explicit dependency on the generated
    file.
    
    Here are the reasons we have might not have seen it:
    
    - We have the compiler construct an additional header dependency graph
      during build. This will include the protobuf header files.
    - If we succeeded a build once, a header file will exist, we just migth
      include the wrong one.
    - Our development machines are crazy fast. protoc "ALWAYS" seems to
      finish before we actually try to compile the .c file.
    - The build machines don't seem to have this speed :-(
    
    Note, that we take a dependency on the pb.cc file and not the pb.h file
    due to another bug (b/115634240).
    
    Test: make -Bnd now lists this:
         Prerequisite
         'objs/build/intermediates64/proto-sources/android/metrics/proto/studio_stats.pb.cc'
         is newer than target
         'android/android-emu/android/skin/qt/extended-pages/camera-virtualscene-subpage.cpp'.
    Test: Added sleep 5 in front of protoc and build will succeed.
    
    Bug: b/115589098
    Change-Id: I69e9df6b147e2be7434af891c886ee7ba7a06c75